<!DOCTYPE html>
<html lang="en"><head>
<script src="lecture09_files/libs/clipboard/clipboard.min.js"></script>
<script src="lecture09_files/libs/quarto-html/tabby.min.js"></script>
<script src="lecture09_files/libs/quarto-html/popper.min.js"></script>
<script src="lecture09_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="lecture09_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lecture09_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="lecture09_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Sam Wiwatanapataphee (275287a@curtin.edu.au)">
  <meta name="dcterms.date" content="2026-05-14">
  <title>STAT2005 Computer Simulation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="lecture09_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="lecture09_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="lecture09_files/libs/revealjs/dist/theme/quarto-1ebbb7785f905cfe4b305ac95dd97afc.css">
  <link href="lecture09_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="lecture09_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="lecture09_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="lecture09_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="lecture09_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="lecture09_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">STAT2005 Computer Simulation</h1>
  <p class="subtitle">Lecture 9 — Monte Carlo Integration &amp; Markov Chain Monte Carlo</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Sam Wiwatanapataphee (275287a@curtin.edu.au) 
</div>
</div>
</div>

  <p class="date">14 May 2026</p>
</section>
<section id="goals-today" class="slide level2">
<h2>Goals today</h2>
<p><br></p>
<div class="columns">
<div class="column">
<ul>
<li class="fragment"><strong>Part 1:</strong> Monte Carlo Integration
<ul>
<li class="fragment">Integration as Expectation</li>
<li class="fragment">Monte Carlo Estimator</li>
<li class="fragment">Monte Carlo Error and Convergence</li>
<li class="fragment">Pros and Cons of Monte Carlo Integration</li>
<li class="fragment">Transition to Markov Chain Monte Carlo</li>
</ul></li>
</ul>
</div><div class="column">
<ul>
<li class="fragment"><strong>Part 2:</strong> Markov Chain Monte Carlo (MCMC)
<ul>
<li class="fragment">Introduction to MCMC</li>
<li class="fragment">Gibbs Sampling
<ul>
<li class="fragment">Bivariate Normal Distribution</li>
<li class="fragment">Multivariate Normal Distribution</li>
<li class="fragment">Bayesian Normal Model</li>
</ul></li>
</ul></li>
</ul>
</div></div>
<p><br></p>
<div class="center">
<ul>
<li class="fragment"><strong>Part 3:</strong> Bayesian Gibbs Sampling
<ul>
<li class="fragment">Case Study - <a href="https://zamnolence.github.io/_book/10_6_energysavings.html">💡 Estimating Household Energy Savings</a></li>
</ul></li>
</ul>
</div>
</section>
<section>
<section id="part-1-monte-carlo-integration" class="title-slide slide level1 center">
<h1>Part 1: Monte Carlo Integration</h1>

</section>
<section id="motivation-for-monte-carlo-integration" class="slide level2">
<h2>Motivation for Monte Carlo Integration</h2>
<p>In many scientific and statistical problems, we are interested in quantities that can be written as <strong>integrals</strong>.</p>
<div class="fragment">
<p>Examples include:</p>
<ul>
<li class="fragment">probabilities;</li>
<li class="fragment">expected values;</li>
<li class="fragment">variances;</li>
<li class="fragment">areas and volumes;</li>
<li class="fragment">posterior means in Bayesian statistics.</li>
</ul>
</div>
<div class="fragment">
<p>For simple models, calculus may provide exact solutions.</p>
</div>
<div class="fragment">
<p>However, in realistic applications:</p>
<ul>
<li class="fragment">analytical solutions may not exist;</li>
<li class="fragment">integrals may be high-dimensional;</li>
<li class="fragment">models may be computationally complex.</li>
</ul>
</div>
<div class="block yellow fragment center">
<p><strong>Key Idea:</strong> Monte Carlo integration uses averages computed from random samples to approximate complicated integrals.</p>
</div>
<div class="fragment">
<p>This transforms integration from a <strong>calculus problem</strong> into a <strong>simulation problem</strong>.</p>
</div>
</section>
<section id="integration-as-expectation" class="slide level2">
<h2>Integration as Expectation</h2>
<p><span class="space-out"></span></p>
<p>Recall from probability theory that the expectation of a function of a random variable can be expressed as an integral,</p>
<p><span class="math display">\[
\mathbb{E}[X] = \int x f(x)\,dx,
\]</span></p>
<p><span class="space-out"></span></p>
<p>where <span class="math inline">\(f(x)\)</span> is the probability density function of the random variable <span class="math inline">\(X\)</span>.</p>
<p><span class="space-out"></span></p>
<div class="note fragment">
<p>Suppose <span class="math inline">\(X\)</span> is a continuous random variable with probability density function <span class="math inline">\(f(x)\)</span>, and let <span class="math inline">\(h(x)\)</span> be a function of interest. Then, the expectation of <span class="math inline">\(h(X)\)</span> is</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\mathbb{E}[h(X)] = \int h(x)f(x)\,dx.
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Many difficult integrals can be rewritten as expectations of random variables. And once we have this connection, we can use random sampling to estimate these expectations, which is the basis of Monte Carlo integration.</p>
</div>
<p><span class="space-out"></span></p>
<div class="block blue fragment center">
<p><strong>Monte Carlo integration</strong> is a method for estimating the value of an integral using random sampling. The basic idea is to sample points from a probability distribution and use these samples to approximate the integral.</p>
</div>
</section>
<section class="slide level2">

<h3 id="example-1-estimating-an-expected-value">Example 1: Estimating an Expected Value</h3>
<div class="example fragment">
<p>Compute the following integral using Monte Carlo integration:</p>
<p><span class="math display">\[
I = \int_0^1 x^2\,dx.
\]</span></p>
</div>
<div class="fragment">
<p>Since this example is quite simple, we can compute the integral analytically for comparison:</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
I = \int_0^1 x^2\,dx
= \left[ \frac{x^3}{3} \right]_0^1
= \frac{1}{3}.
\]</span></p>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">library</span>(Ryacas)</span>
<span id="cb1-2"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">ysym</span>(<span class="st">"x"</span>)</span>
<span id="cb1-3"><a href=""></a>f <span class="ot">&lt;-</span> x<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-4"><a href=""></a>F <span class="ot">&lt;-</span> <span class="fu">integrate</span>(f, x); F</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>y: x^3/3</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href=""></a><span class="im">import</span> sympy <span class="im">as</span> sp</span>
<span id="cb3-2"><a href=""></a><span class="im">from</span> scipy.integrate <span class="im">import</span> quad</span>
<span id="cb3-3"><a href=""></a></span>
<span id="cb3-4"><a href=""></a>x <span class="op">=</span> sp.symbols(<span class="st">'x'</span>)</span>
<span id="cb3-5"><a href=""></a>f <span class="op">=</span> x<span class="op">**</span><span class="dv">2</span></span>
<span id="cb3-6"><a href=""></a>F <span class="op">=</span> sp.integrate(f, x)</span>
<span id="cb3-7"><a href=""></a><span class="co"># print(sp.latex(F)) # copiable LaTeX</span></span>
<span id="cb3-8"><a href=""></a>pprint(F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div class="fragment">
<p>To apply Monte Carlo integration, we can interpret the integral as an expectation. We can rewrite the integral as:</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
I = \int_0^1 x^2(1)\,dx = \mathbb{E}[X^2],
\]</span></p>
<p><span class="space-out"></span></p>
<p>where <span class="math inline">\(f(x)=1\)</span>, and <span class="math inline">\(X \sim \text{Uniform}(0,1)\)</span> corresponds to the limit of integration.</p>
</div>
</section>
<section class="slide level2 scrollable">

<h4 id="example-1-estimating-an-expected-value-cont.">Example 1: Estimating an Expected Value (Cont.)</h4>
<p><span class="space-out"></span></p>
<p>To estimate <span class="math inline">\(I\)</span>, we can</p>
<ol type="1">
<li class="fragment">generate <span class="math inline">\(N\)</span> random samples from the <span class="math inline">\(\text{Uniform}(0,1)\)</span> distribution,</li>
<li class="fragment">compute <span class="math inline">\(X_i^2\)</span> for each sample, and</li>
<li class="fragment">take the average.</li>
</ol>
<p><span class="space-out"></span></p>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb4-2"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb4-3"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n)</span>
<span id="cb4-4"><a href=""></a>x_squared <span class="ot">&lt;-</span> x<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb4-5"><a href=""></a>estimate <span class="ot">&lt;-</span> <span class="fu">mean</span>(x_squared)</span>
<span id="cb4-6"><a href=""></a><span class="fu">cat</span>(<span class="st">"Monte Carlo estimate:"</span>, estimate, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Monte Carlo estimate: 0.3327025 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>I <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(x) x<span class="sc">^</span><span class="dv">2</span>, <span class="at">lower=</span><span class="dv">0</span>, <span class="at">upper=</span><span class="dv">1</span>)<span class="sc">$</span>value</span>
<span id="cb6-2"><a href=""></a><span class="fu">cat</span>(<span class="st">"Analytical value:"</span>, I, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analytical value: 0.3333333 </code></pre>
</div>
</div>
<p><span class="space-out"></span></p>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-2"><a href=""></a>np.random.seed(<span class="dv">1234</span>)</span>
<span id="cb8-3"><a href=""></a>n <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb8-4"><a href=""></a>x <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n)</span>
<span id="cb8-5"><a href=""></a>x_squared <span class="op">=</span> x<span class="op">**</span><span class="dv">2</span></span>
<span id="cb8-6"><a href=""></a>estimate <span class="op">=</span> np.mean(x_squared)</span>
<span id="cb8-7"><a href=""></a><span class="bu">print</span>(<span class="st">"Monte Carlo estimate:"</span>, <span class="bu">round</span>(estimate, <span class="dv">4</span>))</span>
<span id="cb8-8"><a href=""></a>I, _ <span class="op">=</span> quad(<span class="kw">lambda</span> x: x<span class="op">**</span><span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb8-9"><a href=""></a><span class="bu">print</span>(<span class="st">"Analytical value:"</span>, <span class="bu">round</span>(I, <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>The Monte Carlo estimate will be close to the analytical value of <span class="math inline">\(1/3\)</span>, and the accuracy improves as we increase the number of samples <span class="math inline">\(N\)</span>.</p>
</div>
</section>
<section id="monte-carlo-estimator" class="slide level2">
<h2>Monte Carlo Estimator</h2>
<div class="note">
<p>Suppose <span class="math inline">\(X_1,X_2,\dots,X_n\)</span> are independent and identically distributed (i.i.d.) samples from density <span class="math inline">\(f(x)\)</span>.</p>
<p>The Monte Carlo estimator of an integral</p>
<p><span id="eq-mc-integral"><span class="math display">\[
I = \int h(x) f(x)\,dx
=
\mathbb{E}[h(X)].
\tag{1}\]</span></span></p>
<p>is</p>
<p><span id="eq-mc-estimator"><span class="math display">\[
\hat I_n
=
\frac{1}{n}\sum_{i=1}^n h(X_i).
\tag{2}\]</span></span></p>
<p>This estimator is simply the <strong>sample mean of the simulated values</strong>.</p>
</div>
<div class="fragment" style="font-size: 1.4em;">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why This Works</strong></p>
</div>
<div class="callout-content">
<p>Monte Carlo integration is justified by the <strong>Law of Large Numbers (LLN)</strong>.</p>
<p>Recall from Week 1 that if <span class="math inline">\(X_1,X_2,\dots,X_n\)</span> are i.i.d. with finite mean <span class="math inline">\(\mu\)</span>, then</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\bar x
\to
\mu
\quad \text{as } n\to\infty.
\]</span></p>
<p><span class="space-out"></span></p>
<p>Since the Monte Carlo estimator <span class="math inline">\(\hat I_n\)</span> is simply a sample average, it converges to the true expectation <span class="math inline">\(\mathbb{E}[h(X)]\)</span> as the number of samples increases. Thus,</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\hat I_n \to I \quad \text{as } n\to\infty.
\]</span></p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h3 id="example-2-estimating-an-area-pi-of-a-unit-circle">Example 2: Estimating an Area <span class="math inline">\(\pi\)</span> of a Unit Circle</h3>
<div class="example">
<p>Consider the square <span class="math inline">\([-1,1]\times[-1,1]\)</span> with area 4<sup>1</sup>.</p>
<p>Inside the square is a circle of radius 1 centred at the origin. The equation of the circle is</p>
<p><span id="eq-unitcircle"><span class="math display">\[
x^2 + y^2 = 1.
\tag{3}\]</span></span></p>
<p>Since the radius of the circle is 1, the area of the circle is</p>
<p><span class="math display">\[
\pi r^2 = \pi (1)^2 = \pi.
\]</span></p>
<p>How can we use Monte Carlo integration to estimate the area of the unit circle <span class="math inline">\(\pi\)</span>?</p>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb9-2"><a href=""></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb9-3"><a href=""></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="cn">NA</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ylab=</span><span class="st">""</span>, <span class="at">xlab=</span><span class="st">""</span>)</span>
<span id="cb9-4"><a href=""></a><span class="fu">symbols</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="at">circles=</span><span class="dv">1</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">fg=</span><span class="st">"blue"</span>)</span>
<span id="cb9-5"><a href=""></a><span class="fu">rect</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="at">border=</span><span class="st">"red"</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb9-6"><a href=""></a><span class="fu">grid</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="lecture09_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center" width="288"></p>
</figure>
</div>
</div>
</div>
<aside><ol class="aside-footnotes"><li id="fn1"><p><span class="math inline">\(\text{Area of the square} = 2 \times 2 = 4\)</span></p></li></ol></aside></section>
<section class="slide level2">

<h4 id="method-1-using-curve-height">Method 1: Using Curve-Height</h4>
<p><span class="space-out"></span></p>
<p>The first method is to express the area as a single integral and then apply the Monte Carlo estimator.</p>
<div class="tip fragment">
<p><strong>Step 1: Expressing Area as an Integral</strong></p>
</div>
<div class="fragment">
<p>From <a href="#/eq-unitcircle" class="quarto-xref">Equation&nbsp;3</a>, rewriting it in terms of <span class="math inline">\(y\)</span> gives</p>
<p><span class="math display">\[
y = \pm\sqrt{1-x^2}.
\]</span></p>
</div>
<div class="fragment">
<p>Then, from the geometric interpretation of the definite integral, the area of the circle can be written as</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;= \int_{-1}^1 \left( \sqrt{1-x^2} - (-\sqrt{1-x^2}) \right) dx \\
A &amp;= \int_{-1}^1 2\sqrt{1-x^2}\,dx.
\end{aligned}
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="tip fragment">
<p><strong>Step 2: Rewriting as an Expectation</strong></p>
</div>
<div class="fragment">
<p>Since <span class="math inline">\(X \sim \text{Uniform}(-1,1)\)</span>, its density is</p>
<p><span class="math display">\[
f(x) = \frac12, \quad -1 &lt; x &lt; 1.
\]</span></p>
</div>
<div class="fragment">
<p>Rewriting the area integral as in <a href="#/eq-mc-integral" class="quarto-xref">Equation&nbsp;1</a>, we can express the area as an expectation</p>
<p><span class="space-out"></span></p>
<p><span id="eq-area-expectation"><span class="math display">\[
A = \int_{-1}^1 4\sqrt{1-x^2} \left(\frac12\right)\,dx = \mathbb{E}[4\sqrt{1-X^2}].
\tag{4}\]</span></span></p>
</div>
</section>
<section class="slide level2">

<div class="tip">
<p><strong>Step 3: Apply Monte Carlo Estimator</strong></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>From <a href="#/eq-mc-estimator" class="quarto-xref">Equation&nbsp;2</a>, the Monte Carlo estimator of the area is given by</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\hat A_n
=
\frac1n\sum_{i=1}^n 4\sqrt{1-X_i^2},
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Since <span class="math inline">\(A = \pi\)</span>, the Monte Carlo estimate of <span class="math inline">\(\pi\)</span> is</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\boxed{
\hat \pi_n
=
\frac1n\sum_{i=1}^n 4\sqrt{1-X_i^2},}
\]</span></p>
<p>where <span class="math inline">\(X \sim \text{Uniform}(-1,1)\)</span>.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-2"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb10-3"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb10-4"><a href=""></a>pi_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="dv">4</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">-</span>x<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb10-5"><a href=""></a>pi <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(x) <span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">-</span>x<span class="sc">^</span><span class="dv">2</span>), <span class="at">lower=</span><span class="sc">-</span><span class="dv">1</span>, <span class="at">upper=</span><span class="dv">1</span>)<span class="sc">$</span>value</span>
<span id="cb10-6"><a href=""></a><span class="fu">cat</span>(<span class="st">"Analytical value: "</span>, <span class="fu">round</span>(pi, <span class="dv">5</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-7"><a href=""></a>    <span class="st">"Monte Carlo estimate: "</span>, <span class="fu">round</span>(pi_hat, <span class="dv">5</span>), <span class="at">sep=</span><span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analytical value: 3.14159
Monte Carlo estimate: 3.14051</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb12-2"><a href=""></a><span class="im">from</span> scipy.integrate <span class="im">import</span> quad</span>
<span id="cb12-3"><a href=""></a></span>
<span id="cb12-4"><a href=""></a>np.random.seed(<span class="dv">1234</span>)</span>
<span id="cb12-5"><a href=""></a>n <span class="op">=</span> <span class="dv">5000</span></span>
<span id="cb12-6"><a href=""></a>x <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, n)</span>
<span id="cb12-7"><a href=""></a>pi_hat <span class="op">=</span> np.mean(<span class="dv">4</span> <span class="op">*</span> np.sqrt(<span class="dv">1</span> <span class="op">-</span> x<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb12-8"><a href=""></a>pi, _ <span class="op">=</span> quad(<span class="kw">lambda</span> x: <span class="dv">2</span> <span class="op">*</span> np.sqrt(<span class="dv">1</span> <span class="op">-</span> x<span class="op">**</span><span class="dv">2</span>), <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb12-9"><a href=""></a><span class="bu">print</span>(<span class="st">"Analytical value: "</span>, <span class="bu">round</span>(pi, <span class="dv">5</span>), </span>
<span id="cb12-10"><a href=""></a>      <span class="st">"</span><span class="ch">\n</span><span class="st">Monte Carlo estimate: "</span>, <span class="bu">round</span>(pi_hat, <span class="dv">5</span>), sep<span class="op">=</span><span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</section>
<section class="slide level2">

<h4 class="unnumbered" id="method-2-using-dartboard">Method 2: Using Dartboard</h4>
<p>The second method is to express the area as a double integral and then apply the Monte Carlo estimator. This method is more intuitive and closely related to the original idea of Monte Carlo methods, which is to use random sampling to approximate areas and volumes.</p>
<div class="tip fragment">
<p><strong>Step 1: Expressing Area as an Integral</strong></p>
</div>
<div class="fragment">
<p>The area of the circle can be written as a double integral,</p>
<p><span class="math display">\[
A = \iint_{[-1, 1]^2} \mathbf{1}(x^2 + y^2 \le 1) \, dx\,dy,
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\mathbf{1}(x^2 + y^2 \le 1) = \begin{cases}
1 &amp; \text{if } x^2 + y^2 \le 1, \\
0 &amp; \text{otherwise}.
\end{cases}
\]</span></p>
<p>This indicator function simply checks whether a point belongs to the circle. The integral therefore “adds up” all points inside the circle, producing the total area.</p>
</div>
<div class="tip fragment">
<p><strong>Step 2: Rewriting as an Expectation</strong></p>
</div>
<div class="fragment">
<p>Since <span class="math inline">\((X,Y)\)</span> is uniformly distributed over the square <span class="math inline">\([a, b] \times [c, d] = [-1,1]\times[-1,1]\)</span>, its joint density is</p>
<p><span class="math display">\[
\begin{aligned}
f(x,y) &amp;= f_X(x)f_Y(y) \\
&amp;= \frac{1}{b-a} \cdot \frac{1}{d-c} \\
f(x,y) &amp;= \frac{1}{4}, \quad -1 &lt; x &lt; 1,\; -1 &lt; y &lt; 1.
\end{aligned}
\]</span></p>
</div>
</section>
<section class="slide level2">

<p>Since</p>
<p><span class="math display">\[
f(x,y) = \frac{1}{4}, \quad -1 &lt; x &lt; 1,\; -1 &lt; y &lt; 1,
\]</span></p>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>rewriting the area integral as in <a href="#/eq-mc-integral" class="quarto-xref">Equation&nbsp;1</a>, we can express the area as an expectation of the indicator function</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
A = \iint_{[-1, 1]^2} 4\cdot\mathbf{1}(x^2 + y^2 \le 1) \left(\frac{1}{4}\right) dx\,dy = 4\cdot\mathbb{E}[\mathbf{1}(X^2 + Y^2 \le 1)].
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="tip fragment">
<p><strong>Step 3: Apply Monte Carlo Estimator</strong></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>From <a href="#/eq-mc-estimator" class="quarto-xref">Equation&nbsp;2</a>, the Monte Carlo estimator of the area is given by</p>
<p><span class="math display">\[
\hat A_n
=
4\cdot\frac1n\sum_{i=1}^n \mathbf{1}(X_i^2 + Y_i^2 \le 1),
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Since <span class="math inline">\(A = \pi\)</span>, the Monte Carlo estimate of <span class="math inline">\(\pi\)</span> is</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\boxed{
\hat \pi_n
=
4\cdot \frac1n\sum_{i=1}^n \mathbf{1}(X_i^2 + Y_i^2 \le 1),}
\]</span></p>
<p><span class="space-out"></span></p>
<p>where <span class="math inline">\((X,Y) \sim \text{Uniform}([-1,1]\times[-1,1])\)</span>.</p>
</div>
</section>
<section class="slide level2">

<div class="tip">
<p><strong>Step 4: From expectation to probability</strong></p>
</div>
<p>If a point <span class="math inline">\((X,Y)\)</span> is generated uniformly inside the square, then the probability that a point falls inside the circle is</p>
<p><span id="eq-prob-area"><span class="math display">\[
P(x^2 + y^2 \le 1)
=
\frac{\text{Area of the circle}}{\text{Area of the square}}
=
\frac{\pi}{4}.
\tag{5}\]</span></span></p>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Rearranging gives</p>
<p><span class="math display">\[
\pi = 4 \times P(x^2 + y^2 \le 1).
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Suppose we generate <span class="math inline">\(n\)</span> random points uniformly inside the square (from <span class="math inline">\((X,Y) \sim \text{Uniform}([-1,1]\times[-1,1])\)</span>) and let</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
k = \text{number of points that satisfy } x^2 + y^2 \le 1.
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Then, the proportion of points that fall inside the circle is</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\frac{k}{n} \approx P(x^2 + y^2 \le 1).
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Therefore, the Monte Carlo estimate of <span class="math inline">\(\pi\)</span> can be simplified to</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\boxed{
\hat \pi
\approx
4\times
\frac{k}{n}}
\]</span></p>
</div>
<div class="fragment">
<p>As the number of simulated points increases, the estimate becomes more accurate by the Law of Large Numbers.</p>
</div>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb13-2"><a href=""></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb13-3"><a href=""></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="cn">NA</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ylab=</span><span class="st">""</span>, <span class="at">xlab=</span><span class="st">""</span>)</span>
<span id="cb13-4"><a href=""></a><span class="fu">points</span>(<span class="fu">runif</span>(<span class="dv">1000</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="fu">runif</span>(<span class="dv">1000</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">pch=</span><span class="dv">16</span>, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">col=</span><span class="fu">rgb</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.5</span>))</span>
<span id="cb13-5"><a href=""></a><span class="fu">symbols</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="at">circles=</span><span class="dv">1</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">fg=</span><span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lecture09_files/figure-revealjs/unnamed-chunk-8-1.png" class="quarto-figure quarto-figure-center r-stretch" width="288"><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb14-2"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb14-3"><a href=""></a>y <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb14-4"><a href=""></a>inside <span class="ot">&lt;-</span> (x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> y<span class="sc">^</span><span class="dv">2</span> <span class="sc">&lt;=</span> <span class="dv">1</span>)</span>
<span id="cb14-5"><a href=""></a>pi_hat <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">*</span> <span class="fu">mean</span>(inside)</span>
<span id="cb14-6"><a href=""></a>pi_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.144</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href=""></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb16-3"><a href=""></a></span>
<span id="cb16-4"><a href=""></a>np.random.seed(<span class="dv">1234</span>)</span>
<span id="cb16-5"><a href=""></a>x <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1000</span>)</span>
<span id="cb16-6"><a href=""></a>y <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1000</span>)</span>
<span id="cb16-7"><a href=""></a></span>
<span id="cb16-8"><a href=""></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb16-9"><a href=""></a>ax.set_aspect(<span class="st">'equal'</span>)</span>
<span id="cb16-10"><a href=""></a>ax.set_xlabel(<span class="st">""</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">""</span>)</span>
<span id="cb16-11"><a href=""></a>ax.scatter(x, y, s<span class="op">=</span><span class="dv">10</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb16-12"><a href=""></a>circle <span class="op">=</span> plt.Circle((<span class="dv">0</span>, <span class="dv">0</span>), <span class="dv">1</span>, fill<span class="op">=</span><span class="va">False</span>, color<span class="op">=</span><span class="st">'red'</span>, linewidth<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb16-13"><a href=""></a>ax.add_patch(circle)</span>
<span id="cb16-14"><a href=""></a>plt.show()</span>
<span id="cb16-15"><a href=""></a></span>
<span id="cb16-16"><a href=""></a>n <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb16-17"><a href=""></a>x <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, n)</span>
<span id="cb16-18"><a href=""></a>y <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, n)</span>
<span id="cb16-19"><a href=""></a>inside <span class="op">=</span> (x<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> y<span class="op">**</span><span class="dv">2</span> <span class="op">&lt;=</span> <span class="dv">1</span>)</span>
<span id="cb16-20"><a href=""></a>pi_hat <span class="op">=</span> <span class="dv">4</span> <span class="op">*</span> np.mean(inside)</span>
<span id="cb16-21"><a href=""></a>pi_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section class="slide level2">

<h4 id="curve-height-vs-dartboard-method">Curve-Height vs Dartboard Method</h4>
<ul>
<li class="fragment">The curve-height method is better for showing Monte Carlo integration.</li>
<li class="fragment">The dartboard method is better for showing simulation-based probability/area estimation.</li>
<li class="fragment">They are both valid methods for estimating the area of the circle, and they will give similar estimates as the number of samples increases.</li>
</ul>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p><strong>Question:</strong> Which estimator is better in practice?</p>
</div>
<div class="fragment center" style="font-size: 1.2em;">
<p><strong>Hint:</strong> Check the variance of the two estimators.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Recall the two estimators:</p>
<p><span class="space-out"></span></p>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Random Variable</th>
<th>Monte Carlo Estimator <span class="math inline">\(\hat \pi_n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Curve-Height</td>
<td><span class="math inline">\(X \sim U(-1,1)\)</span></td>
<td><span class="math inline">\(\hat \pi_1 = \frac1n\sum_{i=1}^n 4\sqrt{1-X_i^2}\)</span></td>
</tr>
<tr class="even">
<td>Dartboard</td>
<td><span class="math inline">\((X,Y) \sim U([-1,1]^2)\)</span></td>
<td><span class="math inline">\(\hat \pi_2 = \frac4n\sum_{i=1}^n \mathbf{1}(X_i^2 + Y_i^2 \le 1)\)</span></td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<p>Both estimators are unbiased:</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\mathbb E[\hat\pi_1] = \mathbb E[\hat\pi_2] = \pi.
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p>How to compute the variance of these estimators?</p>
</div>
</section>
<section class="slide level2">

<h4 id="estimator-1-curve-height">Estimator 1: Curve-Height</h4>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Random Variable</th>
<th>Monte Carlo Estimator <span class="math inline">\(\hat \pi_n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Curve-Height</td>
<td><span class="math inline">\(X \sim U(-1,1)\)</span></td>
<td><span class="math inline">\(\hat \pi_1 = \frac1n\sum_{i=1}^n 4\sqrt{1-X_i^2}\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Variance of the <strong>curve-height estimator</strong> is <span class="math display">\[
\begin{aligned}
\text{Var}(\hat\pi_1)
&amp;=
\frac1n \text{Var}(4\sqrt{1-X^2}) \\
&amp;=
\frac1n \left(\mathbb{E}[16(1-X^2)] - \mathbb{E}[4\sqrt{1-X^2}]^2\right).
\end{aligned}
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p><span class="math inline">\(\mathbb{E}[X^2] = \frac{1}{3}\)</span> and according to <a href="#/eq-area-expectation" class="quarto-xref">Equation&nbsp;4</a>, <span class="math inline">\(\mathbb{E}[4\sqrt{1-X^2}] = \pi\)</span>, so</p>
<p><span class="math display">\[
\begin{aligned}
\text{Var}(\hat\pi_1)
&amp;=
\frac1n \left(\mathbb{E}[16(1-X^2)] - \pi^2\right) \\
&amp;=
\frac1n \left[16(1-\mathbb{E}[X^2])-\pi^2\right] \\
&amp;=
\frac1n \left[16\left(1-\frac{1}{3}\right)-\pi^2\right] \\
&amp;=
\frac1n \left(\frac{32}{3}-\pi^2\right) \\
\therefore \text{Var}(\hat\pi_1)
&amp;\approx
\frac{0.797}{n}.
\end{aligned}
\]</span></p>
</div>
</section>
<section class="slide level2">

<h4 id="estimator-2-dartboard">Estimator 2: Dartboard</h4>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Random Variable</th>
<th>Monte Carlo Estimator <span class="math inline">\(\hat \pi_n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dartboard</td>
<td><span class="math inline">\((X,Y) \sim U([-1,1]^2)\)</span></td>
<td><span class="math inline">\(\hat \pi_2 = \frac4n\sum_{i=1}^n \mathbf{1}(X_i^2 + Y_i^2 \le 1)\)</span></td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Variance of the <strong>dartboard estimator</strong> is</p>
<p><span class="math display">\[
\begin{aligned}
\text{Var}(\hat\pi_2)
&amp;=
\frac{16}{n} \text{Var}(\mathbf{1}(X^2 + Y^2 \le 1)) \\
&amp;=
\frac{16}{n} \left(\mathbb{E}[\mathbf{1}(X^2 + Y^2 \le 1)] - \mathbb{E}[\mathbf{1}(X^2 + Y^2 \le 1)]^2\right).
\end{aligned}
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>According to <a href="#/eq-prob-area" class="quarto-xref">Equation&nbsp;5</a>, <span class="math inline">\(\mathbb{E}[\mathbf{1}(X^2 + Y^2 \le 1)] = P(x^2 + y^2 \le 1) = \pi/4\)</span>, so</p>
<p><span class="math display">\[
\begin{aligned}
\text{Var}(\hat\pi_2)
&amp;=
\frac{16}{n} \left(\frac{\pi}{4} - \left(\frac{\pi}{4}\right)^2\right) \\
&amp;=
\frac1n
(4\pi-\pi^2) \\
&amp;=
\frac1n
(4\pi-\pi^2) \\
\text{Var}(\hat\pi_2)
&amp;\approx
\frac{2.697}{n}.
\end{aligned}
\]</span></p>
</div>
</section>
<section class="slide level2">

<h4 id="comparison-of-estimators">Comparison of Estimators</h4>
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Random Variable</th>
<th>Monte Carlo Estimator <span class="math inline">\(\hat \pi_n\)</span></th>
<th>Variance <span class="math inline">\(\text{Var}(\hat \pi_n)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Curve-Height</td>
<td><span class="math inline">\(X \sim U(-1,1)\)</span></td>
<td><span class="math inline">\(\hat \pi_1 = \frac1n\sum_{i=1}^n 4\sqrt{1-X_i^2}\)</span></td>
<td><span class="math inline">\(\text{Var}(\hat \pi_1)\approx \dfrac{0.797}{n}\)</span></td>
</tr>
<tr class="even">
<td>Dartboard</td>
<td><span class="math inline">\((X,Y) \sim U([-1,1]^2)\)</span></td>
<td><span class="math inline">\(\hat \pi_2 = \frac4n\sum_{i=1}^n \mathbf{1}(X_i^2 + Y_i^2 \le 1)\)</span></td>
<td><span class="math inline">\(\text{Var}(\hat \pi_2)\approx \dfrac{2.697}{n}\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><span class="math inline">\(\therefore\)</span> Since <span class="math inline">\(\text{Var}(\hat\pi_1)&lt;\text{Var}(\hat\pi_2),\)</span> the curve-height estimator is more efficient.</p>
</div>
<div class="fragment">
<p>In fact, the dartboard estimator requires approximately</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\frac{\text{Var}(\hat \pi_2)}{\text{Var}(\hat \pi_1)} \approx \frac{2.697}{0.797} \approx 3.4
\]</span></p>
<p><span class="space-out"></span></p>
<p>times as many simulations to achieve the same variance.</p>
</div>
<p><span class="space-out"></span></p>
<div class="block green fragment center" style="font-size: 1.2em;">
<p><strong>Key takeaway:</strong> Monte Carlo estimators are random, and different estimators can produce very different levels of variability even when estimating the same quantity.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<blockquote>
<p><strong>Question:</strong> How does Monte Carlo estimation error behave?</p>
</blockquote>
</div>
<aside class="notes">
<p>This comparison highlights an important idea:</p>
<blockquote>
<p>Monte Carlo estimators are random, and different estimators can produce very different levels of variability.</p>
</blockquote>
<p>Even when two estimators target the same quantity, one may fluctuate much more than the other.</p>
<p>This naturally leads to the question:</p>
<blockquote>
<p>How does Monte Carlo estimation error behave?</p>
</blockquote>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="monte-carlo-error-and-convergence" class="slide level2">
<h2>Monte Carlo Error and Convergence</h2>
<p><span class="space-out"></span></p>
<p>Monte Carlo estimates are random because they depend on random samples. If we repeat the simulation, we obtain slightly different answers each time. The accuracy of the estimator is described by the <strong>Central Limit Theorem (CLT)</strong>.</p>
<p><span class="space-out"></span></p>
<div class="note fragment">
<h4 id="central-limit-theorem-for-monte-carlo-estimators">Central Limit Theorem for Monte Carlo Estimators</h4>
<p>If the Monte Carlo estimator is defined as</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\hat I_n
=
\frac1n\sum_{i=1}^n h(X_i),
\]</span></p>
<p><span class="space-out"></span></p>
<p>then CLT implies that for large <span class="math inline">\(n\)</span>,</p>
<p><span class="space-out"></span></p>
<p><span id="eq-mc-clt"><span class="math display">\[
\sqrt n(\hat I_n-I)
\to
N(0,\sigma^2),
\tag{6}\]</span></span></p>
<p><span class="space-out"></span></p>
<p>where the Monte Carlo error is <span class="math inline">\(\hat I_n - I\)</span> and the variance is <span class="math inline">\(\sigma^2 = \text{Var}(h(X))\)</span>.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Dividing <a href="#/eq-mc-clt" class="quarto-xref">Equation&nbsp;6</a> both sides by <span class="math inline">\(\sqrt n\)</span> gives</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\boxed{
\hat I_n - I
\approx
N\left(0, \frac{\sigma^2}{n}\right)
}
\]</span></p>
</div>
<div class="fragment center" style="font-size: 1.2em;">
<p>Does this look familiar?</p>
</div>
<aside class="notes">
<ul>
<li><p>The CLT tells us how the Monte Carlo estimation error behaves.</p></li>
<li><p>After multiplying the error by <span class="math inline">\(\sqrt n\)</span>, the distribution of the error converges to a normal distribution with mean zero and variance <span class="math inline">\(\sigma^2\)</span>.</p></li>
<li><p>This tells us that the Monte Carlo error has approximately a normal distribution with mean zero and standard deviation <span class="math inline">\(\sigma/\sqrt n\)</span>.</p></li>
<li><p>Does this look familiar? It should! This is the same formula for the standard error of the sample mean from Week 1, which is not a coincidence since the Monte Carlo estimator is a sample mean.</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h4 id="monte-carlo-error-and-convergence-cont.">Monte Carlo Error and Convergence (Cont.)</h4>
<p><span class="space-out"></span></p>
<p>The Monte Carlo error <span class="math inline">\(\hat I_n - I\)</span> is approximately normally distributed with mean zero and variance <span class="math inline">\(\sigma^2/n\)</span>:</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\boxed{
\hat I_n - I
\approx
N\left(0, \frac{\sigma^2}{n}\right)
}
\]</span></p>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Since the <em>typical size</em> of random fluctuations is measured by the standard deviation</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\boxed{\text{Magnitude of Monte Carlo error} \propto
\frac{1}{\sqrt{n}}
}
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>So,</p>
<ul>
<li class="fragment">100 simulations gives error roughly proportional to 1/10,</li>
<li class="fragment">10,000 simulations gives error roughly proportional to 1/100.</li>
</ul>
</div>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p>What do we notice about the rate of convergence?</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p>It requires 100 times as many simulations to reduce the error by a factor of 10.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p>That’s a very slow rate of convergence!</p>
</div>
<aside class="notes">
<p>This explains why Monte Carlo converges slowly, which is one of the main computational limitations of Monte Carlo methods.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2 scrollable">

<div class="example">
<p><strong>Example:</strong> Estimate <span class="math inline">\(\pi\)</span> using Monte Carlo integration with different numbers of simulated points, <span class="math inline">\(n = 100, 1000, 10000\)</span></p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb17-2"><a href=""></a>estimate_pi <span class="ot">&lt;-</span> <span class="cf">function</span>(n) {</span>
<span id="cb17-3"><a href=""></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>); y <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb17-4"><a href=""></a>  inside <span class="ot">&lt;-</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> y<span class="sc">^</span><span class="dv">2</span> <span class="sc">&lt;=</span> <span class="dv">1</span></span>
<span id="cb17-5"><a href=""></a>  pi_hat <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">*</span> <span class="fu">mean</span>(inside)</span>
<span id="cb17-6"><a href=""></a>  <span class="fu">return</span>(pi_hat)</span>
<span id="cb17-7"><a href=""></a>}</span>
<span id="cb17-8"><a href=""></a></span>
<span id="cb17-9"><a href=""></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb17-10"><a href=""></a>n_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">1000</span>, <span class="dv">10000</span>)</span>
<span id="cb17-11"><a href=""></a></span>
<span id="cb17-12"><a href=""></a><span class="co"># Repeat the Monte Carlo experiment for each n</span></span>
<span id="cb17-13"><a href=""></a>results <span class="ot">&lt;-</span> <span class="fu">lapply</span>(n_values, <span class="cf">function</span>(n) {</span>
<span id="cb17-14"><a href=""></a>  <span class="fu">replicate</span>(B, <span class="fu">estimate_pi</span>(n))</span>
<span id="cb17-15"><a href=""></a>})</span>
<span id="cb17-16"><a href=""></a><span class="fu">names</span>(results) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, n_values)</span>
<span id="cb17-17"><a href=""></a></span>
<span id="cb17-18"><a href=""></a><span class="co"># Summary statistics</span></span>
<span id="cb17-19"><a href=""></a><span class="fu">sapply</span>(results, <span class="cf">function</span>(x) {</span>
<span id="cb17-20"><a href=""></a>  <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(x), <span class="at">sd =</span> <span class="fu">sd</span>(x), <span class="at">bias =</span> <span class="fu">mean</span>(x) <span class="sc">-</span> pi)</span>
<span id="cb17-21"><a href=""></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          n = 100     n = 1000     n = 10000
mean  3.136320000  3.138332000  3.1409696000
sd    0.160557268  0.051433911  0.0166427178
bias -0.005272654 -0.003260654 -0.0006230536</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb19-2"><a href=""></a></span>
<span id="cb19-3"><a href=""></a><span class="kw">def</span> estimate_pi(n):</span>
<span id="cb19-4"><a href=""></a>    x <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, n)</span>
<span id="cb19-5"><a href=""></a>    y <span class="op">=</span> np.random.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, n)</span>
<span id="cb19-6"><a href=""></a>    inside <span class="op">=</span> x<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> y<span class="op">**</span><span class="dv">2</span> <span class="op">&lt;=</span> <span class="dv">1</span></span>
<span id="cb19-7"><a href=""></a>    pi_hat <span class="op">=</span> <span class="dv">4</span> <span class="op">*</span> np.mean(inside)</span>
<span id="cb19-8"><a href=""></a>    <span class="cf">return</span> pi_hat</span>
<span id="cb19-9"><a href=""></a></span>
<span id="cb19-10"><a href=""></a>B <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb19-11"><a href=""></a>n_values <span class="op">=</span> [<span class="dv">100</span>, <span class="dv">1000</span>, <span class="dv">10000</span>]</span>
<span id="cb19-12"><a href=""></a>results <span class="op">=</span> {<span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>: [estimate_pi(n) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(B)] <span class="cf">for</span> n <span class="kw">in</span> n_values}</span>
<span id="cb19-13"><a href=""></a></span>
<span id="cb19-14"><a href=""></a><span class="cf">for</span> n, estimates <span class="kw">in</span> results.items():</span>
<span id="cb19-15"><a href=""></a>    mean_estimate <span class="op">=</span> np.mean(estimates)</span>
<span id="cb19-16"><a href=""></a>    sd_estimate <span class="op">=</span> np.std(estimates)</span>
<span id="cb19-17"><a href=""></a>    bias_estimate <span class="op">=</span> mean_estimate <span class="op">-</span> np.pi</span>
<span id="cb19-18"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">: mean=</span><span class="sc">{</span>mean_estimate<span class="sc">:.4f}</span><span class="ss">, sd=</span><span class="sc">{</span>sd_estimate<span class="sc">:.4f}</span><span class="ss">, bias=</span><span class="sc">{</span>bias_estimate<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<aside class="notes">
<p>If the CLT is useful here, we should observe two things:</p>
<ol type="1">
<li>the estimates cluster around the true value of <span class="math inline">\(\pi\)</span>;</li>
<li>the spread of the estimates becomes smaller as <span class="math inline">\(n\)</span> increases.</li>
</ol>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb20-2"><a href=""></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(n_values)) {</span>
<span id="cb20-3"><a href=""></a>  <span class="fu">hist</span>(</span>
<span id="cb20-4"><a href=""></a>    results[[i]],</span>
<span id="cb20-5"><a href=""></a>    <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb20-6"><a href=""></a>    <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"n ="</span>, n_values[i]),</span>
<span id="cb20-7"><a href=""></a>    <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(pi)),</span>
<span id="cb20-8"><a href=""></a>    <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">2.8</span>, <span class="fl">3.5</span>)</span>
<span id="cb20-9"><a href=""></a>  )</span>
<span id="cb20-10"><a href=""></a>  </span>
<span id="cb20-11"><a href=""></a>  <span class="fu">abline</span>(<span class="at">v =</span> pi, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb20-12"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lecture09_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"><div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href=""></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb21-2"><a href=""></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>))</span>
<span id="cb21-3"><a href=""></a><span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>(n_values):</span>
<span id="cb21-4"><a href=""></a>    axes[i].hist(results[<span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>], bins<span class="op">=</span><span class="dv">30</span>, <span class="bu">range</span><span class="op">=</span>(<span class="fl">2.8</span>, <span class="fl">3.5</span>))</span>
<span id="cb21-5"><a href=""></a>    axes[i].axvline(np.pi, color<span class="op">=</span><span class="st">'red'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb21-6"><a href=""></a>    axes[i].set_title(<span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-7"><a href=""></a>    axes[i].set_xlabel(<span class="vs">r'</span><span class="dv">$</span><span class="er">\</span><span class="vs">hat{</span><span class="er">\</span><span class="vs">pi}</span><span class="dv">$</span><span class="vs">'</span>)</span>
<span id="cb21-8"><a href=""></a>plt.tight_layout()</span>
<span id="cb21-9"><a href=""></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<aside class="notes">
<p>As expected: For small <span class="math inline">\(n\)</span>, the estimates vary widely because each simulation uses relatively few random points. As <span class="math inline">\(n\)</span> increases, the estimates become more concentrated around the true value of <span class="math inline">\(\pi\)</span>. This shows the Monte Carlo estimator becoming more stable.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div style="font-size: 2em;">
<div class="callout callout-warning callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><strong>Question:</strong> How to Reduce Monte Carlo Error by Half?</strong></p>
</div>
<div class="callout-content">

</div>
</div>
</div>
</div>
</section>
<section id="pros-and-cons-of-monte-carlo-integration" class="slide level2">
<h2>Pros and Cons of Monte Carlo Integration</h2>
<p><span class="space-out"></span></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Pros</th>
<th>Cons</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Conceptually simple and easy to implement.</td>
<td>Slow convergence rate (<span class="math inline">\(1/\sqrt{n}\)</span>).</td>
</tr>
<tr class="even">
<td>Can handle high-dimensional integrals.</td>
<td>Variance can be large, leading to noisy estimates.</td>
</tr>
<tr class="odd">
<td>Flexible and can be applied to a wide range of problems.</td>
<td>Requires a large number of samples for accurate estimates.</td>
</tr>
<tr class="even">
<td>Can be used when analytical solutions are intractable.</td>
<td>Not suitable for all types of integrals (e.g., those with singularities or direct sampling is impossible).</td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p>In many realistic problems, direct sampling is impossible.</p>
</div>
<p><span class="space-out"></span></p>
<div class="center">
<ul>
<li class="fragment"><strong>Bayesian posterior distributions</strong> may have unknown normalising constants</li>
<li class="fragment"><strong>High-dimensional models</strong> may be analytically intractable</li>
<li class="fragment"><strong>Complicated joint distributions</strong> may not have standard sampling algorithms</li>
</ul>
</div>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p>What can we do if we cannot sample directly from the target distribution?</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment center" style="font-size: 1.2em;">
<p><strong>Markov chain Monte Carlo (MCMC)</strong></p>
</div>
<aside class="notes">
<p>Singular integrals are integrals whose integrand approaches infinity at one or more points within the domain, often requiring special techniques to determine convergence</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-2-markov-chain-monte-carlo-mcmc" class="title-slide slide level1 center">
<h1>Part 2: Markov Chain Monte Carlo (MCMC)</h1>

</section>
<section id="introduction-to-mcmc" class="slide level2">
<h2>Introduction to MCMC</h2>
<p>Markov Chain Monte Carlo (MCMC) is a powerful class of algorithms for sampling from <em>complex probability distributions</em>, especially when direct sampling is difficult or impossible. MCMC methods construct a <strong>Markov chain</strong> that has the desired distribution as its <em>equilibrium</em> distribution, allowing us to generate samples that can be used for estimation and inference.</p>
<p><span class="space-out"></span></p>
<div class="fragment" style="font-size: 1.4em;">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>What is a Markov Chain?</strong></p>
</div>
<div class="callout-content">
<p>Recall from Stochastic Modelling lectures:</p>
<p>A Markov chain (or Markov process) is a sequence of random variables</p>
<p><span class="math display">\[
(X_0, X_1, X_2, \dots)
\]</span></p>
<p>such that the distribution of the next state <span class="math inline">\(X_{n+1}\)</span> depends only on the current state <span class="math inline">\(X_n\)</span> and not on the previous states. That is,</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
P(X_{n+1} | X_n, X_{n-1}, \dots, X_0) = P(X_{n+1} | X_n).
\]</span></p>
<p><span class="space-out"></span></p>
<p>This property is called the <strong>Markov property</strong>.</p>
</div>
</div>
</div>
</div>
<ul>
<li class="fragment"><strong>Equilibrium (stationary) distribution:</strong><br>
A probability distribution <span class="math inline">\(\pi\)</span> is called a stationary distribution of a Markov chain if, whenever <span class="math inline">\(X_0 \sim \pi,\)</span> the distribution of <span class="math inline">\(X_n\)</span> remains <span class="math inline">\(\pi\)</span> for all <span class="math inline">\(n \ge 0\)</span>.</li>
</ul>
</section>
<section class="slide level2">

<h4 id="introduction-to-mcmc-cont.">Introduction to MCMC (Cont.)</h4>
<ul>
<li class="fragment"><p><strong>What is considered a “complex” distribution?</strong><br>
A distribution may be considered complex if it:</p>
<ul>
<li class="fragment">has a high-dimensional parameter space (e.g., multivariate or joint distributions);</li>
<li class="fragment">is defined only implicitly (e.g., posterior distributions in Bayesian inference);</li>
<li class="fragment">has an intractable normalising constant;</li>
<li class="fragment">or is difficult to sample from directly using standard simulation methods.</li>
</ul></li>
</ul>
<p><span class="space-out"></span></p>
<h4 class="fragment" id="mcmc-algorithms">MCMC Algorithms</h4>
<ul>
<li class="fragment"><strong>Metropolis-Hastings algorithm</strong>: a general MCMC algorithm that constructs a Markov chain using a proposal distribution and an acceptance criterion to ensure convergence to the target distribution.</li>
<li class="fragment"><strong>Gibbs sampling</strong> (a special case of Metropolis-Hastings): an MCMC algorithm that generates samples from a multivariate distribution by iteratively sampling from the conditional distributions of each variable given the others.</li>
<li class="fragment"><strong>Hamiltonian Monte Carlo (HMC)</strong>: an MCMC algorithm that uses Hamiltonian dynamics to propose new states, allowing for more efficient exploration of the target distribution.</li>
<li class="fragment"><strong>No-U-Turn Sampler (NUTS)</strong>: an extension of HMC that automatically tunes the path length to avoid unnecessary computations and improve sampling efficiency.</li>
</ul>
<div class="fragment">
<p>MCMC is still a developing field, and new algorithms are being proposed to address specific challenges in sampling from complex distributions.</p>
</div>
</section>
<section id="gibbs-sampling" class="slide level2">
<h2>Gibbs Sampling</h2>
<ul>
<li class="fragment"><p>In practice, direct sampling (as in Multivariate Simulation lecture) from the full joint distribution may be extremely difficult or even impossible.</p></li>
<li class="fragment"><p><strong>Gibbs sampling</strong> is a specific MCMC algorithm that generates samples from a <strong>multivariate distribution</strong> by iteratively sampling from the conditional distributions of each variable given the others.</p></li>
</ul>
<p><span class="space-out"></span></p>
<h3 class="fragment" id="bivariate-example">Bivariate Example</h3>
<div class="note fragment">
<p>Suppose we wish to sample from the joint distribution</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
p(x,y),
\]</span></p>
<p><span class="space-out"></span></p>
<p>which may be difficult to sample from directly.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>However, we know the conditional distributions</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
p(x|y)
\quad \text{and} \quad
p(y|x),
\]</span></p>
<p><span class="space-out"></span></p>
<p>which are easier to sample from.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment" style="font-size: 1.4em;">
<div class="callout callout-important callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gibbs sampling idea</strong></p>
</div>
<div class="callout-content">
<p>If we can sample from the conditional distributions, we can use these to construct a Markov chain that converges to the joint distribution.</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h4 id="bivariate-example-cont.">Bivariate Example (Cont.)</h4>
<div class="note">
<p>Suppose we want to sample from a joint distribution <span class="math inline">\(p(x,y).\)</span></p>
<p>Starting from the initial values <span class="math inline">\(x^{(0)}\)</span> and <span class="math inline">\(y^{(0)}\)</span>, the iterative updates are:</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
x^{(t+1)}
\sim
p(x|y^{(t)}),
\]</span></p>
<p><span class="math display">\[
y^{(t+1)}
\sim
p(y|x^{(t+1)}).
\]</span></p>
<p><span class="space-out"></span></p>
<ul>
<li class="fragment">These updates are repeated many times, and the sequence of samples forms a Markov chain.</li>
<li class="fragment">After sufficiently many iterations, the chain behaves as though it were sampling from the target joint distribution.</li>
</ul>
</div>

<img data-src="figs/bivariate-gibbs.png" class="quarto-figure quarto-figure-center r-stretch" style="width:60.0%"><div class="center">
<ol type="1">
<li class="fragment">sample a new value of <span class="math inline">\(x\)</span> conditional on the current value of <span class="math inline">\(y\)</span>;</li>
<li class="fragment">sample a new value of <span class="math inline">\(y\)</span> conditional on the updated value of <span class="math inline">\(x\)</span>.</li>
</ol>
</div>
<aside class="notes">
<p>Starting from an initial point <span class="math inline">\((x_0, y_0)\)</span>, the sampler first updates <span class="math inline">\(x\)</span> conditional on the current value of <span class="math inline">\(y\)</span>. Then <span class="math inline">\(y\)</span> is updated conditional on the newly updated <span class="math inline">\(x\)</span>. Repeating this alternating procedure generates a Markov chain that gradually explores the target joint distribution. Since only one coordinate is updated at a time, the Gibbs sampler typically moves through the state space in a <strong>zig-zag</strong> pattern.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 class="unnumbered" id="gibbs-sampling-algorithm">Gibbs Sampling Algorithm</h3>
<p>Suppose the target distribution is multivariate with <span class="math inline">\(d\)</span> variables:</p>
<p><span class="math display">\[
p(x_1,x_2,\dots,x_d).
\]</span></p>
<div class="tip fragment">
<p><strong>Step 1 — Choose initial values</strong></p>
</div>
<div class="fragment">
<p>Select starting values:</p>
<p><span class="math display">\[
x_1^{(0)},x_2^{(0)},\dots,x_d^{(0)}.
\]</span></p>
</div>
<div class="tip fragment">
<p><strong>Step 2 — Sequential conditional updates</strong></p>
</div>
<div class="fragment">
<p>For iteration <span class="math inline">\(t=0,1,2,\dots\)</span>,</p>
<p>Update each variable one at a time:</p>
<p><span class="math display">\[
x_1^{(t+1)}
\sim
p(x_1|x_2^{(t)},x_3^{(t)},\dots,x_d^{(t)}),
\]</span></p>
<p><span class="math display">\[
x_2^{(t+1)}
\sim
p(x_2|x_1^{(t+1)},x_3^{(t)},\dots,x_d^{(t)}),
\]</span></p>
<p>and so on until</p>
<p><span class="math display">\[
x_d^{(t+1)}
\sim
p(x_d|x_1^{(t+1)},\dots,x_{d-1}^{(t+1)}).
\]</span></p>
</div>
<div class="fragment">
<p>The Gibbs sampler updates <strong>one variable at a time</strong>, conditional on the current values of all the other <span class="math inline">\(d−1\)</span> variables.</p>
</div>
<div class="tip fragment">
<p><strong>Step 3 — Repeat</strong></p>
</div>
<div class="fragment">
<p>Repeat for many iterations.</p>
<p>The generated sequence approximates samples from the target distribution.</p>
</div>
</section>
<section class="slide level2">

<h3 class="unnumbered" id="example-1-bivariate-normal">Example 1: Bivariate Normal</h3>
<div class="example">
<p>Consider the bivariate normal distribution:</p>
<p><span class="math display">\[
\begin{pmatrix}
X \\ Y
\end{pmatrix}
\sim
N\left(
\begin{pmatrix}
0 \\ 0
\end{pmatrix},
\begin{pmatrix}
1 &amp; \rho \\
\rho &amp; 1
\end{pmatrix}
\right).
\]</span></p>
<p>Suppose <span class="math inline">\(\rho = 0.8\)</span>. Use Gibbs sampling to generate samples from this distribution.</p>
</div>
<div class="tip fragment">
<p><strong>Step 0 — Identify conditional distributions</strong></p>
</div>
<div class="fragment">
<p>Recall from Multivariate Distribution, the joint density can be written as</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
f(x,y)=
\frac{1}{2\pi\sqrt{1-\rho^2}}
\exp\left(
-\frac{1}{2(1-\rho^2)}
(x^2 - 2\rho xy + y^2)
\right).
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>To obtain the conditional distribution of <span class="math inline">\(X\mid Y= y\)</span>, we can treat <span class="math inline">\(y\)</span> as a constant and view the joint density as a function of <span class="math inline">\(x\)</span> alone. This gives</p>
</div>
<div class="fragment">
<p><span class="math display">\[
f(x|y)
\propto
\exp\left(
-\frac{1}{2(1-\rho^2)}
(x^2 - 2\rho xy)
\right).
\]</span></p>
</div>
<div class="fragment">
<p>Now complete the square in <span class="math inline">\(x\)</span>:</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p><span class="math display">\[
x^2 - 2\rho xy
=
(x-\rho y)^2 - \rho^2 y^2.
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Substituting this into the exponent gives</p>
<p><span class="math display">\[
f(x|y)
\propto
\exp\left(
-\frac{(x-\rho y)^2}{2(1-\rho^2)}
\right).
\]</span></p>
</div>
</section>
<section class="slide level2">

<p>Recall that the kernel of a normal distribution is given by</p>
<p><span class="math display">\[
f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)
\]</span></p>
<p>Then, <span class="math display">\[
\boxed{
f(x|y)
\propto
\exp\left(
-\frac{(x-\rho y)^2}{2(1-\rho^2)}
\right)}
\]</span></p>
<p>is the kernel of a normal distribution with mean <span class="math inline">\(\mathbb{E}[X|Y=y] = \rho y\)</span> and variance <span class="math inline">\(\text{Var}(X|Y=y) = 1-\rho^2\)</span>.</p>
<p>Thus,</p>
<p><span class="math display">\[
\boxed{X|Y=y \sim N(\rho y,1-\rho^2)}
\]</span></p>
<p>Similarly, <span class="math display">\[
\boxed{Y|X=x \sim N(\rho x,1-\rho^2)}
\]</span></p>
<div class="fragment" style="font-size: 1.4em;">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interpretation of Conditional Distributions</strong></p>
</div>
<div class="callout-content">
<p>The conditional distributions reveal several key properties of the bivariate normal distribution:</p>
<ul>
<li class="fragment"><span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are positively correlated (since <span class="math inline">\(\rho &gt; 0\)</span>);</li>
<li class="fragment">the mean of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y\)</span> is proportional to <span class="math inline">\(Y\)</span>, and vice versa;</li>
<li class="fragment">the variance of each conditional distribution is reduced compared to the marginal variance, reflecting the information gained from conditioning on the other variable.</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h4 id="gibbs-sampling-algorithm-for-this-example">Gibbs sampling algorithm for this example</h4>
<ol type="1">
<li class="fragment"><p>Choose initial values <span class="math inline">\(X^{(0)}\)</span> and <span class="math inline">\(Y^{(0)}\)</span>.</p></li>
<li class="fragment"><p>Sample <span class="math inline">\(X\)</span> given current <span class="math inline">\(Y\)</span> and sample <span class="math inline">\(Y\)</span> given updated <span class="math inline">\(X\)</span>:</p></li>
</ol>
<div class="fragment">
<p><span class="math display">\[
X^{(t+1)} \sim N(\rho Y^{(t)}, 1-\rho^2)
\]</span></p>
<p><span class="math display">\[
Y^{(t+1)} \sim N(\rho X^{(t+1)}, 1-\rho^2)
\]</span></p>
</div>
<ol start="3" type="1">
<li class="fragment">Repeat</li>
</ol>
<p><span class="space-out"></span></p>
<h4 class="fragment" id="analytical-example-of-gibbs-sampling-iterations">Analytical Example of Gibbs Sampling Iterations</h4>
<div class="fragment">
<p>From the setup, we have</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\rho = 0.8,
\qquad
1-\rho^2 = 1-0.8^2 = 0.36.
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Therefore, each conditional distribution has standard deviation</p>
<p><span class="space-out"></span></p>
<p><span class="math display">\[
\sqrt{1-\rho^2} = \sqrt{0.36} = 0.6.
\]</span></p>
</div>
<div class="tip fragment">
<p><strong>Step 1 — Choose initial values</strong></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Assume we start with the initial values</p>
<p><span class="math display">\[
X^{(0)} = 3,
\qquad
Y^{(0)} = -3.
\]</span></p>
</div>
<aside class="notes">
<p>The choice of initial values can affect the convergence of the Gibbs sampler. Starting from extreme values may lead to slower convergence, while starting from values closer to the mean can help the sampler converge more quickly to the target distribution.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div class="tip">
<p><strong>Step 2 &amp; 3 — Update variables and repeat</strong></p>
</div>
<ul>
<li class="fragment"><p><span style="color:blue;"><strong>At iteration <span class="math inline">\(t=0\)</span></strong></span>,</p>
<p>we first update <span class="math inline">\(X\)</span> using the current value <span class="math inline">\(Y^{(0)}=-3\)</span>:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
X^{(1)} \sim N(0.8Y^{(0)},0.36)
=
N(-2.4,0.36).
\]</span></p>
</div>
<div class="fragment">
<p>Randomly draw a value from this distribution:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> <span class="fl">0.8</span> <span class="sc">*</span> (<span class="sc">-</span><span class="dv">3</span>), <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="fl">0.36</span>))</span>
<span id="cb22-2"><a href=""></a>x1 <span class="ot">&lt;-</span> <span class="fu">round</span>(x1, <span class="dv">2</span>); x1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.4</code></pre>
</div>
</div>
<p><span class="math inline">\(\therefore X^{(1)} = -3.4.\)</span></p>
</div>
<div class="fragment">
<p>Now update <span class="math inline">\(Y\)</span> using the newly updated value <span class="math inline">\(X^{(1)}\)</span>:</p>
<p><span class="math display">\[
Y^{(1)} \sim N(0.8X^{(1)},0.36)
=
N(-2.72,0.36).
\]</span></p>
</div>
<div class="fragment">
<p>Randomly draw a value from this distribution:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a>y1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> <span class="fl">0.8</span> <span class="sc">*</span> x1, <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="fl">0.36</span>))</span>
<span id="cb24-2"><a href=""></a>y1 <span class="ot">&lt;-</span> <span class="fu">round</span>(y1, <span class="dv">2</span>); y1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.59</code></pre>
</div>
</div>
<p><span class="math inline">\(\therefore Y^{(1)} = -1.59.\)</span></p>
</div>
<div class="fragment">
<p>Thus, after the first iteration, we have</p>
<p><span class="math display">\[
\boxed{(X^{(1)},Y^{(1)}) = (-3.4,-1.59)}.
\]</span></p>
</div>
</section>
<section class="slide level2">

<p><strong>Exercise:</strong> <span style="color:blue;"><strong>At iteration <span class="math inline">\(t=1\)</span></strong></span>, determine <span class="math inline">\(X^{(2)}\)</span> and <span class="math inline">\(Y^{(2)}\)</span> using the same procedure as before, using the updated values from iteration <span class="math inline">\(t=0\)</span>:</p>
<p><span class="math display">\[
\boxed{(X^{(1)},Y^{(1)}) = (-3.4,-1.59)}.
\]</span></p>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb26-2"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb26-3"><a href=""></a>rho <span class="ot">&lt;-</span> <span class="fl">0.8</span></span>
<span id="cb26-4"><a href=""></a>sd_cond <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> rho<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb26-5"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb26-6"><a href=""></a>y <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb26-7"><a href=""></a>x[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb26-8"><a href=""></a>y[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb26-9"><a href=""></a></span>
<span id="cb26-10"><a href=""></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>n){</span>
<span id="cb26-11"><a href=""></a>  x[i] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> rho <span class="sc">*</span> y[i<span class="dv">-1</span>], <span class="at">sd =</span> sd_cond)</span>
<span id="cb26-12"><a href=""></a>  y[i] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> rho <span class="sc">*</span> x[i], <span class="at">sd =</span> sd_cond)</span>
<span id="cb26-13"><a href=""></a>}</span>
<span id="cb26-14"><a href=""></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb26-15"><a href=""></a><span class="fu">plot</span>(x, y, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.4</span>, <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.3</span>), <span class="at">xlab =</span> <span class="st">"X"</span>, <span class="at">ylab =</span> <span class="st">"Y"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lecture09_files/figure-revealjs/unnamed-chunk-17-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb27-2"><a href=""></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb27-3"><a href=""></a></span>
<span id="cb27-4"><a href=""></a>np.random.seed(<span class="dv">1234</span>)</span>
<span id="cb27-5"><a href=""></a>n <span class="op">=</span> <span class="dv">5000</span></span>
<span id="cb27-6"><a href=""></a>rho <span class="op">=</span> <span class="fl">0.8</span></span>
<span id="cb27-7"><a href=""></a>sd_cond <span class="op">=</span> np.sqrt(<span class="dv">1</span> <span class="op">-</span> rho<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb27-8"><a href=""></a>x <span class="op">=</span> np.zeros(n)</span>
<span id="cb27-9"><a href=""></a>y <span class="op">=</span> np.zeros(n)</span>
<span id="cb27-10"><a href=""></a>x[<span class="dv">0</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb27-11"><a href=""></a>y[<span class="dv">0</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb27-12"><a href=""></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, n):</span>
<span id="cb27-13"><a href=""></a>    x[i] <span class="op">=</span> np.random.normal(loc<span class="op">=</span>rho <span class="op">*</span> y[i<span class="op">-</span><span class="dv">1</span>], scale<span class="op">=</span>sd_cond)</span>
<span id="cb27-14"><a href=""></a>    y[i] <span class="op">=</span> np.random.normal(loc<span class="op">=</span>rho <span class="op">*</span> x[i], scale<span class="op">=</span>sd_cond)</span>
<span id="cb27-15"><a href=""></a></span>
<span id="cb27-16"><a href=""></a>plt.scatter(x, y, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb27-17"><a href=""></a>plt.xlabel(<span class="st">"X"</span>)</span>
<span id="cb27-18"><a href=""></a>plt.ylabel(<span class="st">"Y"</span>)</span>
<span id="cb27-19"><a href=""></a>plt.title(<span class="st">"Gibbs Samples from a Bivariate Normal"</span>)</span>
<span id="cb27-20"><a href=""></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<aside class="notes">
<p>The simulated points approximate the target bivariate normal distribution. Although the samples are generated one coordinate at a time, the collection of points eventually reproduces the elliptical shape and positive dependence of the target bivariate normal distribution.</p>
<p>In the Multivariate Simulation chapter, we generated dependent random variables using techniques such as:</p>
<ul>
<li>linear transformations and <strong>Cholesky decomposition</strong> for multivariate normal simulation;</li>
<li><strong>copulas</strong> for modelling more general dependence structures.</li>
</ul>
<p>Those approaches are examples of <em>direct</em> simulation methods: we can generate samples from the joint distribution directly using <em>known transformations</em>.</p>
<p>Gibbs sampling is different. Instead of sampling directly from the joint distribution, <strong>Gibbs sampling generates samples indirectly through a sequence of conditional distributions.</strong> This becomes particularly useful when:</p>
<ul>
<li>the joint distribution is difficult to sample from directly;</li>
<li>no convenient transformation is available;</li>
<li>the distribution is only known up to a proportionality constant (common in Bayesian statistics).</li>
</ul>
<p>Thus, Gibbs sampling extends simulation methods to settings where direct multivariate simulation is no longer feasible.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h4 class="unnumbered" id="example-2-multivariate-normal">Example 2: Multivariate Normal</h4>
<div class="example">
<p>Let</p>
<p><span class="math display">\[
(X_1, X_2, X_3)^T
\sim
N\left(\mathbf{0}, \Sigma\right),
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\Sigma = \begin{pmatrix}
1 &amp; 0.8 &amp; 0.5 \\
0.8 &amp; 1 &amp; 0.3 \\
0.5 &amp; 0.3 &amp; 1
\end{pmatrix}.
\]</span></p>
<p>Use Gibbs sampling to generate samples from this distribution.</p>
</div>
<p><span class="space-out"></span></p>
<div class="tip fragment">
<p><strong>Step 0 — Identify conditional distributions</strong></p>
</div>
<div class="fragment">
<p>For a multivariate normal distribution, the conditional distribution of one component given the others is also normal.</p>
<p>Partition the random vector as <span class="math inline">\(X_j\)</span> and <span class="math inline">\(X_{-j}\)</span>. Then</p>
<p><span class="math display">\[
X_j \mid X_{-j}=x_{-j}
\sim
N(\mu_{j|-j},\sigma^2_{j|-j}),
\]</span></p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>where</p>
<p><span class="math display">\[
\mu_{j|-j}
=
\mu_j
+
\Sigma_{j,-j}
\Sigma_{-j,-j}^{-1}
(x_{-j}-\mu_{-j}),
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\sigma^2_{j|-j}
=
\Sigma_{jj}
-
\Sigma_{j,-j}
\Sigma_{-j,-j}^{-1}
\Sigma_{-j,j}.
\]</span></p>
<p>In this example, <span class="math inline">\(\mu=\mathbf 0\)</span>, so the conditional means simplify to linear combinations of the remaining variables.</p>
</div>
</section>
<section class="slide level2">

<h4 id="visualisation-of-gibbs-sampling-in-higher-dimensions-3-variables">Visualisation of Gibbs Sampling in Higher Dimensions (3 variables)</h4>

<img data-src="figs/3d-gibbs.png" class="quarto-figure quarto-figure-center r-stretch" style="width:40.0%"><ul>
<li class="fragment">The Gibbs sampler updates one variable at a time, conditional on the current values of the other two variables. This results in a <strong>stair-case</strong> pattern.</li>
<li class="fragment"><span style="color:blue;"><strong>Blue arrows:</strong> conditional dependencies used when updating <span class="math inline">\(x_1\)</span></span></li>
<li class="fragment"><span style="color:green;"><strong>Green arrows:</strong> conditional dependencies used when updating <span class="math inline">\(x_2\)</span></span></li>
<li class="fragment"><span style="color:red;"><strong>Red arrows:</strong> conditional dependencies used when updating <span class="math inline">\(x_3\)</span></span></li>
</ul>
</section>
<section class="slide level2">

<div class="tip">
<p><strong>Step 1 — Choose initial values</strong></p>
</div>
<p>Choose a starting point, for example</p>
<p><span class="math display">\[
(X_1^{(0)},X_2^{(0)},X_3^{(0)})=(3,-3,2).
\]</span></p>
<div class="tip fragment">
<p><strong>Step 2 — Update one coordinate at a time</strong></p>
</div>
<div class="fragment">
<p>At iteration <span class="math inline">\(t\)</span>, update:</p>
<p><span class="math display">\[
X_1^{(t+1)}
\sim
p(X_1\mid X_2^{(t)},X_3^{(t)}),
\]</span></p>
<p><span class="math display">\[
X_2^{(t+1)}
\sim
p(X_2\mid X_1^{(t+1)},X_3^{(t)}),
\]</span></p>
<p><span class="math display">\[
X_3^{(t+1)}
\sim
p(X_3\mid X_1^{(t+1)},X_2^{(t+1)}).
\]</span></p>
<p>Notice that each update uses the most recently available values.</p>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="co"># Problem setup</span></span>
<span id="cb28-2"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb28-3"><a href=""></a></span>
<span id="cb28-4"><a href=""></a><span class="co"># Target covariance matrix</span></span>
<span id="cb28-5"><a href=""></a>Sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(</span>
<span id="cb28-6"><a href=""></a>  <span class="dv">1</span>,   <span class="fl">0.8</span>, <span class="fl">0.5</span>,</span>
<span id="cb28-7"><a href=""></a>  <span class="fl">0.8</span>, <span class="dv">1</span>,   <span class="fl">0.3</span>,</span>
<span id="cb28-8"><a href=""></a>  <span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="dv">1</span></span>
<span id="cb28-9"><a href=""></a>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-10"><a href=""></a></span>
<span id="cb28-11"><a href=""></a>mu <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="co"># Function for conditional normal parameters</span></span>
<span id="cb29-2"><a href=""></a>cond_params <span class="ot">&lt;-</span> <span class="cf">function</span>(j, x, mu, Sigma) {</span>
<span id="cb29-3"><a href=""></a>  other <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, j) <span class="co"># indices of other variables, excluding j</span></span>
<span id="cb29-4"><a href=""></a>  </span>
<span id="cb29-5"><a href=""></a>  <span class="co"># Extract relevant submatrices and vectors</span></span>
<span id="cb29-6"><a href=""></a>  Sigma_j_other <span class="ot">&lt;-</span> Sigma[j, other]</span>
<span id="cb29-7"><a href=""></a>  Sigma_other_other <span class="ot">&lt;-</span> Sigma[other, other]</span>
<span id="cb29-8"><a href=""></a>  Sigma_other_j <span class="ot">&lt;-</span> Sigma[other, j]</span>
<span id="cb29-9"><a href=""></a>  mu_j <span class="ot">&lt;-</span> mu[j]</span>
<span id="cb29-10"><a href=""></a>  mu_other <span class="ot">&lt;-</span> mu[other]</span>
<span id="cb29-11"><a href=""></a>  </span>
<span id="cb29-12"><a href=""></a>  <span class="co"># Conditional mean and variance</span></span>
<span id="cb29-13"><a href=""></a>  cond_mean <span class="ot">&lt;-</span> mu_j <span class="sc">+</span></span>
<span id="cb29-14"><a href=""></a>    Sigma_j_other <span class="sc">%*%</span> <span class="fu">solve</span>(Sigma_other_other) <span class="sc">%*%</span></span>
<span id="cb29-15"><a href=""></a>    (x[other] <span class="sc">-</span> mu_other)</span>
<span id="cb29-16"><a href=""></a>  cond_var <span class="ot">&lt;-</span> Sigma[j, j] <span class="sc">-</span></span>
<span id="cb29-17"><a href=""></a>    Sigma_j_other <span class="sc">%*%</span> <span class="fu">solve</span>(Sigma_other_other) <span class="sc">%*%</span></span>
<span id="cb29-18"><a href=""></a>    Sigma_other_j</span>
<span id="cb29-19"><a href=""></a>  </span>
<span id="cb29-20"><a href=""></a>  <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">as.numeric</span>(cond_mean), <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="fu">as.numeric</span>(cond_var)))</span>
<span id="cb29-21"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">5000</span> <span class="co"># number of iterations</span></span>
<span id="cb30-2"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> n, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb30-3"><a href=""></a><span class="fu">colnames</span>(x) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"X1"</span>, <span class="st">"X2"</span>, <span class="st">"X3"</span>)</span>
<span id="cb30-4"><a href=""></a>x[<span class="dv">1</span>, ] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="sc">-</span><span class="dv">3</span>, <span class="dv">2</span>)</span>
<span id="cb30-5"><a href=""></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>n) {</span>
<span id="cb30-6"><a href=""></a>  current <span class="ot">&lt;-</span> x[i <span class="sc">-</span> <span class="dv">1</span>, ]</span>
<span id="cb30-7"><a href=""></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(x)[<span class="dv">2</span>]) {</span>
<span id="cb30-8"><a href=""></a>    cp <span class="ot">&lt;-</span> <span class="fu">cond_params</span>(j, current, mu, Sigma)</span>
<span id="cb30-9"><a href=""></a>    current[j] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> cp<span class="sc">$</span>mean, <span class="at">sd =</span> cp<span class="sc">$</span>sd)</span>
<span id="cb30-10"><a href=""></a>  }</span>
<span id="cb30-11"><a href=""></a>  x[i, ] <span class="ot">&lt;-</span> current</span>
<span id="cb30-12"><a href=""></a>}</span>
<span id="cb30-13"><a href=""></a><span class="fu">pairs</span>(x, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lecture09_files/figure-revealjs/unnamed-chunk-21-1.png" width="960" class="r-stretch"><aside class="notes">
<p>The pairwise plots show elliptical point clouds. The strongest relationship appear between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, since their covariance is 0.8. The relationship between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_3\)</span> is also positive but weaker, while the relationship between <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span> is the weakest of the three.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 class="unnumbered" id="trace-plots">Trace Plots</h3>
<p>A trace plot displays the sampled values over iteration number. Trace plots help assess convergence, mixing behaviour, and stability of the chain.</p>
<p>Good trace plots fluctuate around a stable region, show no obvious trend, and explore the distribution well.</p>
<div class="fragment">
<p>From Example 2, we can plot the trace of each variable across iterations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb31-2"><a href=""></a><span class="fu">plot</span>(x[, <span class="dv">1</span>], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">ylab =</span> <span class="st">"X1"</span>)</span>
<span id="cb31-3"><a href=""></a><span class="fu">plot</span>(x[, <span class="dv">2</span>], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">ylab =</span> <span class="st">"X2"</span>)</span>
<span id="cb31-4"><a href=""></a><span class="fu">plot</span>(x[, <span class="dv">3</span>], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">ylab =</span> <span class="st">"X3"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture09_files/figure-revealjs/unnamed-chunk-22-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href=""></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb32-2"><a href=""></a>axes[<span class="dv">0</span>].plot(x[:, <span class="dv">0</span>], color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb32-3"><a href=""></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"X1"</span>)</span>
<span id="cb32-4"><a href=""></a>axes[<span class="dv">1</span>].plot(x[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb32-5"><a href=""></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"X2"</span>)</span>
<span id="cb32-6"><a href=""></a>axes[<span class="dv">2</span>].plot(x[:, <span class="dv">2</span>], color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb32-7"><a href=""></a>axes[<span class="dv">2</span>].set_xlabel(<span class="st">"Iteration"</span>)</span>
<span id="cb32-8"><a href=""></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"X3"</span>)</span>
<span id="cb32-9"><a href=""></a>plt.suptitle(<span class="st">"Trace Plots for Gibbs Samples"</span>)</span>
<span id="cb32-10"><a href=""></a>plt.show() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<aside class="notes">
<p>The trace plots show that the samples fluctuate around stable regions, with no obvious trends. However, the samples appear to be highly autocorrelated, especially for <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>. This is a common feature of Gibbs sampling, since each update depends on the previous state of the chain.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 class="unnumbered" id="burn-in-period">Burn-in Period</h3>
<ul>
<li class="fragment">The early part of the chain may depend heavily on the starting values.</li>
<li class="fragment">This initial transient behaviour is called the burn-in period.</li>
<li class="fragment">Typically, early samples are discarded, and only later samples are used for inference.</li>
<li class="fragment">The idea is that the chain needs time to approach the target distribution.</li>
</ul>
<div class="fragment" style="font-size: 1.4em;">
<div class="callout callout-caution callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>Burn-in selection is partly subjective, and more formal convergence diagnostics are often used in advanced applications.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>From Example 2, we can discard the first 1000 iterations as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a>burnin <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb33-2"><a href=""></a>x_post <span class="ot">&lt;-</span> x[(burnin <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>n, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Python Version</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href=""></a>burnin <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb34-2"><a href=""></a>x_post <span class="op">=</span> x[burnin:, :]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<aside class="notes">
<p>If we plot it, the post-burn-in samples still show the same elliptical relationships as before, but the initial transient behaviour has been removed. It might not look clearly different in this case, but in other examples, the burn-in period can have a significant impact on the quality of the samples and the resulting inference.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 class="unnumbered" id="autocorrelation-in-mcmc">Autocorrelation in MCMC</h3>
<p>Gibbs samples are dependent. Successive samples are often highly correlated. This dependence is measured by <strong>autocorrelation</strong>. Strong autocorrelation means the chain moves slowly and fewer effectively independent samples are obtained.</p>
<div class="fragment">
<p>This is one reason MCMC methods may require many iterations.</p>
</div>
<div class="fragment">
<p>From Example 2, we can plot the autocorrelation function (ACF) for each variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb35-2"><a href=""></a><span class="fu">acf</span>(x_post[, <span class="dv">1</span>], <span class="at">ylab =</span> <span class="st">"ACF: X1"</span>); <span class="fu">acf</span>(x_post[, <span class="dv">2</span>], <span class="at">ylab =</span> <span class="st">"ACF: X2"</span>)</span>
<span id="cb35-3"><a href=""></a><span class="fu">acf</span>(x_post[, <span class="dv">3</span>], <span class="at">ylab =</span> <span class="st">"ACF: X3"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture09_files/figure-revealjs/unnamed-chunk-26-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>The ACF plots show strong autocorrelation for all three variables, especially at low lags. This indicates that the samples are highly dependent, which is a common feature of Gibbs sampling.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 id="strengths-and-limitations">Strengths and Limitations</h3>
<table class="caption-top">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Strengths</th>
<th>Limitations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Can sample from complex, high-dimensional distributions.</td>
<td>Slow convergence and strong autocorrelation.</td>
</tr>
<tr class="even">
<td>Flexible and widely applicable.</td>
<td>Requires careful tuning (e.g., burn-in, number of iterations).</td>
</tr>
<tr class="odd">
<td>Can be used when direct sampling is impossible.</td>
<td>May not perform well for multimodal distributions.</td>
</tr>
<tr class="even">
<td>Provides a way to approximate intractable integrals.</td>
<td>Diagnostics for convergence can be subjective and challenging.</td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<h3 class="fragment" id="workshop-today">Workshop Today</h3>
<ul>
<li class="fragment">Bayesian Gibbs Sampling</li>
<li class="fragment">Case Study - <a href="https://zamnolence.github.io/_book/10_6_energysavings.html">💡 Estimating Household Energy Savings</a></li>
<li class="fragment">Guest Lecture by Dr Tony Mathew</li>
</ul>

</section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="figs/curtin-logo2.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="lecture09_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="lecture09_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="lecture09_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="lecture09_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"titleSelector":"h1, h2, h3","hideMissingTitles":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>