project:
  type: book
  # resources:
  #   - 01lecture.html

book:
  title: "Supply Chain Modelling and Optimisation"
  author: "Ben W. and Sam W."
  date: "6/4/2026"
  cover-image: cover.png
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - part: "<strong>0 Workshop Setup Guide</strong>"
      chapters:
        - 00_python_setup.qmd
        - 00_quarto_git.qmd
    - part: "<strong>1 Introduction</strong>"
      chapters: 
        - 01tutorial.qmd
        - 01solutions.qmd
    - part: "<strong>2 Network Design: SESC</strong>"
      chapters:
        - 02tutorial.qmd
        - 02solutions.qmd
    - part: "<strong>3 Network Design: TEMC</strong>"
      chapters:
        - 03tutorial.qmd
        - 03solutions.qmd
    - part: "<strong>4 Network Design under Uncertainty</strong>"
      chapters:
        - 04tutorial.qmd
        # - 04solutions.qmd
    - part: "<strong>5 Demand Forecasting</strong>"
      chapters:
        - 05tutorial.qmd
        # - 05solutions.qmd
    - part: "<strong>6 Inventory Model: Single-Commodity</strong>"
      # chapters:
        # - 06tutorial.qmd
        # - 06solutions.qmd
    - part: "<strong>7 Inventory Model: Discount and Multi-Commodity</strong>"
      # chapters:
        # - 07tutorial.qmd
        # - 07solutions.qmd
    - part: "<strong>8 Stochastic Inventory Model</strong>"
      # chapters:
        # - 08tutorial.qmd
        # - 08solutions.qmd
    # - references.qmd

  page-footer:
    background: light
    left: |
      Supply Chain Modelling and Optimisation<br>
      &copy; Copyright 2026, Ben W. and Sam W.
    right: |
      This book was built with ❤️ and [Quarto]( https://quarto.org)


  sidebar:
    style: "floating" # "docked" for left-aligned and distinct sidebar
    search: true
    logo: logo_.png
    collapse-level: 1 # 1 to callapse chapters

bibliography: references.bib
bibliographystyle: apa

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    theme:
      light:
        - flatly
        - brand
        - book.scss
      dark:
        - darkly
        - brand
        - book-dark.scss
    code-overflow: wrap
    toc-expand: true
    toc-depth: 4
  pdf:
    documentclass: scrreprt

prefer-html: true
execute:
  freeze: true



