{
  "hash": "232c76f539f38ce78a0560d03b199e31",
  "result": {
    "engine": "jupyter",
    "markdown": "# Tutorial 2 Exercises {#02tut .unnumbered}\n\nThis tutorial trains you to quantify the elements of an optimisation model:\n\n- **Decision variables:** quantities of resources used (e.g., money allocated) or levels of activities (e.g., units produced, gallons blended).\n- **Objective:** a function of decision variables to be maximised/minimised.\n- **Constraints:** relationships/limits the decision variables must satisfy.\n\n### Question 1\n\nWith precisely 2700 sq. cm. of cardboard, you wish to construct a box (width: $x$, depth: $y$, height: $z$) containing a volume $V$. You require the width to double its depth. You would like to maximise the volume of the box. Which values of $x, y, z$ will maximise the volume?\n\n::: {.example}\n1. **Construct the objective function and constraints**: \n\n$$\n\\begin{aligned}\n\\max\\; &f(x,y,z) = xyz \\\\\n\\text{st:} \\quad\n&x = 2y \\\\\n&2(xy + xz + yz) = 2700 \\\\\n&x, y, z \\ge 0\n\\end{aligned}\n$$\n\n&emsp;&emsp;Convert the maximisation problem to a minimisation problem in the standard form:\n\n$$\n\\begin{aligned}\n\\min\\; &f(x,y,z) = -xyz \\\\\n\\text{st:} \\quad\n&x - 2y = 0 \\\\\n&2(xy + xz + yz) - 2700 = 0 \\\\\n&-x, -y, -z \\le 0\n\\end{aligned}\n$$\n\n\n2. **Set up a Lagrangian function**\n\n$$\n\\begin{aligned}\nL(x,y,z,\\lambda_1,\\lambda_2,\\mu_1, \\mu_2, \\mu_3)\n = xyz &+ \\lambda_1(2(xy + xz + yz) - 2700) \\\\\n       &+ \\lambda_2(x-2y) \\\\\n       &+ \\mu_1 x + \\mu_2 y +\\mu_3 z\n\\end{aligned}\n$$\n\nSince the optimum has $x,y,z>0,$ the non-negativity constraints are not binding, so $\\mu_1=\\mu_2=\\mu_3=0$. Therefore,\n\n$$\n\\begin{aligned}\nL(x,y,z,\\lambda_1,\\lambda_2,\\mu_1, \\mu_2, \\mu_3)\n = xyz &+ \\lambda_1(2(xy + xz + yz) - 2700) \\\\\n       &+ \\lambda_2(x-2y)\n\\end{aligned}\n$$\n\nFrom this, KKT's dual feasibility and complementary slackness conditions are satisfied, so we can proceed to the stationarity and primal feasibility conditions.\n\n2. **KKT's stationarity**\n\nSolve for partial derivatives and set them equal to 0:\n\n$$\n\\begin{aligned}\nL_x &= yz - 2\\lambda_1(y+z) - \\lambda_2 + \\mu_1 = 0 \\\\\nL_y &= xz - 2\\lambda_1(x+z) + 2\\lambda_2 + \\mu_2 = 0 \\\\\nL_z &= xy - 2\\lambda_1(x+y) + \\mu_3 = 0 \\\\\nL_{\\lambda_1} &= 2(xy + xz + yz) - 2700 = 0 \\\\\nL_{\\lambda_2} &= x - 2y = 0 \\\\\n\\end{aligned}\n$$\n\nFrom $L_{\\lambda_2}$,\n\n$$\nx = 2y\n$$\n\nFrom $L_{\\lambda_1}$, substitute $x=2y$:\n\n$$\n2(2y^2+2yz+yz)=2700\n$$\n\n$$\n4y^2+6yz=2700\n$$\n\nSolve for $z$:\n\n$$\nz=\\frac{2700-4y^2}{6y}= \\frac{450}{y}-\\frac{2y}{3}\n$$\n\nVolume:\n\n$$\nV=xyz=(2y)(y)(z)=2y^2z\n$$\n\nSubstitute $z$:\n\n$$\nV(y)=2y^2\\left(\\frac{450}{y}-\\frac{2y}{3}\\right)\n=900y-\\frac{4}{3}y^3\n$$\n\nDifferentiate and set it equal to 0:\n\n$$\n\\begin{aligned}\nV'(y)=900-4y^2&=0 \\\\\ny^2&=225 \\\\\ny&=15\n\\end{aligned}\n$$\n\nThen:\n\n$$\nx=2y=30\n$$\n\n$$\nz=\\frac{450}{15}-\\frac{2(15)}{3}=30-10=20\n$$\n\nSo the optimal dimensions are:\n\n$$\n\\boxed{x=30,\\quad y=15,\\quad z=20}\n$$\n\n3. **Verify KKT's primal feasibility**\n\nSubstitute the optimal dimensions into the constraints $L_{\\lambda_1}$ and $L_{\\lambda_2}$:\n\n$$\nL_{\\lambda_1} = 2(2(15)^2+2(15)(20)+(15)(20)) - 2700 = 0 \\quad \\text{(Satisfied)}\n$$\n\n$$\nL_{\\lambda_2} = 30 - 2(15) = 0 \\quad \\text{(Satisfied)}\n$$\n\n4. **Calculate the maximum volume**\n\n$$\nV=30(15)(20)=\\boxed{9000\\text{ cm}^3}\n$$\n\n:::\n\n::: {#0532535f .cell execution_count=1}\n``` {.python .cell-code}\nimport sympy as sp\n\n# Variables\nx, y, z = sp.symbols(\"x y z\", positive=True)\nlambda1, lambda2 = sp.symbols(\"lambda1 lambda2\")\n\n# Objective and constraints\nV = x * y * z\ng1 = 2 * (x*y + x*z + y*z) - 2700\ng2 = x - 2*y\n\n# Lagrangian\nL = V - lambda1 * g1 - lambda2 * g2\n\n# First-order conditions\nequations = [\n    sp.diff(L, x),\n    sp.diff(L, y),\n    sp.diff(L, z),\n    g1,\n    g2,\n]\n\nsolution = sp.solve(\n    equations,\n    [x, y, z, lambda1, lambda2],\n    dict=True\n)\n\nprint(\"Solutions:\")\nfor sol in solution:\n    print(sol)\n\n# Keep positive real solution\npositive_solutions = [\n    sol for sol in solution\n    if sol[x].is_real and sol[y].is_real and sol[z].is_real\n    and sol[x] > 0 and sol[y] > 0 and sol[z] > 0\n]\n\nbest = max(positive_solutions, key=lambda sol: V.subs(sol))\n\nprint(\"\\nOptimal dimensions:\")\nprint(f\"x = {sp.simplify(best[x])} = {float(best[x]):.4f} cm\")\nprint(f\"y = {sp.simplify(best[y])} = {float(best[y]):.4f} cm\")\nprint(f\"z = {sp.simplify(best[z])} = {float(best[z]):.4f} cm\")\n\nprint(\"\\nMaximum volume:\")\nprint(f\"V = {sp.simplify(V.subs(best))} = {float(V.subs(best)):.4f} cubic cm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSolutions:\n{lambda1: 5, lambda2: -50, x: 30, y: 15, z: 20}\n\nOptimal dimensions:\nx = 30 = 30.0000 cm\ny = 15 = 15.0000 cm\nz = 20 = 20.0000 cm\n\nMaximum volume:\nV = 9000 = 9000.0000 cubic cm\n```\n:::\n:::\n\n\n---\n\n### Question 2\n\nA manufacturing facility produces four types of wood panelling: Tahoe, Pacific, Savannah, and Aspen. Each product is manufactured using pine chips and oak chips and requires both gluing and pressing processes.\n\nThe profit earned per pallet is as follows:\n\n- \\$450 for Tahoe,\n- \\$1140 for Pacific,\n- \\$800 for Savannah, and\n- \\$400 for Aspen.\n\nThe factory operates under limited resource availability. During the planning period, there are 5,800 quarts of glue available, 730 pressing machine hours, and 29,200 pounds of pine chips. In addition, the supply of oak chips is limited to a fixed total amount.\n\n|| Tahoe | Pacific | Savannah | Aspen | Capacity |\n|---|---|---|---|---|---|\n| Glueing (quarts) | 50 | 50 | 100 | 50 | 5800 quarts |\n| Pressing (hours) | 5 | 15 | 10 | 5 | 730 hours |\n| Pine chips (pounds) | 500 | 400 | 300 | 200 | 29200 pounds |\n| Oak chips (pounds) | 500 | 750 | 250 | 500 | 60500 pounds |\n| Profit per pallet (\\$) | 450 | 1150 | 800 | 400 | - |\n\nLet decision variables be $X_1,X_2,X_3,X_4$ (pallets of Tahoe, Pacific, Savannah, Aspen). Write down the optimisation model to maximise profit, and solve for the optimal production plan. What is the maximum profit?\n\nObjective function:\n\n$$\n\\max\\; 450x_1 + 1150x_2 + 800x_3 + 400x_4\n$$\n\nConstraints:\n\n$$\n\\begin{aligned}\n50x_1 + 50x_2 + 100x_3 + 50x_4 &\\le 5800 \\quad \\text{(Glueing)} \\\\\n5x_1 + 15x_2 + 10x_3 + 5x_4 &\\le 730 \\quad \\text{(Pressing)} \\\\\n500x_1 + 400x_2 + 300x_3 + 200x_4 &\\le 29200 \\quad \\text{(Pine chips)} \\\\\n500x_1 + 750x_2 + 250x_3 + 500x_4 &\\le 60500 \\quad \\text{(Oak chips)} \\\\\nx_1, x_2, x_3, x_4 &\\ge 0\n\\end{aligned}\n$$\n\nThis can be solved using KKT. However, it is usually not the preferred manual method for solving linear programming problems. Instead, we can use the **Simplex method** or an LP solver.\n\n::: {.example}\n\nThe objective function is:\n$$\n\\max Z=450x_1+1150x_2+800x_3+400x_4\n$$\n\nsubject to the four resource constraints and $x_i\\ge 0$.\n\nThe optimal solution is:\n\n$$\n\\boxed{x_1=23,\\quad x_2=15,\\quad x_3=39,\\quad x_4=0}\n$$\n\nThat is:\n\nMaximum profit:\n\n$$\nZ=450(23)+1150(15)+800(39)+400(0)\n$$\n\n$$\n\\boxed{Z=58800}\n$$\n\nThe binding constraints are:\n\n$$\n\\begin{aligned}\n50x_1+50x_2+100x_3+50x_4&=5800 \\\\\n5x_1+15x_2+10x_3+5x_4&=730 \\\\\n500x_1+400x_2+300x_3+200x_4&=29200\n\\end{aligned}\n$$\n\nThe oak constraint is not binding:\n\n$$\n500(23)+750(15)+250(39)+500(0)=32500<60500\n$$\n:::\n\n::: {#2e1b45f8 .cell execution_count=2}\n``` {.python .cell-code}\nimport pulp\n\n# Define the LP problem\nproblem = pulp.LpProblem(\"Wood_Panelling_Production\", pulp.LpMaximize)\n\n# Decision variables\nx1 = pulp.LpVariable(\"Tahoe\", lowBound=0)\nx2 = pulp.LpVariable(\"Pacific\", lowBound=0)\nx3 = pulp.LpVariable(\"Savannah\", lowBound=0)\nx4 = pulp.LpVariable(\"Aspen\", lowBound=0)\n\n# Objective function\nproblem += 450*x1 + 1150*x2 + 800*x3 + 400*x4\n\n# Constraints\nproblem += 50*x1 + 50*x2 + 100*x3 + 50*x4 <= 5800, \"Glueing\"\nproblem += 5*x1 + 15*x2 + 10*x3 + 5*x4 <= 730, \"Pressing\"\nproblem += 500*x1 + 400*x2 + 300*x3 + 200*x4 <= 29200, \"Pine_Chips\"\nproblem += 500*x1 + 750*x2 + 250*x3 + 500*x4 <= 60500, \"Oak_Chips\"\n\n# Solve\nproblem.solve()\n\n# Print results\nprint(f\"Status: {pulp.LpStatus[problem.status]}\")\n\nprint(f\"Tahoe pallets: {x1.varValue}\")\nprint(f\"Pacific pallets: {x2.varValue}\")\nprint(f\"Savannah pallets: {x3.varValue}\")\nprint(f\"Aspen pallets: {x4.varValue}\")\n\nprint(f\"Maximum Profit: ${pulp.value(problem.objective):,.2f}\")\n\n# Resource usage\nprint(\"\\nResource usage:\")\nprint(f\"Glueing: {50*x1.varValue + 50*x2.varValue + 100*x3.varValue + 50*x4.varValue}\")\nprint(f\"Pressing: {5*x1.varValue + 15*x2.varValue + 10*x3.varValue + 5*x4.varValue}\")\nprint(f\"Pine chips: {500*x1.varValue + 400*x2.varValue + 300*x3.varValue + 200*x4.varValue}\")\nprint(f\"Oak chips: {500*x1.varValue + 750*x2.varValue + 250*x3.varValue + 500*x4.varValue}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWelcome to the CBC MILP Solver \nVersion: 2.10.3 \nBuild Date: Dec 15 2019 \n\ncommand line - /home/sam/teaching/inde2000-curtin/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f9fb637a1e92408baed25d18e3fa7a38-pulp.mps -max -timeMode elapsed -solve -printingOptions all -solution /tmp/f9fb637a1e92408baed25d18e3fa7a38-pulp.sol (default strategy 1)\nAt line 2 NAME          MODEL\nAt line 3 ROWS\nAt line 9 COLUMNS\nAt line 30 RHS\nAt line 35 BOUNDS\nAt line 36 ENDATA\nProblem MODEL has 4 rows, 4 columns and 16 elements\nCoin0008I MODEL read with 0 errors\nOption for timeMode changed from cpu to elapsed\nPresolve 4 (0) rows, 4 (0) columns and 16 (0) elements\n0  Obj -0 Dual inf 3000 (4)\n0  Obj -0 Dual inf 3000 (4)\n3  Obj 58800\nOptimal - objective value 58800\nOptimal objective 58800 - 3 iterations time 0.002\nOption for printingOptions changed from normal to all\nTotal time (CPU seconds):       0.00   (Wallclock seconds):       0.00\n\nStatus: Optimal\nTahoe pallets: 23.0\nPacific pallets: 15.0\nSavannah pallets: 39.0\nAspen pallets: 0.0\nMaximum Profit: $58,800.00\n\nResource usage:\nGlueing: 5800.0\nPressing: 730.0\nPine chips: 29200.0\nOak chips: 32500.0\n```\n:::\n:::\n\n\n---\n\n## Question 3\n\nConsider the problem of diet optimisation. There are four different types of food: Brownies, Ice Cream, Cola, and Cheese Cake. The nutrition values and cost per unit are as follows: \n\n\n| | Brownies | Ice Cream | Cola | Cheese Cake |\n|---|---|---|---|---|\n| Calories | 400 | 200 | 150 | 500 |\n| Chocolate | 3 | 2 | 0 | 0 |\n| Sugar | 2 | 2 | 4 | 4 |\n| Fat | 2 | 4 | 1 | 5 |\n| Cost (\\$) | \\$0.50 | \\$0.20 | \\$0.30 | \\$0.80 |\n\nThe objective is to minimise the cost of the diet while satisfying the following nutritional requirements:\n\n- At least 500 calories,\n- At least 5 units of chocolate,\n- At least 10 units of sugar, and\n- At least 8 units of fat.\n\n---\n\n## Question 4\n\nTowAlong makes trailers at Kansas City, Denver, and Raleigh plants and ships these units to Birmingham, Milwaukee, Los Angeles, and Seattle distribution centres. In planning production for the next year, TowAlong estimates Kansas City, Denver, and Raleigh plant’s unit shipping cost between any plant and distribution centre, plant capacities, and distribution centre demands. These numbers are given in the table.\n\n| Plant/DC | Birmingham | Milwaukee | LA | Seattle | Capacity |\n|---|---|---|---|---|---|\n| Kansas City | \\$35 | \\$40 | \\$60 | \\$120 | 12,000 |\n| Denver | \\$30 | \\$30 | \\$45 | \\$130 | 8,000 |\n| Raleigh | \\$60 | \\$65 | \\$50 | \\$100 | 5,000 |\n| Demand | 9,000 | 3,000 | 9,500 | 1,500 | - |\n\n",
    "supporting": [
      "02tutorial_files"
    ],
    "filters": [],
    "includes": {}
  }
}