<!DOCTYPE html>
<html lang="en"><head>
<script src="04lecture_files/libs/clipboard/clipboard.min.js"></script>
<script src="04lecture_files/libs/quarto-html/tabby.min.js"></script>
<script src="04lecture_files/libs/quarto-html/popper.min.js"></script>
<script src="04lecture_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="04lecture_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04lecture_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="04lecture_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04lecture_files/libs/quarto-contrib/iconify-3.0.0/iconify-icon.min.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Lecturer: Sam Wiwatanapataphee">
  <title>Topic 4: Network Design Under Uncertainty</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="04lecture_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="04lecture_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="04lecture_files/libs/revealjs/dist/theme/quarto-31e77d737e81b9b945dd1098fae77c0e.css">
  <link href="04lecture_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="04lecture_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="04lecture_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="04lecture_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="04lecture_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="04lecture_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="04lecture_files/libs/quarto-diagram/mermaid.min.js"></script>
  <script src="04lecture_files/libs/quarto-diagram/mermaid-init.js"></script>
  <link href="04lecture_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
  
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    import elkLayouts from 'https://cdn.jsdelivr.net/npm/@mermaid-js/layout-elk@0/dist/mermaid-layout-elk.esm.min.mjs';
    mermaid.registerLayoutLoaders(elkLayouts);
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Topic 4: Network Design Under Uncertainty</h1>
  <p class="subtitle">05115130 Supply Chain Modelling and Optimisation</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Lecturer: Sam Wiwatanapataphee 
</div>
<div class="quarto-title-author-email">
<a href="mailto:275287a@curtin.edu.au">275287a@curtin.edu.au</a>
</div>
        <p class="quarto-title-affiliation">
            School of EECMS, Curtin University
          </p>
    </div>
</div>

  <p class="date">8 Jun 2026</p>
</section>
<section id="goals-today" class="slide level2 scrollable">
<h2>Goals Today</h2>
<div style="font-size: 85%;">
<ol type="1">
<li class="fragment"><p>Introduction</p>
<ul>
<li class="fragment">Sources of uncertainty and Risk</li>
</ul></li>
<li class="fragment"><p>Strategic decision tools in SC network design</p>
<ul>
<li class="fragment">Components of cash flow</li>
<li class="fragment">Cash flow equation</li>
</ul></li>
<li class="fragment"><p>Discounted cash flow (DCF) for network design</p>
<ul>
<li class="fragment">Components of a DCF</li>
<li class="fragment">Incorporating uncertainty into DCF</li>
<li class="fragment">DCF calculation process</li>
<li class="fragment">Net present value (NPV)</li>
<li class="fragment">Binomial representation of Uncertainty
<ul>
<li class="fragment">Multiplication binomial</li>
<li class="fragment">Additive binomial</li>
</ul></li>
</ul></li>
<li class="fragment"><p>Decision tree</p>
<ul>
<li class="fragment">Evaluating NPV using decision tree (Bellman’s Principle)</li>
</ul></li>
</ol>
</div>
</section>
<section id="introduction" class="slide level2">
<h2>1. Introduction</h2>
<p><span class="space-out"></span></p>
<p>SC network design and how companies structure and optimise their supply chains.</p>
<p><span class="space-out"></span></p>
<h4 class="fragment" id="key-design-decisions">Key design decisions</h4>
<div class="columns">
<div class="column">
<ul>
<li class="fragment">Location of <strong>production facilities</strong></li>
<li class="fragment">Location of <strong>distribution centers</strong></li>
</ul>
</div><div class="column">
<ul>
<li class="fragment"><strong>Inventory levels</strong></li>
<li class="fragment"><strong>Transportation flows</strong></li>
</ul>
</div></div>
<p><span class="space-out"></span></p>
<h4 class="fragment" id="uncertainty-in-supply-chains">Uncertainty in Supply Chains</h4>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>These decisions are made while <strong>key parameters fluctuate unpredictably</strong>:</p>
</div>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column block orange fragment center" style="width:20%;">
<p><strong>Demand</strong></p>
</div><div class="column block blue fragment center" style="width:20%;">
<p><strong>Supply</strong></p>
</div><div class="column block red fragment center" style="width:20%;">
<p><strong>Costs</strong></p>
</div><div class="column block green fragment center" style="width:20%;">
<p><strong>Lead times</strong></p>
</div></div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>This uncertainty creates challenges for traditional deterministic planning.</p>
</div>

<aside><div>
<p>Lead time = the total duration from order placement to delivery.</p>
</div></aside></section>
<section class="slide level2 scrollable">

<h3 id="sources-of-uncertainty-and-risk">1.1 Sources of Uncertainty and Risk</h3>
<div style="font-size:88%;">
<ol type="1">
<li class="fragment"><strong>Demand Uncertainty</strong>
<ul>
<li class="fragment">Variations in customer demand across regions or over time</li>
<li class="fragment">Seasonality, trends, and unexpected spikes (e.g., promotions, pandemics)</li>
</ul></li>
<li class="fragment"><strong>Supply Uncertainty</strong>
<ul>
<li class="fragment">Reliability of raw materials or components</li>
<li class="fragment">Quality issues, supplier financial stability, or capacity constraints</li>
</ul></li>
<li class="fragment"><strong>Cost and Price Fluctuations</strong>
<ul>
<li class="fragment">Changes in labour rates, material costs, or exchange rates</li>
<li class="fragment">Energy price volatility affecting production and transportation</li>
</ul></li>
<li class="fragment"><strong>Lead Time Variability</strong>
<ul>
<li class="fragment">Transportation delays due to logistics bottlenecks, customs, or weather events</li>
<li class="fragment">Production lead times extended by machine breakdown or labour strikes</li>
</ul></li>
<li class="fragment"><strong>External Disruptions</strong>
<ul>
<li class="fragment">Natural disasters (floods, earthquakes, pandemics) halting production or shipping</li>
<li class="fragment">Geopolitical risks (tariffs, sanctions, border closures)</li>
</ul></li>
</ol>
</div>
<aside class="notes">
<p>Introduce the five main sources of uncertainty in supply chains. Demand uncertainty relates to variability in customer demand patterns. Supply uncertainty arises from supplier reliability and capacity issues. Cost fluctuations occur due to changing input prices, labour costs, or exchange rates. Lead time variability results from transportation or production delays. External disruptions include large unexpected events such as natural disasters or geopolitical conflicts.</p>
<p>These uncertainties motivate the need for robust and resilient supply chain network design.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="strategic-decision-tools-in-sc-network-design" class="slide level2">
<h2>2. Strategic Decision Tools in SC Network Design</h2>
<div class="fragment" style="font-size:39px;">
<div class="callout callout-important callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>New objective</strong></p>
</div>
<div class="callout-content">
<p>Minimise costs while maintaining <em>service levels</em> and <em>resilience to disruptions</em>.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>When designing a <strong>SC network under uncertainty</strong>, companies must balance <em>long-term costs and risks</em> while <strong>meeting service requirements</strong>.</p>
</div>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Two widely used tools to support this strategic decision-making are</p>
</div>
<div class="columns">
<div class="column block orange fragment center" style="width:60%;">
<p><strong>Discounted Cash Flow (DCF) Analysis</strong></p>
</div><div class="column block blue fragment center" style="width:30%;">
<p><strong>Decision Trees</strong></p>
</div></div>
<div class="fragment" style="font-size:39px;">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Cash flow (CF)</strong></p>
</div>
<div class="callout-content">
<p>The net amount of cash and cash equivalents being transferred into and out of a business over a specific time period. Inflows are positive CF (e.g.&nbsp;revenue), while outflows are negative CF (e.g.&nbsp;expenses).</p>
</div>
</div>
</div>
</div>

<aside class="notes">
<p>Conclude by introducing the concept of resilience.</p>
<p>Robust supply chains are designed to continue operating effectively even when disruptions occur.</p>
<p>Examples include maintaining backup suppliers, strategic inventory buffers, or flexible transportation routes.</p>
<p>The goal is to balance efficiency with resilience so that supply chains can adapt to unexpected events.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside><div>
<p>Service level = the ability to meet customer demand on time and in full.<br> Resilience = the ability to recover quickly from disruptions and maintain operations.</p>
</div></aside></section>
<section class="slide level2">

<h3 id="components-of-cash-flow">2.1 Components of Cash Flow</h3>
<p><span class="space-out"></span></p>
<p>Cash flow can be categorised into <strong>three primary activities</strong></p>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column" style="width:3%;">

</div><div class="column block blue fragment center" style="width:28%;">
<p><strong>Operating</strong></p>
<ul>
<li class="fragment">Sales revenue<br>
</li>
<li class="fragment">Payments to suppliers<br>
</li>
<li class="fragment">Wages and operating costs</li>
</ul>
</div><div class="column block orange fragment center" style="width:28%;">
<p><strong>Investing</strong></p>
<ul>
<li class="fragment">Purchase of equipment<br>
</li>
<li class="fragment">Infrastructure investments<br>
</li>
<li class="fragment">Asset sales</li>
</ul>
</div><div class="column block purple fragment center" style="width:26%;">
<p><strong>Financing</strong></p>
<ul>
<li class="fragment">Loans and debt repayment<br>
</li>
<li class="fragment">Equity financing<br>
</li>
<li class="fragment">Dividend payments</li>
</ul>
</div></div>
<p><br></p>
<h3 class="fragment" id="cash-flow-equation">2.2 Cash Flow Equation</h3>
<p><span class="space-out"></span></p>
<div class="block gray fragment center">
<p><span style="color:blue;">Net Cash Flow</span> = <span style="color:green;">Total Cash Inflows</span> − <span style="color:red;">Total Cash Outflows</span></p>
</div>
<aside class="notes">
<p>Explain that cash flows are grouped into three categories.</p>
<p>Operating activities represent the firm’s core operations, including revenue from sales and payments for operating expenses.</p>
<p>Investing activities involve long-term assets such as purchasing equipment, facilities, or selling assets.</p>
<p>Financing activities relate to how the firm raises and returns capital, including loans, equity financing, and dividend payments.</p>
<p>Finally, emphasize that net cash flow is simply the difference between total inflows and total outflows.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 id="discounted-cash-flow-dcf-for-network-design">3. Discounted Cash Flow (DCF) for Network Design</h3>
<p><strong>DCF</strong> is a valuation method used to estimate the value of an investment based on its expected future cash flows. The DCF model calculates the <strong>present value (PV)</strong> of these cash flows, taking into account the <strong>time value of money</strong>.</p>
<div class="block green fragment center">
<p><strong>Time value of money</strong></p>
<p>Money (or CF) today are worth more than the future</p>
</div>
<div class="columns">
<div class="column center fragment">
<p><iconify-icon role="img" inline="" icon="material-symbols:money" style="color:darkgreen; font-size:96px;" aria-label="Icon money from material-symbols Iconify.design set." title="Icon money from material-symbols Iconify.design set."></iconify-icon></p>
<p>$100 Today</p>
</div><div class="column center fragment">
<p><iconify-icon role="img" inline="" icon="material-symbols:money" style="color:green; font-size:96px;" aria-label="Icon money from material-symbols Iconify.design set." title="Icon money from material-symbols Iconify.design set."></iconify-icon></p>
<p>$100 in 10 years time?</p>
</div></div>
<ul>
<li class="fragment"><p>DCF is widely used in finance to assess the <strong>intrinsic value</strong> of a company or project by discounting future cash flows back to their present value.</p></li>
<li class="fragment"><p>It is also used in <strong>capital budgeting</strong> and <strong>investment analysis</strong> to evaluate the profitability of projects, including supply chain network design decisions.</p></li>
</ul>

<aside><div>
<p>Intrinsic value = the actual worth of an asset based on its fundamentals, rather than its current market price.</p>
</div></aside></section>
<section class="slide level2">

<h3 id="components-of-a-dcf-for-network-design">3.1 Components of a DCF for Network Design</h3>
<table class="table-striped caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Component</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">🏭 <strong>Initial Investment</strong></td>
<td>Also known as capital expenditure (CapEx), these are upfront costs for land, facilities, and equipment.</td>
</tr>
<tr class="even">
<td style="text-align: center;">💰 <strong>Operating Cash Flows</strong></td>
<td>Ongoing revenues and costs from production and distribution.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">📦 <strong>Working Capital</strong></td>
<td>Funds tied up in inventory and accounts receivable/payable.</td>
</tr>
<tr class="even">
<td style="text-align: center;">🏗 <strong>Terminal Value</strong></td>
<td>The value of the project beyond the forecast period, often based on salvage value or perpetuity.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">% <strong>Discount Rate</strong></td>
<td>The rate used to discount future CFs, typically the Weighted Average Cost of Capital (WACC) adjusted for project risk.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><iconify-icon role="img" inline="" icon="material-symbols:money" style="color:darkgreen;" aria-label="Icon money from material-symbols Iconify.design set." title="Icon money from material-symbols Iconify.design set."></iconify-icon> <strong>Net Present Value (NPV)</strong></td>
<td>The sum of discounted CFs, used to evaluate the profitability of the project.</td>
</tr>
</tbody>
</table>

<aside><div>
<p>WACC = a company’s average cost of financing from all sources, both equity (stocks) and debt (loans or bonds), weighted by their proportion in the company’s capital structure.</p>
</div></aside></section>
<section id="incorporating-uncertainty-into-dcf" class="slide level2">
<h2>3.2 Incorporating Uncertainty into DCF</h2>
<div class="columns">
<div class="column" style="width:55%;">
<h3 id="time-value-of-money">⏳ Time Value of Money</h3>
<blockquote>
<p><strong>Cash in the future is worth less than cash today</strong></p>
</blockquote>
<p>Reasons:</p>
<ul>
<li class="fragment"><p>Inflation &amp; Opportunity cost</p></li>
<li class="fragment"><p>Risk and uncertainty</p></li>
</ul>
<h3 class="fragment" id="scenario-analysis">📊 Scenario Analysis</h3>
<ul>
<li class="fragment">Evaluate <strong>NPV under multiple scenarios</strong></li>
<li class="fragment">Examples: <strong>High, Medium, Low demand</strong></li>
<li class="fragment">Calculate <strong>expected NPV using scenario probabilities</strong></li>
</ul>
</div><div class="column" style="width:45%;">
<h3 class="fragment" id="stochastic-inputs">🎲 Stochastic Inputs</h3>
<ul>
<li class="fragment">Model uncertain parameters (<strong>demand, costs</strong>) as <strong>probability distributions</strong></li>
<li class="fragment">Use <strong>Monte Carlo simulation</strong> to generate many possible NPVs</li>
</ul>
<h3 class="fragment" id="sensitivity-analysis">🔎 Sensitivity Analysis</h3>
<ul>
<li class="fragment">Test how changes in key inputs affect NPV:
<ul>
<li class="fragment">Discount rate</li>
<li class="fragment">Demand forecasts</li>
<li class="fragment">Material costs</li>
</ul></li>
</ul>
</div></div>
</section>
<section class="slide level2">

<h4 id="how-does-the-concept-work">How does the Concept Work?</h4>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column" style="width:50%;">
<h4 class="fragment" id="forecast-future-cfs">💰 Forecast Future CFs</h4>
<ul>
<li class="fragment">Estimate expected <strong>CFs</strong>
<ul>
<li class="fragment">Revenues</li>
<li class="fragment">Salvage value</li>
</ul></li>
<li class="fragment">Estimate <strong>CF outflows</strong>
<ul>
<li class="fragment">Expenses</li>
<li class="fragment">Investments</li>
</ul></li>
<li class="fragment">Forecast for several years<br>
<em>(e.g., 5–10 years or longer)</em></li>
</ul>
</div><div class="column" style="width:50%;">
<h4 class="fragment" id="select-a-discount-rate">📉 Select a Discount Rate</h4>
<ul>
<li class="fragment"><p>Represents the <strong>required rate of return</strong> or the <strong>cost of capital</strong></p></li>
<li class="fragment"><p>Reflects compensation for <strong>investment risk</strong></p></li>
<li class="fragment"><p>Commonly used: <strong>Weighted Average Cost of Capital (WACC)</strong></p></li>
<li class="fragment"><p>May be adjusted for <strong>project-specific risk</strong></p></li>
</ul>
</div></div>
<p><span class="space-out"></span></p>
<div class="fragment" style="font-size:39px;">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Idea</strong></p>
</div>
<div class="callout-content">
<p>Future cash flows are converted into <strong>present value using a discount rate.</strong></p>
</div>
</div>
</div>
</div>
</section>
<section id="dcf-calculation-process" class="slide level2">
<h2>3.3 DCF Calculation Process</h2>
<div class="columns">
<div class="block blue center fragment column" data-fragment-index="1" style="width:35%;">
<p>💰<br> Estimate yearly inflows and outflows<br> <span class="math inline">\(CF_1, CF_2, CF_3, \dots, CF_n\)</span></p>
</div><div class="column center fragment" data-fragment-index="2" style="width:20%;">
<p><iconify-icon role="img" inline="" icon="mynaui:arrow-long-right" style="font-size:48px; margin-top: 68px;" aria-label="Icon arrow-long-right from mynaui Iconify.design set." title="Icon arrow-long-right from mynaui Iconify.design set."></iconify-icon></p>
</div><div class="block purple center fragment column" data-fragment-index="3" style="width:35%;">
<p>📉<br> Convert future cash flows into present value<br> <span class="math inline">\(PV_t=CF_t / (1+r)^t\)</span></p>
</div></div>
<div class="fragment" data-fragment-index="4">
<p><iconify-icon role="img" inline="" icon="mynaui:arrow-long-down" style="font-size:48px; margin-left: 77%;" aria-label="Icon arrow-long-down from mynaui Iconify.design set." title="Icon arrow-long-down from mynaui Iconify.design set."></iconify-icon></p>
</div>
<div class="columns">
<div class="block orange center fragment column" data-fragment-index="7" style="width:35%;">
<p>📈<br> Subtract initial investment<br> <span class="math inline">\(NPV = \sum PV_t - C_0\)</span></p>
</div><div class="column center fragment" data-fragment-index="6" style="width:20%;">
<p><iconify-icon role="img" inline="" icon="mynaui:arrow-long-left" style="font-size:48px; margin-top: 68px;" aria-label="Icon arrow-long-left from mynaui Iconify.design set." title="Icon arrow-long-left from mynaui Iconify.design set."></iconify-icon></p>
</div><div class="block green center fragment column" data-fragment-index="5" style="width:35%;">
<p>🧮<br> Add discounted cash flows<br> <span class="math inline">\(\sum PV_t\)</span></p>
</div></div>
<p><span class="space-out"></span></p>
<div class="fragment" style="font-size:40px;" data-fragment-index="8">
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Decision Rule:</strong> Choose the network design with the <strong>highest positive NPV</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="discount-the-cash-flows-formulas">3.4 Discount the Cash Flows Formulas</h3>
<p>Consider a simple example of receiving $1 in one year. The present value (PV) of that future cash flow can be calculated using the formula:</p>
<div class="columns">
<div class="column">
<div id="b90cc305" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="04lecture_files/figure-revealjs/cell-2-output-1.png" width="442" height="156"></p>
</figure>
</div>
</div>
</div>
</div><div class="block orange column fragment center" style="width:40%;">
<div style="font-size:90%;">
<p><span class="math display">\[
\text{Discount factor} = \frac{1}{1+r} = PV_0
\]</span></p>
</div>
</div></div>
<div class="fragment">
<div id="290727c0" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="04lecture_files/figure-revealjs/cell-3-output-1.png" width="1114" height="156"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment" style="font-size:85%;">
<p><span class="math display">\[
\text{NPV}=C_0+C_1\left(\frac{1}{1+r}\right)+C_2\left(\frac{1}{1+r}\right)^2\ldots+C_{T-1}\left(\frac{1}{1+r}\right)^{T-1}+C_T\left(\frac{1}{1+r}\right)^T
\]</span></p>
</div>
<div class="fragment center">
<p>What is the PV formula at time <span class="math inline">\(t\)</span>? Can you simplify it to the NPV formula?</p>
</div>
</section>
<section class="slide level2">

<h3 id="net-present-value">3.5 Net Present Value</h3>
<ul>
<li class="fragment"><p>Convert each future cash flow into <strong>present value</strong></p></li>
<li class="fragment"><p>Use the formula, <span class="math inline">\(C_t\)</span> denotes cash flow in period <em>t</em>,</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
PV_t = \frac{C_t}{(1+r)^t}
\]</span></p>
</div>
<div class="fragment">
<p>where <span class="math inline">\(r\)</span>= the discount rate and <span class="math inline">\(t\)</span>= time period (years).</p>
</div>
<ul>
<li class="fragment">Summing all present values gives the <strong>Net Present Value (NPV)</strong>:</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
NPV  = C_0 + \sum_{t=1}^T \left(\frac{1}{1+r}\right)^tC_t
\]</span></p>
</div>
<div class="fragment">
<p>where <span class="math inline">\(T\)</span> = Total number of periods and <span class="math inline">\(C_0\)</span> = Initial investment.</p>
</div>
</section>
<section class="slide level2">

<h4 id="interpreting-npv-results">Interpreting NPV Results</h4>
<p><span class="space-out"></span></p>
<div style="font-size:95%;">
<table class="table-striped caption-top">
<colgroup>
<col style="width: 7%">
<col style="width: 52%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">NPV</th>
<th>Interpretation</th>
<th>Suggested Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span style="color:green;"><strong>&gt; 0</strong></span></td>
<td>The project is expected to generate more cash than it costs, indicating a profitable investment.</td>
<td>Consider proceeding with the project.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span style="color:orange;"><strong>= 0</strong></span></td>
<td>The project is expected to break even, generating CFs equal to the initial investment.</td>
<td>The project may be acceptable, but it does not create additional value.</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span style="color:red;"><strong>&lt; 0</strong></span></td>
<td>The project is expected to generate less cash than it costs, indicating a loss.</td>
<td>Consider rejecting the project or re-evaluating assumptions.</td>
</tr>
</tbody>
</table>
</div>
<p><span class="space-out"></span></p>
<div class="fragment" style="font-size:38px;">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Decision Rule</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment"><p>Conduct a <strong>scenario analysis</strong> to evaluate NPV under different assumptions (e.g., demand levels, cost fluctuations).</p></li>
<li class="fragment"><p>Prefer projects with <span style="color:green;"><strong>higher positive NPV</strong></span> as they are expected to add more value to the company.</p></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h3 id="example-1">3.5.1 Example 1</h3>
<p>Suppose you have a project requiring an <strong>initial investment of $200,000 (Year 0)</strong> with expected annual cash inflows over the next <strong>five years</strong>. Future cash inflows will be <strong>discounted at 10%</strong> to compute their present values.</p>
<ol type="a">
<li>Fill in the missing values in the table below to calculate the NPV of the project.</li>
<li>Evaluate whether the project is financially attractive based on the NPV result.</li>
</ol>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Cash Flow</th>
<th style="text-align: right;">Discount Factor (10%)</th>
<th style="text-align: right;">Present Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">-200,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">50,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">60,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">70,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">80,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">90,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>NPV</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2 scrollable">

<ol type="a">
<li class="fragment">To calculate the NPV, we first need to compute the discount factor for each year. Then, we can calculate the PV of each cash flow by multiplying the CF by its corresponding discount factor. Finally, we sum all the PVs to get the NPV.</li>
</ol>
<div class="fragment" style="font-size:90%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Cash Flow</th>
<th style="text-align: right;">Discount Factor (10%)</th>
<th style="text-align: right;">Present Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">-200,000</td>
<td style="text-align: right;"><span class="math inline">\((1.1)^0=1.0000\)</span></td>
<td style="text-align: right;">-200,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">50,000</td>
<td style="text-align: right;"><span class="math inline">\((1.1)^{-1}=0.9091\)</span></td>
<td style="text-align: right;">45,455</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">60,000</td>
<td style="text-align: right;"><span class="math inline">\((1.1)^{-2}=0.8264\)</span></td>
<td style="text-align: right;">49,583</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">70,000</td>
<td style="text-align: right;"><span class="math inline">\((1.1)^{-3}=0.7513\)</span></td>
<td style="text-align: right;">52,591</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">80,000</td>
<td style="text-align: right;"><span class="math inline">\((1.1)^{-4}=0.6830\)</span></td>
<td style="text-align: right;">54,640</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">90,000</td>
<td style="text-align: right;"><span class="math inline">\((1.1)^{-5}=0.6209\)</span></td>
<td style="text-align: right;">55,878</td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>NPV</strong></td>
<td style="text-align: right;"><strong>$58,147</strong></td>
</tr>
</tbody>
</table>
</div>
<p><span class="space-out"></span></p>
<ol start="2" type="a">
<li class="fragment">Since the <strong>NPV is positive</strong>, the project is expected to generate more cash than it costs, indicating a profitable investment. Therefore, the project is financially attractive and may be considered for implementation.</li>
</ol>
</section>
<section class="slide level2 scrollable">

<h3 id="example-2">3.5.2 Example 2</h3>
<p><span class="space-out"></span></p>
<p>For the cash flows of two options with <span class="math inline">\(r = 0.1\)</span> (10%), <strong>which option is better?</strong></p>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Option 1</th>
<th style="text-align: right;">Option 1 PV</th>
<th style="text-align: right;">Option 2</th>
<th style="text-align: right;">Option 2 PV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">-1,000,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">-1,400,000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">300,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">300,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">300,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">300,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">300,000</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>Option 1 NPV</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>Option 2 NPV</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="fragment">
<ol type="a">
<li>Fill in the missing values in the table to calculate the NPV of each option.</li>
<li>Evaluate which option is better based on the NPV results.</li>
</ol>
</div>
</section>
<section class="slide level2 scrollable">

<ol type="a">
<li class="fragment">To calculate the NPV for each option, we will compute the present value of each cash flow using the formula <span class="math inline">\(PV_t = C_t/(1+r)^t = C_t(1+r)^{-t}\)</span>, where <span class="math inline">\(r = 0.1\)</span> (10%). Then, we will sum the present values to get the NPV for each option.</li>
</ol>
<p><span class="space-out"></span></p>
<div class="fragment" style="font-size:90%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Option 1 PV</th>
<th style="text-align: right;">Option 2 PV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(-1,000,000(1.1)^0=-1,000,000\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-1,400,000(1.1)^0=-1,400,000\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;"><span class="math inline">\(300,000(1.1)^{-1}=272,727\)</span></td>
<td style="text-align: right;"><span class="math inline">\(400,000(1.1)^{-1}=363,636\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;"><span class="math inline">\(300,000(1.1)^{-2}=247,934\)</span></td>
<td style="text-align: right;"><span class="math inline">\(400,000(1.1)^{-2}=330,579\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;"><span class="math inline">\(300,000(1.1)^{-3}=225,394\)</span></td>
<td style="text-align: right;"><span class="math inline">\(400,000(1.1)^{-3}=300,526\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;"><span class="math inline">\(300,000(1.1)^{-4}=204,904\)</span></td>
<td style="text-align: right;"><span class="math inline">\(400,000(1.1)^{-4}=273,205\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;"><span class="math inline">\(300,000(1.1)^{-5}=186,276\)</span></td>
<td style="text-align: right;"><span class="math inline">\(400,000(1.1)^{-5}=248,369\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>Option 1 NPV</strong> <span class="math inline">\(= 137,236\)</span></td>
<td style="text-align: right;"><strong>Option 2 NPV</strong> <span class="math inline">\(= 116,315\)</span></td>
</tr>
</tbody>
</table>
</div>
<p><span class="space-out"></span></p>
<ul>
<li class="fragment">Since the NPV of <strong>Option 1</strong> is higher than that of <strong>Option 2</strong>, Option 1 is the better choice based on the NPV criterion.</li>
</ul>
</section>
<section class="slide level2 scrollable">

<h3 id="example-3-target.com">3.5.3 Example 3: Target.com</h3>
<div class="columns">
<div class="column" style="width:70%;">
<h5 id="scenario">Scenario</h5>
<ul>
<li class="fragment">Estimated demand: <strong>100,000 units</strong> for online orders<br>
</li>
<li class="fragment">Required space: <strong>1,000 sq. ft. for every 1,000 units</strong><br>
</li>
<li class="fragment">Revenue: <strong>$1.22 per unit of demand</strong></li>
<li class="fragment">Discount factor: <strong>10% (<span class="math inline">\(r = 0.1\)</span>)</strong></li>
</ul>
</div><div class="column center" style="width:30%;">
<p><iconify-icon role="img" inline="" icon="cbi:target" style="color:#dd1931; font-size:102px;" aria-label="Icon target from cbi Iconify.design set." title="Icon target from cbi Iconify.design set."></iconify-icon><br> <span style="color:#dd1931; font-weight:bold;">TARGET</span></p>
</div></div>
<h5 class="fragment" id="questions">Questions</h5>
<ol type="1">
<li class="fragment">How much <strong>warehouse space</strong> should be leased in the next 3 years?</li>
<li class="fragment">Should Target sign a <strong>3-year lease contract</strong> or obtain warehousing space on the <strong>spot market each year</strong>?</li>
</ol>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column center">
<h5 class="fragment" id="option-1-spot-market"><strong>Option 1: Spot Market</strong></h5>
<ul>
<li class="fragment">Spot market rate <strong>~$1.20/sq.ft./year</strong> for each of the next 3 years</li>
</ul>
</div><div class="column center">
<h5 class="fragment" id="option-2-3-year-lease-contract"><strong>Option 2: 3-Year Lease Contract</strong></h5>
<ul>
<li class="fragment">Fixed lease rate of <strong>$1.00/sq.ft.</strong> locked in for <strong>3 years</strong></li>
</ul>
</div></div>
</section>
<section class="slide level2">

<h4 id="option-1-obtain-space-from-the-spot-market-each-year">Option 1: Obtain space from the spot market each year</h4>
<div style="font-size:92%;">
<ul>
<li>Spot market rate expected at $1.20/sq.ft./year for each of the next 3 years.</li>
<li>Required space 1,000 sq. ft. for every 1,000 units.</li>
<li>Estimated demand 100,000 units per year for online orders.</li>
<li>Revenue $1.22 for each unit of demand.</li>
</ul>
<p>First, calculate the expected annual profit (<span class="math inline">\(C_t\)</span>) if space is obtained from the spot market using discount factor <span class="math inline">\(r = 0.1\)</span> is given by</p>
</div>
<div class="fragment" style="font-size:92%;">
<p><span class="math display">\[
\begin{aligned}
\text{Profit} &amp;= \text{Revenue} - \text{Expense} \\
&amp;= (100{,}000 \text{ units} \times \$1.22) - (100{,}000 \text{ units} \times \$1.20) = \$2{,}000
\end{aligned}
\]</span></p>
</div>
<div class="columns" style="font-size:90%;">
<div class="column fragment" style="width:30%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;"><span class="math inline">\(C_t\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_t\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2,000</td>
<td style="text-align: right;">2,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2,000</td>
<td style="text-align: right;">1,818</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2,000</td>
<td style="text-align: right;">1,653</td>
</tr>
<tr class="even">
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>NPV</strong></td>
<td style="text-align: right;"><strong>$5,471</strong></td>
</tr>
</tbody>
</table>
</div><div class="column fragment center">
<p><span class="math display">\[
\begin{aligned}
\text{NPV (no lease)} &amp;= C_0 + \frac{C_1}{1+r} + \frac{C_2}{(1+r)^2} \\
&amp;= 2{,}000 + \frac{2{,}000}{1.1} + \frac{2{,}000}{1.1^2} \\
\therefore \text{NPV (no lease)} &amp;= \$5{,}471
\end{aligned}
\]</span></p>
</div></div>
</section>
<section class="slide level2">

<h4 id="option-2-sign-a-3-year-lease-contract">Option 2: Sign a 3-year lease contract</h4>
<div style="font-size:92%;">
<ul>
<li>100,000 sq.ft. of warehouse space are leased for the next 3 years.<br>
</li>
<li>Target pays $1 per sq.ft. of space leased each year.</li>
<li>Estimated demand 100,000 units per year for online orders.</li>
<li>Revenue $1.22 for each unit of demand.</li>
</ul>
</div>
<div class="fragment" style="font-size:92%;">
<p>Thus, the expected annual profit (<span class="math inline">\(C_t\)</span>) is</p>
<p><span class="math display">\[
\text{Revenue} - \text{Expense} = 100{,}000 \times \$1.22 - 100{,}000 \times \$1.00
= \$22{,}000
\]</span></p>
</div>
<div class="columns" style="font-size:90%;">
<div class="column fragment" style="width:30%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;"><span class="math inline">\(C_t\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_t\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">22,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">20,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">18,182</td>
</tr>
<tr class="even">
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>NPV</strong></td>
<td style="text-align: right;"><strong>$60,182</strong></td>
</tr>
</tbody>
</table>
</div><div class="column fragment center">
<p><span class="math display">\[
\begin{aligned}
\text{NPV (Lease)} &amp;=
C_0 + \frac{C_1}{1+r} + \frac{C_2}{(1+r)^2} \\
&amp;= 22{,}000 + \frac{22{,}000}{1.1} + \frac{22{,}000}{1.1^2} \\
\therefore \text{NPV (Lease)} &amp;= \$60{,}182
\end{aligned}
\]</span></p>
</div></div>
</section>
<section class="slide level2">

<h4 id="comparing-the-npv-of-two-options">Comparing the NPV of Two Options</h4>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column" style="width:10%;">

</div><div class="column fragment" style="width:40%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;"><span class="math inline">\(C_t\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_t\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2,000</td>
<td style="text-align: right;">2,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2,000</td>
<td style="text-align: right;">1,818</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2,000</td>
<td style="text-align: right;">1,653</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Option 1</strong></td>
<td style="text-align: right;"><strong>NPV</strong></td>
<td style="text-align: right;"><strong>$5,471</strong></td>
</tr>
</tbody>
</table>
</div><div class="column fragment center" style="width:40%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;"><span class="math inline">\(C_t\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_t\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">22,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">20,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">18,182</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Option 2</strong></td>
<td style="text-align: right;"><strong>NPV</strong></td>
<td style="text-align: right;"><strong>$60,182</strong></td>
</tr>
</tbody>
</table>
</div></div>
<p><span class="space-out"></span></p>
<ul>
<li class="fragment"><p>The NPV of signing the lease is 60,182 - 5,471 = <strong>$54,711 higher.</strong></p></li>
<li class="fragment"><p>Assume that there is no uncertainty in the demand and costs, Target.com should go with Option 2.</p></li>
<li class="fragment"><p>However, if there is significant uncertainty in demand or costs, Target.com may want to consider the flexibility of the spot market despite its lower NPV.</p></li>
</ul>
<div class="fragment" style="font-size:39px;">
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>How does uncertainty affect the decision between the two options? And how can we incorporate uncertainty into the NPV analysis?</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="binomial-representation-of-uncertainty">3.6 Binomial Representation of Uncertainty</h3>
<p><span class="space-out"></span></p>
<p>A binomial distribution is a discrete probability distribution that models the <strong>number of successes in a fixed number of independent trials</strong> of a <strong>binary experiment</strong> — where each trial results in only one of <strong>two outcomes: success or failure</strong>.</p>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="block blue center fragment">
<p><span class="math display">\[
P(X=k) = \binom{n}{k} p^k (1-p)^{n-k}
\]</span></p>
<p>for <span class="math inline">\(k=0,1,2,\dots,n\)</span> and <span class="math display">\[
\binom{n}{k} = \frac{n!}{k!(n-k)!}
\]</span></p>
</div>
</div><div class="column fragment" style="font-size: 85%">
<table class="caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Symbol</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
<td>Total number of trials</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(k\)</span></td>
<td>Number of successes</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(p\)</span></td>
<td>Probability of success on an individual trial</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(1-p\)</span></td>
<td>Probability of failure on an individual trial</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(P(X=k)\)</span></td>
<td>Probability of observing exactly <span class="math inline">\(k\)</span> successes in <span class="math inline">\(n\)</span> trials</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\dbinom{n}{k}\)</span></td>
<td>The number of ways to choose <span class="math inline">\(k\)</span> successes from <span class="math inline">\(n\)</span> trials</td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section class="slide level2">

<h4 id="example-binomial-representation-of-demand-uncertainty">Example: Binomial Representation of Demand Uncertainty</h4>
<ul>
<li class="fragment"><p>Suppose a company is launching a new product and wants to model the demand uncertainty using a binomial distribution.</p></li>
<li class="fragment"><p>The company estimates that there is a <strong>60%</strong> chance that the product will be <strong>successful</strong> and a <strong>40%</strong> chance that it will not be successful (<strong>failure</strong>).</p></li>
<li class="fragment"><p>The company plans to produce <strong>100 units</strong> of the product.</p></li>
<li class="fragment"><p>What is the probability of observing exactly <strong>70 units</strong> of demand?</p></li>
</ul>
<div class="fragment">
<p>From the question, identify the parameters:</p>
<p><span class="math display">\[
n=100, \quad k=70, \quad p=0.6
\]</span></p>
</div>
<div class="fragment">
<p>The probability is calculated using the binomial formula:</p>
<p><span class="math display">\[
P(X=70) = \binom{100}{70} (0.6)^{70} (0.4)^{30} = \frac{100!}{70! \cdot 30!} (0.6)^{70} (0.4)^{30} = 0.01
\]</span></p>
</div>
</section>
<section class="slide level2">

<h3 id="multiplicative-binomial">3.6.1 Multiplicative Binomial</h3>
<p>Given a price <span class="math inline">\(𝑃\)</span> in Period 0, the possible outcomes in the future periods are</p>
<div style="font-size:95%;">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Period</th>
<th style="text-align: center;">Outcomes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;"><span class="math inline">\(P\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(Pu,\; Pd\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(Pu^2,\; Pud,\; Pd^2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(Pu^3,\; Pu^2d,\; Pud^2,\; Pd^3\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(Pu^4,\; Pu^3d,\; Pu^2d^2,\; Pud^3,\; Pd^4\)</span></td>
</tr>
</tbody>
</table>
</div>
<p><span class="space-out"></span></p>
<div class="center fragment">
<p>General formula for the price at time <span class="math inline">\(t\)</span> is</p>
<p><span class="math display">\[
Pu^t d^{T-t}, \quad t=0,1,2,\dots,T
\]</span></p>
</div>
<div class="center fragment">
<p>At instant time <span class="math inline">\(t=a\)</span>, the price can move to either</p>
</div>
<div class="columns">
<div class="column center fragment">
<p><span class="math inline">\(Pu^{a+1}d^{T-a}\)</span></p>
<p>with probability <span class="math inline">\(\alpha\)</span></p>
</div><div class="column center fragment">
<p><span class="math inline">\(Pd^{a}u^{(T-a)+1}\)</span></p>
<p>with probability <span class="math inline">\(1-\alpha\)</span></p>
</div></div>
</section>
<section class="slide level2">

<h4 id="multiplicative-binomial-1">3.6.1 Multiplicative Binomial</h4>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "padding": 30,
    "nodeSpacing": 30,
    "rankSpacing": 60
  },
  "themeVariables": {
    "fontSize": "22px"
  }
}}%%

flowchart LR
  P((P)) --&gt;|α| Pu((Pu))
  P --&gt;|1-α| Pd((Pd))

  Pu --&gt;|α| Pu2((Pu²))
  Pu --&gt;|1-α| Pud((Pud))
  Pd --&gt; Pud
  Pd --&gt; Pd2((Pd²))

  Pu2 --&gt;|α| Pu3((Pu³))
  Pu2 --&gt;|1-α| Pu2d((Pu²d))
  Pud --&gt; Pu2d
  Pud --&gt; Pud2((Pud²))
  Pd2 --&gt; Pud2
  Pd2 --&gt; Pd3((Pd³))

  Pu3 --&gt;|α| Pu4((Pu⁴))
  Pu3 --&gt;|1-α| Pu3d((Pu³d))
  Pu2d --&gt; Pu3d
  Pu2d --&gt; Pu2d2((Pu²d²))
  Pud2 --&gt; Pu2d2
  Pud2 --&gt; Pud3((Pud³))
  Pd3 --&gt; Pud3
  Pd3 --&gt; Pd4((Pd⁴))

  Pu4 --&gt;|α| Pu5((Pu⁵))
  Pu4 --&gt;|1-α| Pu4d((Pu⁴d))
  Pu3d --&gt; Pu4d
  Pu3d --&gt; Pu3d2((Pu³d²))
  Pu2d2 --&gt; Pu3d2
  Pu2d2 --&gt; Pu2d3((Pu²d³))
  Pud3 --&gt; Pu2d3
  Pud3 --&gt; Pud4((Pud⁴))
  Pd4 --&gt; Pud4
  Pd4 --&gt; Pd5((Pd⁵))
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h4 id="multiplicative-binomial-examples">3.6.1 Multiplicative Binomial Examples</h4>
<p><span class="space-out"></span></p>
<p><strong>Example 1</strong> Given:</p>
<div class="columns">
<div class="column" style="width:35%;">
<ul>
<li>Initial asset price P = 100</li>
<li>Up factor u = 1.2</li>
<li>Down factor d = 0.8</li>
</ul>
</div><div class="column" style="width:65%;">
<ol type="a">
<li>Construct the binomial price tree up to 3 periods.</li>
<li>List all possible outcomes at t = 3.</li>
<li>Express the general formula for price at any node.</li>
</ol>
</div></div>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column fragment">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 40,
    "nodeSpacing": 15,
    "rankSpacing": 45
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
    "secondaryTextColor": "#000000"
  }
}}%%

flowchart LR
  P([100]) --&gt; Pu([120])
  P --&gt; Pd([80])

  Pu --&gt; Pu2([144])
  Pu --&gt; Pud([96])
  Pd --&gt; Pud
  Pd --&gt; Pd2([64])

  Pu2 --&gt; Pu3([172.8])
  Pu2 --&gt; Pu2d([115.2])
  Pud --&gt; Pu2d
  Pud --&gt; Pud2([76.8])
  Pd2 --&gt; Pud2
  Pd2 --&gt; Pd3([51.2])

  classDef default fill:#ffffff,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column fragment">
<p><span class="space-out"></span></p>
<p>The general formula for price at any node is given by</p>
<p><span class="math display">\[
P u^t  d^{T-t} = 100(1.2)^t (0.8)^{T-t},
\]</span></p>
<p><span class="math display">\[
\quad t=0,1,2,\dots,T
\]</span></p>
<p>where <span class="math inline">\(t\)</span> is the number of up moves and <span class="math inline">\(T-t\)</span> is the number of down moves.</p>
</div></div>
</section>
<section class="slide level2 scrollable">

<h4 id="multiplicative-binomial-examples-1">3.6.1 Multiplicative Binomial Examples</h4>
<p><strong>Example 2</strong> Given:</p>
<div class="columns">
<div class="column" style="width:33%;">
<ul>
<li>Initial asset price P = 50</li>
<li>u = 1.1, d = 0.9</li>
<li>Risk-neutral probability <span class="math inline">\(\alpha\)</span> = 0.6</li>
</ul>
</div><div class="column" style="width:67%;">
<ol type="a">
<li>Calculate all possible prices at T = 2.</li>
<li>Find the probability of ending up at each price level.</li>
<li>What is the probability that the final price is greater than 50?</li>
</ol>
</div></div>
<div class="columns">
<div class="column fragment" style="width:45%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 40,
    "nodeSpacing": 15,
    "rankSpacing": 45
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
    "secondaryTextColor": "#000000"
  }
}}%%

flowchart LR
  P([50]) --&gt;|α|Pu([55])
  P --&gt;|1-α| Pd([45])

  Pu --&gt;|α| Pu2([60.5])
  Pu --&gt;|1-α| Pud([49.5])
  Pd --&gt;|α| Pud
  Pd --&gt;|1-α| Pd2([40.5])

  classDef default fill:#ffffff,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column fragment" style="font-size:90%;">
<p><span style="display: block; margin-bottom: 44px;"></span></p>
<div class="fragment">
<p><span class="math inline">\(P=\alpha^2=0.36=P(\text{Final price} &gt; 50)\)</span></p>
</div>
<p><br></p>
<div class="fragment">
<p><span class="math inline">\(P=\alpha(1-\alpha)=0.24\)</span></p>
</div>
<p><br></p>
<div class="fragment">
<p><span class="math inline">\(P=(1-\alpha)^2=0.16\)</span></p>
</div>
</div></div>
</section>
<section class="slide level2">

<h3 id="additive-binomial">3.6.2 Additive Binomial</h3>
<p><span class="space-out"></span></p>
<p>Given a price <span class="math inline">\(𝑃\)</span> in Period 0, the possible outcomes in the future periods are</p>
<p><span class="space-out"></span></p>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Period</th>
<th style="text-align: center;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;"><span class="math inline">\(P\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(P+u,\; P-d\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(P+2u,\; P+u-d,\; P-2d\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(P+3u,\; P+2u-d,\; P+u-2d,\; P-3d\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(P+4u,\; P+3u-d,\; P+2u-2d,\; P+u-3d,\; P-4d\)</span></td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<div class="center fragment">
<p>General formula for the price at time <span class="math inline">\(t\)</span> is</p>
<p><span class="math display">\[
P + tu - (T-t)d, \quad t=0,1,2,\dots,T
\]</span></p>
</div>
</section>
<section class="slide level2">

<h4 id="additive-binomial-1">3.6.2 Additive Binomial</h4>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "padding": 30,
    "nodeSpacing": 40,
    "rankSpacing": 40
  },
  "themeVariables": {
    "fontSize": "22px"
  }
}}%%

flowchart LR
  P([P]) --&gt;|α| Pu([P+u])
  P --&gt;|1-α| Pd([P-d])

  Pu --&gt;|α| Pu2([P+2u])
  Pu --&gt;|1-α| Pud([P+u-d])
  Pd --&gt; Pud
  Pd --&gt; Pd2([P-2d])

  Pu2 --&gt;|α| Pu3([P+3u])
  Pu2 --&gt;|1-α| Pu2d([P+2u-d])
  Pud --&gt; Pu2d
  Pud --&gt; Pud2([P+u-2d])
  Pd2 --&gt; Pud2
  Pd2 --&gt; Pd3([P-3d])

  Pu3 --&gt;|α| Pu4([P+4u])
  Pu3 --&gt;|1-α| Pu3d([P+3u-d])
  Pu2d --&gt; Pu3d
  Pu2d --&gt; Pu2d2([P+2u-2d])
  Pud2 --&gt; Pu2d2
  Pud2 --&gt; Pud3([P+u-3d])
  Pd3 --&gt; Pud3
  Pd3 --&gt; Pd4([P-4d])

  Pu4 --&gt;|α| Pu5([P+5u])
  Pu4 --&gt;|1-α| Pu4d([P+4u-d])
  Pu3d --&gt; Pu4d
  Pu3d --&gt; Pu3d2([P+3u-2d])
  Pu2d2 --&gt; Pu3d2
  Pu2d2 --&gt; Pu2d3([P+2u-3d])
  Pud3 --&gt; Pu2d3
  Pud3 --&gt; Pud4([P+u-4d])
  Pd4 --&gt; Pud4
  Pd4 --&gt; Pd5([P-5d])
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h4 id="additive-binomial-examples">3.6.2 Additive Binomial Examples</h4>
<p><strong>Example 1</strong> Given:</p>
<div class="columns">
<div class="column" style="width:33%;">
<ul>
<li>Initial asset price P = 50</li>
<li>Up increment u = 3</li>
<li>Down decrement d = 2</li>
</ul>
</div><div class="column" style="width:67%;">
<ol type="a">
<li>Construct the additive binomial price tree for T = 3.</li>
<li>List all possible outcomes at T = 3.</li>
<li>Express the general formula for price at any node.</li>
</ol>
</div></div>
<div class="columns">
<div class="column fragment" style="width:35%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 35,
    "nodeSpacing": 15,
    "rankSpacing": 40
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
    "secondaryTextColor": "#000000"
  }
}}%%

flowchart LR
  P((50)) --&gt;|α|Pu((53))
  P --&gt;|1-α| Pd((48))

  Pu --&gt;|α| Pu2((56))
  Pu --&gt;|1-α| Pud((51))
  Pd --&gt;|α| Pud
  Pd --&gt;|1-α| Pd2((46))

  classDef default fill:#ffffff,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column fragment" style="width:65%;">
<p>The general formula for price at any node is given by</p>
<p><span class="math display">\[
\begin{aligned}
P + tu - (T-t)d &amp;= 50 + 3t - 2(T-t) \\
&amp;= 50 + 5t - 2T,
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\quad t=0,1,2,3, \dots,T
\]</span></p>
<p>where <span class="math inline">\(t\)</span> is the number of up moves and <span class="math inline">\(T-t\)</span> is the number of down moves.</p>
</div></div>
</section>
<section class="slide level2">

<h4 id="additive-binomial-examples-1">3.6.2 Additive Binomial Examples</h4>
<p><strong>Example 2</strong> Using the same parameters: P = 100 and T = 2,</p>
<ul>
<li>Build both the additive and multiplicative trees and compare the final prices.</li>
<li>For additive model, u = 5 and d = 3. For multiplicative model, u = +5%, d = -3%</li>
<li>Discuss which model may be more realistic in financial contexts and why.</li>
</ul>
<div class="columns">
<div class="column" style="width:10%;">

</div><div class="column center fragment" style="width:40%;">
<p><strong>Additive Tree</strong></p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 25,
    "nodeSpacing": 15,
    "rankSpacing": 45
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
    "secondaryTextColor": "#000000"
  }
}}%%

flowchart LR
  P([100]) --&gt;|α|Pu([105])
  P --&gt;|1-α| Pd([97])

  Pu --&gt;|α| Pu2([110])
  Pu --&gt;|1-α| Pud([102])
  Pd --&gt;|α| Pud
  Pd --&gt;|1-α| Pd2([94])

  classDef default fill:#fff3cd,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column center fragment" style="width:40%;">
<p><strong>Multiplicative Tree</strong></p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 25,
    "nodeSpacing": 15,
    "rankSpacing": 45
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
    "secondaryTextColor": "#000000"
  }
}}%%

flowchart LR
  P([100]) --&gt;|α|Pu([105])
  P --&gt;|1-α| Pd([97])

  Pu --&gt;|α| Pu2([110.25])
  Pu --&gt;|1-α| Pud([101.85])
  Pd --&gt;|α| Pud
  Pd --&gt;|1-α| Pd2([94.09])

  classDef default fill:#f8d7da,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div></div>
<ul>
<li class="fragment">The multiplicative model may be more realistic in financial contexts because it captures the <strong>compounding effect of returns</strong>.</li>
</ul>
</section>
<section id="decision-trees" class="slide level2">
<h2>4. Decision Trees</h2>
<p>A decision tree is a decision support recursive partitioning structure that uses a tree-like model of decisions and their possible consequences, including chance event outcomes, resource costs, and utility.</p>
<div class="columns" style="font-size:95%;">
<div class="column center fragment">
<p><strong>Binomial Tree</strong></p>
<p>Each node has two outcomes: up or down: (binary branching)</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "padding": 20,
    "nodeSpacing": 5,
    "rankSpacing": 70
  },
  "themeVariables": {
    "fontSize": "22px"
  }
}}%%

flowchart LR
  P(( )) --&gt; Pu(( ))
  P --&gt; Pd(( ))

  Pu --&gt; Pu2(( ))
  Pu --&gt; Pud(( ))
  Pd --&gt; Pud
  Pd --&gt; Pd2(( ))

  Pu2 --&gt; Pu3(( ))
  Pu2 --&gt; Pu2d(( ))
  Pud --&gt; Pu2d
  Pud --&gt; Pud2(( ))
  Pd2 --&gt; Pud2
  Pd2 --&gt; Pd3(( ))

  Pu3 --&gt; Pu4(( ))
  Pu3 --&gt; Pu3d(( ))
  Pu2d --&gt; Pu3d(( ))
  Pu2d --&gt; Pu2d2(( ))
  Pud2 --&gt; Pu2d2(( ))
  Pud2 --&gt; Pud3(( ))
  Pd3 --&gt; Pud3
  Pd3 --&gt; Pd4(( ))

  classDef default fill:#cfe2ff,stroke:#000000,color:#ffffff;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Move forward in discrete time steps</p>
<p>Based on risk-neutral probabilities</p>
</div><div class="column center fragment">
<p><strong>Decision Tree</strong></p>
<p>Each node can have multiple branches representing choices or events</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "padding": 22,
    "nodeSpacing": 8,
    "rankSpacing": 70
  },
  "themeVariables": {
    "fontSize": "22px"
  }
}}%%

flowchart LR
  P0(( )) --&gt; P11(( ))
  P0 --&gt; P12(( ))
  P0 --&gt; P13(( ))

  P11 --&gt; P21(( ))
  P11 --&gt; P22(( ))
  
  P12 --&gt; P22
  P12 --&gt; P23(( ))
  P12 --&gt; P24(( ))
  P12 --&gt; P25(( ))

  P21 --&gt; P31(( ))

  P22 --&gt; P31
  P22 --&gt; P32(( ))

  P23 --&gt; P32
  P23 --&gt; P33(( ))
  P23 --&gt; P34(( ))

  P31 --&gt; P41(( ))
  P31 --&gt; P42(( ))

  P33 --&gt; P43(( ))

  P34 --&gt; P43(( ))
  P34 --&gt; P44(( ))


  classDef default fill:#d1e7dd,stroke:#000000,color:#ffffff;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Move along decision-event-decision cycles</p>
<p>Includes probabilities and payoffs</p>
</div></div>
</section>
<section class="slide level2">

<h3 id="example-1-warehouse-location-decision">4.1.1 Example 1: Warehouse Location Decision</h3>
<p><span class="space-out"></span></p>
<p>A company must decide how to expand its distribution network.</p>
<p><span class="space-out"></span></p>
<h4 class="fragment center" id="decision-node">Decision Node</h4>
<div class="fragment">
<p>Choose between two strategies:</p>
</div>
<div class="columns">
<div class="column center fragment block blue" style="width:45%;">
<p><span style="display: block; margin-bottom: 28px;"></span></p>
<p>Build a Large DC Now</p>
<p><span style="display: block; margin-bottom: 28px;"></span></p>
</div><div class="column center fragment block yellow" style="width:45%;">
<p>Build a Small DC with Option to Expand Later</p>
</div></div>
<p><span class="space-out"></span></p>
<h4 class="fragment center" id="chance-node-future-demand">Chance Node: Future Demand</h4>
<div class="fragment">
<p>Demand next year is uncertain:</p>
</div>
<div class="columns">
<div class="column center fragment block green" style="width:45%;">
<p>High Demand (Probability = 0.6)</p>
</div><div class="column center fragment block red" style="width:45%;">
<p>Low Demand (Probability = 0.4)</p>
</div></div>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:15%;">

</div><div class="column" style="width:75%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 40,
    "nodeSpacing": 5,
    "rankSpacing": 80
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "20px",
    "secondaryColor": "#ffffff"
  }
}}%%

graph LR
    A(["Decision"])

    A --&gt; B(["Large DC"])
    A --&gt; C(["Small DC"])

    B --&gt;|0.6| B1(["High Demand&lt;br/&gt;NPV = $12M"])
    B --&gt;|0.4| B2(["Low Demand&lt;br/&gt;NPV = $2M"])

    C --&gt;|0.6| C1(["High Demand&lt;br/&gt;NPV = $15M"])
    C --&gt;|0.4| C2(["Low Demand&lt;br/&gt;NPV = $4M"])

    classDef default fill:#d1e7dd,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:10%;">

</div></div>
<div class="fragment">
<p><span class="math display">\[
EV_{Large} = 0.6(12) + 0.4(2) = \$8\text{M}
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
EV_{Flexible} = 0.6(15) + 0.4(4) = \$10.6\text{M}
\]</span></p>
</div>
<div class="fragment">
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<div style="font-size:1.4em; text-align:center;">
<p>The <strong>flexible strategy</strong> is preferred because it provides a <strong>higher expected value</strong> and allows adaptation to demand uncertainty.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="example-2-regional-distribution-hub-decision">4.1.2 Example 2: Regional Distribution Hub Decision</h3>
<p><span class="space-out"></span></p>
<p>A logistics company must decide whether to <strong>build a central hub</strong> or <strong>keep decentralised warehouses</strong>.</p>
<p><span class="space-out"></span></p>
<h4 class="fragment center" id="decision-node-1">Decision Node</h4>
<div class="fragment">
<p>Two alternatives:</p>
</div>
<div class="columns">
<div class="column center fragment block blue" style="width:45%;">
<p><span style="display: block; margin-bottom: 28px;"></span></p>
<p>Build a Central DC</p>
<p><span style="display: block; margin-bottom: 28px;"></span></p>
</div><div class="column center fragment block yellow" style="width:45%;">
<p>Keep Current Decentralised Warehouses</p>
</div></div>
<p><span class="space-out"></span></p>
<h4 class="fragment center" id="chance-node">Chance Node</h4>
<div class="fragment">
<p>Demand over the next 5 years is uncertain:</p>
</div>
<div class="columns">
<div class="column center fragment block green" style="width:29%;">
<p>High Growth (Probability = 0.5)</p>
</div><div class="column center fragment block yellow" style="width:29%;">
<p>Moderate Growth (Probability = 0.3)</p>
</div><div class="column center fragment block red" style="width:29%;">
<p>Low Growth (Probability = 0.2)</p>
</div></div>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:10%;">

</div><div class="column" style="width:85%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 30,
    "nodeSpacing": 5,
    "rankSpacing": 160
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "20px",
    "secondaryColor": "#ffffff"
  }
}}%%
flowchart LR

  A(["Decision"])

  A --&gt; B(["Central Hub"])
  A --&gt; C(["Decentralised"])

  B --&gt;|0.5| B1(["$25M"])
  B --&gt;|0.3| B2(["$14M"])
  B --&gt;|0.2| B3(["-$5M"])

  C --&gt;|0.5| C1(["$18M"])
  C --&gt;|0.3| C2(["$12M"])
  C --&gt;|0.2| C3(["$6M"])

  classDef default fill:#fff3cd,stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:5%;">

</div></div>
<div class="fragment" style="font-size:90%;">
<p><span class="math display">\[
EV_\text{Central Hub} = 0.5(25) + 0.3(14) + 0.2(-5) = 12.5 + 4.2 - 1 = 15.7
\]</span></p>
</div>
<div class="fragment" style="font-size:90%;">
<p><span class="math display">\[
EV_\text{Decentralised} = 0.5(18) + 0.3(12) + 0.2(6) = 9 + 3.6 + 1.2 = 13.8
\]</span></p>
</div>
<div class="fragment">
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<div style="font-size:1.4em; text-align:center;">
<p>The <strong>central hub strategy</strong> has the <strong>higher expected value (15.7M)</strong> and is the preferred network design decision.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h3 id="evaluating-npv-bellmans-principle">4.2 Evaluating NPV: Bellman’s Principle</h3>
<div style="font-size:1.4em;">
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Solve the problem from the end (future outcomes) back to the beginning.</p>
</div>
</div>
</div>
</div>
<ol type="1">
<li class="fragment"><strong>Structure the decision tree</strong>
<ul>
<li class="fragment">Draw nodes and terminal nodes (outcomes) connected with arrows</li>
</ul></li>
<li class="fragment"><strong>Assign payoffs and probabilities for each node</strong>
<ul>
<li class="fragment">For each node, calculate payoffs (or a combination of demand and price) and state the probability.</li>
</ul></li>
<li class="fragment"><strong>Work backwards (Bellman’s principle)</strong>
<ul>
<li class="fragment"><p>From the terminal node, calculate</p>
<p><span style="color: blue;"><span class="math inline">\(\text{Expected Monetary Value (EMV)} = \sum (\text{Probability} \times \text{Payoff})\)</span></span></p></li>
<li class="fragment"><p>Discount EMV to Present Value (PV)</p></li>
</ul></li>
<li class="fragment"><strong>Continue working backward until you reach the initial decision.</strong></li>
</ol>

<aside><div>
<p>Bellman: “An optimal policy has the property that, regardless of the initial state, the remaining decisions must constitute an optimal policy with respect to the resulting state.”</p>
</div></aside></section>
<section class="slide level2">

<h3 id="example-1-project-evaluation-1-period">4.2.1 Example 1: Project Evaluation (1 Period)</h3>
<p><span class="space-out"></span></p>
<p>Imagine a company considering a project that costs $50,000. There are two scenarios:</p>
<ul>
<li>High demand (60%): earns $100,000</li>
<li>Low demand (40%): earns $30,000</li>
</ul>
<p>Assume a discount rate of 10% and 1-year horizon. Evaluate the project.</p>
<p><span class="space-out"></span></p>
<div class="fragment">
<p>Starts from the terminal node,</p>
<p><span class="math display">\[
\begin{aligned}
EMV &amp;= 0.6(100,000)+0.4(30,000)=60,000+12,000=72,000 \\[.5em]
PV &amp;= 72,000 / 1.1 = 65,455 \\[.5em]
NPV &amp;= PV - C_0 = 65,455 - 50,000 = \textbf{\$15,455} &gt; 0
\end{aligned}
\]</span></p>
</div>
<ul>
<li class="fragment">Positive NPV suggests a profitable investment in 1-year horizon.</li>
</ul>
</section>
<section class="slide level2 scrollable">

<h3 id="example-2-project-evaluation-2-periods">4.2.2 Example 2: Project Evaluation (2 Periods)</h3>
<p><span class="space-out"></span></p>
<p>Imagine a company considering a project that costs $50,000.</p>
<p>In <strong>Year 1</strong>,</p>
<ul>
<li>High demand (60%): the company can invest $20,000 more to expand.</li>
<li>Low demand (40%): the project ends; no further payoff.</li>
</ul>
<p>In <strong>Year 2</strong>, expansion leads to:</p>
<ul>
<li>$150,000 (70%)</li>
<li>$50,000 (30%)</li>
</ul>
<p><strong>Note.</strong> For this example, the cashflows are realised at Year 2.</p>
<p>Use the discount rate of 10%.</p>
<ol type="a">
<li>Draw a Decision Tree</li>
<li>Calculate the NPV of the project</li>
</ol>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:20%;">

</div><div class="column" style="width:60%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 20,
    "nodeSpacing": 30,
    "rankSpacing": 40
  },
  "theme": "default",
  "themeVariables": {
    "fontSize": "20px",
    "secondaryColor": "#ffffff"
  }
}}%%
flowchart LR
  subgraph P0["Year 0"]
  A([-$50k])
  end

  subgraph P1["Year 1"]
  A --&gt;|0.6| B([High&lt;br&gt;-$20k])
  A --&gt;|0.4| C([Low])
  end

  subgraph P2["Year 2"]
  B --&gt;|0.7| D([$150k])
  B --&gt;|0.3| E([$50k])
  end

  classDef default fill:#cfe2ff,stroke:#000000,color:#000000;
  style B color:green;
  style P0 fill:#ffffff,stroke:#ffffff
  style P1 fill:#ffffff,stroke:#ffffff
  style P2 fill:#ffffff,stroke:#ffffff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:10%;">

</div></div>
<div style="font-size:80%">
<h4 class="fragment center" id="textyear-2-emv_textyear-2-pv_textyear-1-textnet-payoff_textyear-1"><span class="math inline">\(\text{Year 2}\)</span>: <span class="math inline">\(EMV_\text{Year 2}\)</span> → <span class="math inline">\(PV_\text{Year 1}\)</span> → <span class="math inline">\(\text{Net Payoff}_\text{Year 1}\)</span></h4>
<div class="fragment">
<p><span class="math display">\[
EMV_\text{Year 2} = 0.7(150,000) + 0.3(50,000) = 105,000 + 15,000 = 120,000
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
PV_\text{Year 1} = 120,000 / 1.1 = 109,091
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
\text{Net payoff at Year 1} = 109,091 - \color{green}{20,000} = \color{purple}{89,091}
\]</span></p>
</div>
<h4 class="fragment center" id="textyear-1-emv_textyear-1-pv_textyear-0-textnet-payoff_textyear-0"><span class="math inline">\(\text{Year 1}\)</span>: <span class="math inline">\(EMV_\text{Year 1}\)</span> → <span class="math inline">\(PV_\text{Year 0}\)</span> → <span class="math inline">\(\text{Net Payoff}_\text{Year 0}\)</span></h4>
<div class="fragment">
<p><span class="math display">\[
EMV_\text{Year 1} = 0.6(\color{purple}{89,091}) + 0.4(0) = 53,455
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
PV_\text{Year 0} = 53,455 / 1.1 = 48,595
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
NPV_\text{Year 0} = PV_\text{Year 0} - C_0 = 48,595 - 50,000 = \textbf{-\$1,405}
\]</span></p>
</div>
</div>

<aside><div>
<p>The cashflows are realised at Year 2. Work backward.</p>
</div></aside></section>
<section class="slide level2 scrollable">

<h3 id="example-3-multi-stage-project-evaluation">4.2.3 Example 3: Multi-Stage Project Evaluation</h3>
<p>Imagine a company considering a project that costs $50,000.</p>
<p>In <strong>Year 1</strong>,</p>
<ul>
<li>High demand (60%):
<ul>
<li>Earns $30,000 immediately</li>
<li>The company can invest $20,000 more to expand.</li>
</ul></li>
<li>Low demand (40%):
<ul>
<li>Earns $10,000 immediately</li>
<li>The project terminates.</li>
</ul></li>
</ul>
<p>In <strong>Year 2</strong>, expansion leads to: $150,000 (70%) or $50,000 (30%)</p>
<p>Use the discount rate of 10%.</p>
<ol type="a">
<li>Draw a Decision Tree</li>
<li>Calculate the NPV of the project</li>
</ol>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:20%;">

</div><div class="column" style="width:60%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 20,
    "nodeSpacing": 30,
    "rankSpacing": 50
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "20px",
    "secondaryColor": "#ffffff"
  }
}}%%
flowchart LR
  subgraph P0["Year 0"]
  A([-$50k])
  end

  subgraph P1["Year 1"]
  A --&gt;|0.6| B([$30k&lt;br&gt;-$20k])
  A --&gt;|0.4| C([$10k])
  end

  subgraph P2["Year 2"]
  B --&gt;|0.7| D([$150k])
  B --&gt;|0.3| E([$50k])
  end

  classDef default fill:#d1e7dd,stroke:#00000,color:#000000;
  style C color:red;
  style B color:green;
  style P0 fill:#ffffff,stroke:#ffffff
  style P1 fill:#ffffff,stroke:#ffffff
  style P2 fill:#ffffff,stroke:#ffffff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:10%;">

</div></div>
<div style="font-size:80%">
<h4 class="fragment center" id="textyear-2-emv_textyear-2-pv_textyear-1-textnet-payoff_textyear-1-1"><span class="math inline">\(\text{Year 2}\)</span>: <span class="math inline">\(EMV_\text{Year 2}\)</span> → <span class="math inline">\(PV_\text{Year 1}\)</span> → <span class="math inline">\(\text{Net Payoff}_\text{Year 1}\)</span></h4>
<div class="fragment">
<p><span class="math display">\[
EMV_\text{Year 2} = 0.7(150,000) + 0.3(50,000) = 105,000 + 15,000 = 120,000
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
PV_\text{Year 1} = 120,000 / 1.1 = 109,091
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
\text{Net payoff at Year 1} = 109,091 \color{green}{- 20,000 + 30,000}= \color{purple}{119,091}
\]</span></p>
</div>
<h4 class="fragment center" id="textyear-1-emv_textyear-1-pv_textyear-0-textnet-payoff_textyear-0-1"><span class="math inline">\(\text{Year 1}\)</span>: <span class="math inline">\(EMV_\text{Year 1}\)</span> → <span class="math inline">\(PV_\text{Year 0}\)</span> → <span class="math inline">\(\text{Net Payoff}_\text{Year 0}\)</span></h4>
<div class="fragment">
<p><span class="math display">\[
EMV_\text{Year 1} = 0.6(\color{purple}{119,091}) + 0.4(\color{red}{10,000}) = 75,455
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
PV_\text{Year 0} = 75,455 / 1.1 = 68,595
\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[
NPV_\text{Year 0} = PV_\text{Year 0} - C_0 = 68,595 - 50,000 = \textbf{\$18,595}
\]</span></p>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="example-4-target.com">4.2.4 Example 4: Target.com</h3>
<p>Let’s revisit 3.5.3 Example 3 – Target.com.</p>
<p>The Target manager anticipated uncertainty in demand and spot prices over the next three years</p>
<ul style="list-style-type:none; margin-top:0.8em;">
<li class="fragment" style="margin-bottom:0.5em;">
❖&nbsp; Long-term lease
<ul style="list-style-type:none; margin-top:0.3em;">
<li class="fragment">
✓ Cheaper than the spot market rate
</li>
<li class="fragment">
✓ Could go unused if demand is lower than forecast
</li>
</ul>
</li>
<li class="fragment" style="margin-bottom:0.5em;">
❖&nbsp; Spot market
<ul style="list-style-type:none; margin-top:0.3em;">
<li class="fragment">
✓ Currently high, but future rates could decrease.
</li>
<li class="fragment">
✓ Cost a lot if future demand is higher than expected.
</li>
</ul>
</li>
<li class="fragment">
❖&nbsp; Decide whether to
<ul style="list-style-type:none; margin-top:0.3em;">
<li class="fragment">
✓ Lease warehouse space for the coming years and
</li>
<li class="fragment">
✓ The quantity to lease
</li>
</ul>
</li>
</ul>
</section>
<section class="slide level2">

<h4 id="identify-all-options-and-information">Identify all options and information</h4>
<p><span class="space-out"></span></p>
<div class="columns">
<div class="column" style="width:15%;">
<div class="fragment" data-fragment-index="1">
<p><span style="color:blue;"><strong>Option 1:</strong></span></p>
</div>
<div class="fragment" data-fragment-index="2">
<p><span style="color:green;"><strong>Option 2:</strong></span></p>
</div>
<p><span style="display: block; margin-bottom: 48px;"></span></p>
<div class="fragment" data-fragment-index="3">
<p><span style="color:purple;"><strong>Option 3:</strong></span></p>
</div>
</div><div class="column" style="width:85%;">
<div class="fragment" data-fragment-index="1">
<p>Get all warehousing space from the <strong>spot market</strong> as needed.</p>
</div>
<div class="fragment" data-fragment-index="2">
<p>Sign a <strong>three-year lease</strong> for a fixed amount of warehouse space and get additional requirements from the spot market.</p>
</div>
<div class="fragment" data-fragment-index="3">
<p>Sign a <strong>flexible lease</strong> with a minimum charge that allows variable usage of warehouse space up to a limit with additional requirement from the spot market.</p>
</div>
</div></div>
<div style="font-size:95%;">
<ul>
<li class="fragment">r = 10%</li>
<li class="fragment">Revenue = $1.22/unit</li>
<li class="fragment">Lease price = $1/sq.ft/year</li>
<li class="fragment">1000 sq.ft is required for every 1000 units of demand</li>
<li class="fragment">Demand (D) = 100,000 units/year can go up/down by 20% with equal probability</li>
<li class="fragment">Spot market price (P) = $1.2/sq.ft/year can go up/down by 10% with equal probability</li>
<li class="fragment">Prices of warehouse space and demand for product fluctuate <em>independently</em>; thus, 𝑃(𝐴∩𝐵)=𝑃(𝐴)𝑃(𝐵).</li>
</ul>
</div>
</section>
<section class="slide level2">

<h5 id="construct-the-decision-tree-for-demand-and-spot-price-uncertainty-period-0-period-1">Construct the decision tree for demand and spot price uncertainty (Period 0 → Period 1)</h5>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 15,
    "nodeSpacing": 15,
    "rankSpacing": 100
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
  }
}}%%

flowchart LR

%% ----- Period 0 -----
subgraph P0["Period 0"]
A["D=100k&lt;br/&gt;p=$1.2"]
end

%% ----- Period 1 -----
subgraph P1["Period 1"]
B["D = 100(1.2) = 120&lt;br/&gt;&lt;br/&gt; P = 1.2(1.1) = $1.32"]
C["D = _________________&lt;br/&gt;&lt;br/&gt; P = _________________"]
D["D = _________________&lt;br/&gt;&lt;br/&gt; P = _________________"]
E["D = _________________&lt;br/&gt;&lt;br/&gt; P = _________________"]
end



%% Transitions
A --&gt;|"(0.5)(0.5)=0.25"| B
A --&gt;|0.25| C
A --&gt;|0.25| D
A --&gt;|0.25| E




%% Subgraph background (white)
style P0 fill:#ffffff,stroke:#ffffff
style P1 fill:#ffffff,stroke:#ffffff

style A fill:#ffffff;
style B fill:#f8d7da;
style C fill:#cfe2ff,color:#cfe2ff;
style D fill:#fff3cd,color:#fff3cd;
style E fill:#d1e7dd,color:#d1e7dd;
  
classDef default stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h5 id="construct-the-decision-tree-for-demand-and-spot-price-uncertainty-period-0-period-1-1">Construct the decision tree for demand and spot price uncertainty (Period 0 → Period 1)</h5>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 15,
    "nodeSpacing": 25,
    "rankSpacing": 100
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
  }
}}%%

flowchart LR

%% ----- Period 0 -----
subgraph P0["Period 0"]
A["D=100k&lt;br/&gt;p=$1.2"]
end

%% ----- Period 1 -----
subgraph P1["Period 1"]
B["D = 120&lt;br/&gt;P = $1.32"]
C["D = 120&lt;br/&gt;P = $1.08"]
D["D = 80&lt;br/&gt;P = $1.32"]
E["D = 80&lt;br/&gt;P = $1.08"]
end



%% Transitions
A --&gt;|"0.25"| B
A --&gt;|0.25| C
A --&gt;|0.25| D
A --&gt;|0.25| E




%% Subgraph background (white)
style P0 fill:#ffffff,stroke:#ffffff
style P1 fill:#ffffff,stroke:#ffffff

style A fill:#ffffff;
style B fill:#f8d7da;
style C fill:#cfe2ff;
style D fill:#fff3cd;
style E fill:#d1e7dd;
  
classDef default stroke:#000000,color:#000000;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h5 id="construct-the-decision-tree-for-demand-and-spot-price-uncertainty-period-1-period-2">Construct the decision tree for demand and spot price uncertainty (Period 1 → Period 2)</h5>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 15,
    "nodeSpacing": 50,
    "rankSpacing": 200
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
  }
}}%%

flowchart LR

%% ----- Period 0 -----
subgraph P0["Period 0"]
A["D=100k&lt;br/&gt;p=$1.2"]
end

%% ----- Period 1 -----
subgraph P1["Period 1"]
B["D = 120&lt;br/&gt;P = $1.32"]
C[" "]
D[" "]
E[" "]
end

%% ----- Period 2 -----
subgraph P2["Period 2"]
F["D = ______________&lt;br/&gt;P = ______________"]
G["D = ______________&lt;br/&gt;P = ______________"]
H["D = ______________&lt;br/&gt;P = ______________"]
I["D = ______________&lt;br/&gt;P = ______________"]
end

%% Transitions
A --&gt;|"0.25"| B
A --&gt;|0.25| C
A --&gt;|0.25| D
A --&gt;|0.25| E

B --&gt;|0.25| F
B --&gt;|0.25| G
B --&gt;|0.25| H
B --&gt;|0.25| I

%% Subgraph background (white)
style P0 fill:#ffffff,stroke:#ffffff
style P1 fill:#ffffff,stroke:#ffffff
style P2 fill:#ffffff,stroke:#ffffff

style B fill:#f8d7da;
style C fill:#cfe2ff,color:#cfe2ff;
style D fill:#fff3cd,color:#fff3cd;
style E fill:#d1e7dd,color:#d1e7dd;
style F color:#ffffff;
style G color:#ffffff;
style H color:#ffffff;
style I color:#ffffff;
  
classDef default stroke:#000000,color:#000000, fill:#ffffff;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h5 id="construct-the-decision-tree-for-demand-and-spot-price-uncertainty-period-1-period-2-1">Construct the decision tree for demand and spot price uncertainty (Period 1 → Period 2)</h5>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "flowchart": {
    "htmlLabels": true,
    "padding": 15,
    "nodeSpacing": 50,
    "rankSpacing": 200
  },
  "theme": "base",
  "themeVariables": {
    "fontSize": "22px",
    "secondaryColor": "#ffffff",
  }
}}%%

flowchart LR

%% ----- Period 0 -----
subgraph P0["Period 0"]
A["D=100k&lt;br/&gt;p=$1.2"]
end

%% ----- Period 1 -----
subgraph P1["Period 1"]
B["D = 120&lt;br/&gt;P = $1.32"]
C[" "]
D[" "]
E[" "]
end

%% ----- Period 2 -----
subgraph P2["Period 2"]
F["D = 144&lt;br/&gt;P = $1.45"]
G["D = 144&lt;br/&gt;P = $1.19"]
H["D = 96&lt;br/&gt;P = $1.45"]
I["D = 96&lt;br/&gt;P = $0.97"]
end

%% Transitions
A --&gt;|"0.25"| B
A --&gt;|0.25| C
A --&gt;|0.25| D
A --&gt;|0.25| E

B --&gt;|0.25| F
B --&gt;|0.25| G
B --&gt;|0.25| H
B --&gt;|0.25| I

%% Subgraph background (white)
style P0 fill:#ffffff,stroke:#ffffff
style P1 fill:#ffffff,stroke:#ffffff
style P2 fill:#ffffff,stroke:#ffffff

style B fill:#f8d7da;
style C fill:#cfe2ff,color:#cfe2ff;
style D fill:#fff3cd,color:#fff3cd;
style E fill:#d1e7dd,color:#d1e7dd;
  
classDef default stroke:#000000,color:#000000, fill:#ffffff;
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h5 id="construct-the-decision-tree-for-demand-and-spot-price-uncertainty-for-two-periods">Construct the decision tree for demand and spot price uncertainty for two periods</h5>
<div class="center">
<p><img data-src="figs/dts.png" style="width:75.0%"></p>
</div>
</section>
<section class="slide level2 scrollable">

<p><strong>Option 1:</strong> Get all warehousing space from the spot market as needed.</p>
<ol type="1">
<li class="fragment">Calculate payoff at Period 2</li>
</ol>
<div class="fragment" style="font-size: 85%">
<table class="table-striped caption-top" style="width:58%;">
<caption>Table 1. Profit (payoff) at Period 2 for Option 1 in 1000s.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Demand (D)</th>
<th style="text-align: right;">Spot Price (P)</th>
<th style="text-align: right;">Revenue (1.22 x D)</th>
<th style="text-align: right;">Cost (D × P)</th>
<th style="text-align: right;">Profit (R - C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">208.80</td>
<td style="text-align: right;">-33.12</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">171.36</td>
<td style="text-align: right;">4.32</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">139.68</td>
<td style="text-align: right;">36.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">139.20</td>
<td style="text-align: right;">-22.08</td>
</tr>
<tr class="odd">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">114.24</td>
<td style="text-align: right;">2.88</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">93.12</td>
<td style="text-align: right;">24.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">92.80</td>
<td style="text-align: right;">-14.72</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">76.16</td>
<td style="text-align: right;">1.92</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">62.08</td>
<td style="text-align: right;">16.00</td>
</tr>
</tbody>
</table>
</div>
<p><span class="space-out"></span></p>

<aside><div>
<p>Demands and spot prices are from the decision tree.</p>
</div></aside></section>
<section class="slide level2 scrollable">

<div style="font-size: 85%;">
<ol start="2" type="1">
<li>Calculate <span class="math inline">\(EMV_2\)</span> for each node at Period 1, where <span class="math inline">\(EMV_2 = \sum(\text{Probability} \times \text{Profit}_2)\)</span></li>
</ol>
</div>
<div class="columns" style="font-size: 83%">
<div class="column" style="width:30%;">
<div class="fragment">
<table class="table-striped caption-top">
<caption>Table 2. Expected value (EV) of Each Terminal Node</caption>
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;">Profit</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-33.12</td>
<td style="text-align: right;">-8.28</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">4.32</td>
<td style="text-align: right;">1.08</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">36.00</td>
<td style="text-align: right;">9.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-22.08</td>
<td style="text-align: right;">-5.52</td>
</tr>
<tr class="odd">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">2.88</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">6.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-14.72</td>
<td style="text-align: right;">-3.68</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: right;">0.48</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">4.00</td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:70%;">
<ul>
<li class="fragment">For each terminal node, calculate EV.</li>
<li class="fragment">Sum the corresponding EVs to get <span class="math inline">\(EMV_2\)</span>.</li>
<li class="fragment"><strong>Example.</strong> Red Node <span class="math inline">\((D = 120, P = \$1.32)\)</span>:</li>
</ul>
<div class="fragment">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init:{'flowchart':{'nodeSpacing': 10, 'rankSpacing': 40}}}%%
flowchart LR

subgraph P1["Period 1"]
A["D=120&lt;br/&gt;p=$1.32"]
end

subgraph P2["Period 2"]
B["D=144&lt;br/&gt;p=$1.45"]
C["D=144&lt;br/&gt;p=$1.19"]
D["D=96&lt;br/&gt;p=$1.45"]
E["D=96&lt;br/&gt;p=$1.19"]
end

A --&gt;|0.25| B
A --&gt;|0.25| C
A --&gt;|0.25| D
A --&gt;|0.25| E

B --&gt; F(["Profit = -33.12&lt;br/&gt;EV = 0.25x-33.12 = -8.28"])
C --&gt; G(["Profit = 4.32&lt;br/&gt;EV = 0.25x4.32 = 1.08"])
D --&gt; H(["Profit = -22.08&lt;br/&gt;EV = 0.25x-22.08 = -5.52"])
E --&gt; I(["Profit = 2.88&lt;br/&gt;EV = 0.25x2.88 = 0.72"])


style P1 fill:#ffffff,stroke:#ffffff
style P2 fill:#ffffff,stroke:#ffffff

style A fill:#f8d7da;
style B fill:#ffffff;
style C fill:#ffffff;
style D fill:#ffffff;
style E fill:#ffffff;
style F fill:#ffffff,stroke:#ffffff;
style G fill:#ffffff,stroke:#ffffff;
style H fill:#ffffff,stroke:#ffffff;
style I fill:#ffffff,stroke:#ffffff;

linkStyle default stroke:#000,stroke-width:2px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<ul>
<li class="fragment"><strong>Red Node:</strong> <span class="math inline">\(EMV_2\)</span> = -8.28 + 1.08 - 5.52 + 0.72 = -12.00</li>
</ul>
</div></div>
</section>
<section class="slide level2">

<div style="font-size: 83%">
<p><strong>Exercise:</strong> Calculate <span class="math inline">\(EMV_2\)</span> for the blue node <span class="math inline">\((D = 120, P = \$1.08)\)</span>.</p>
</div>
<div class="columns" style="font-size: 83%">
<div class="column" style="width:35%;">
<table class="table-striped caption-top">
<caption>Table 3. Expected value (EV) at Period 2 for Each Terminal Node</caption>
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;">Profit</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-33.12</td>
<td style="text-align: right;">-8.28</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">4.32</td>
<td style="text-align: right;">1.08</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">36.00</td>
<td style="text-align: right;">9.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-22.08</td>
<td style="text-align: right;">-5.52</td>
</tr>
<tr class="odd">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">2.88</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">6.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-14.72</td>
<td style="text-align: right;">-3.68</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: right;">0.48</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">4.00</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:60%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init:{'flowchart':{'nodeSpacing': 15, 'rankSpacing': 40, 'curve': 'basis', 'layout': 'elk'}}}%%
flowchart LR

subgraph P1["Period 1"]
A["D=120&lt;br/&gt;p=$1.08"]
end

subgraph P2["Period 2"]
B["D=144&lt;br/&gt;p=$1.19"]
C["D=144&lt;br/&gt;p=$0.97"]
D["D=96&lt;br/&gt;p=$1.19"]
E["D=96&lt;br/&gt;p=$0.97"]
end

A --&gt;|0.25| B
A --&gt;|0.25| C
A --&gt;|0.25| D
A --&gt;|0.25| E

B --&gt; F([" "])
C --&gt; G([" "])
D --&gt; H([" "])
E --&gt; I([" "])

style P1 fill:#ffffff,stroke:#ffffff
style P2 fill:#ffffff,stroke:#ffffff

style B fill:#ffffff;
style C fill:#ffffff;
style D fill:#ffffff;
style E fill:#ffffff;
style F fill:#ffffff,stroke:#ffffff;
style G fill:#ffffff,stroke:#ffffff;
style H fill:#ffffff,stroke:#ffffff;
style I fill:#ffffff,stroke:#ffffff;

linkStyle default stroke:#000,stroke-width:2px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Blue Node <span class="math inline">\(EMV_2\)</span> =</p>
<p>Yellow Node <span class="math inline">\(EMV_2\)</span> =</p>
<p>Green Node <span class="math inline">\(EMV_2\)</span> =</p>
</div></div>
</section>
<section class="slide level2 scrollable">

<ol start="3" type="1">
<li class="fragment">Calculate Total EMV at Period 1</li>
</ol>
<div class="fragment" style="font-size: 85%">
<div class="center" style="color:blue;">
<p>P1 Nodes <span class="math inline">\(\;\;\)</span> Step 2 <span class="math inline">\(\quad\)</span> /1.1 <span class="math inline">\(\;\;\)</span> 1.22 x D <span class="math inline">\(\;\;\)</span> D x P <span class="math inline">\(\;\;\)</span> Payoff <span class="math inline">\(\;\)</span> x0.25</p>
</div>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;"><span class="math inline">\(EMV_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_1\)</span></th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">120</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">-12.00</td>
<td style="text-align: right;">-10.91</td>
<td style="text-align: right;">146.40</td>
<td style="text-align: right;">158.40</td>
<td style="text-align: right;">-22.91</td>
<td style="text-align: right;">-5.73</td>
</tr>
<tr class="even">
<td style="text-align: right;">120</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">16.80</td>
<td style="text-align: right;">15.27</td>
<td style="text-align: right;">146.40</td>
<td style="text-align: right;">129.60</td>
<td style="text-align: right;">32.07</td>
<td style="text-align: right;">8.02</td>
</tr>
<tr class="odd">
<td style="text-align: right;">80</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">-8.00</td>
<td style="text-align: right;">-7.27</td>
<td style="text-align: right;">97.60</td>
<td style="text-align: right;">105.60</td>
<td style="text-align: right;">-15.27</td>
<td style="text-align: right;">-3.82</td>
</tr>
<tr class="even">
<td style="text-align: right;">80</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">11.20</td>
<td style="text-align: right;">10.18</td>
<td style="text-align: right;">101.82</td>
<td style="text-align: right;">86.40</td>
<td style="text-align: right;">21.38</td>
<td style="text-align: right;">5.35</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
EMV_\text{Period 1} = -5.73 + 8.02 - 3.82 + 5.35 = \textbf{3.82}
\]</span></p>
</div>
<ol start="4" type="1">
<li class="fragment">Calculate NPV</li>
</ol>
<div class="fragment" style="font-size: 85%">
<div class="center" style="color:blue;">
<p>P0 Node <span class="math inline">\(\;\;\)</span> Step 3 <span class="math inline">\(\quad\)</span> /1.1 <span class="math inline">\(\;\;\)</span> 1.22 x D <span class="math inline">\(\;\;\)</span> D x P <span class="math inline">\(\;\;\)</span> NPV</p>
</div>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;"><span class="math inline">\(EMV_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_0\)</span></th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">3.82</td>
<td style="text-align: right;">3.47</td>
<td style="text-align: right;">122.00</td>
<td style="text-align: right;">120.00</td>
<td style="text-align: right;">5.47</td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<div class="center">
<ul>
<li class="fragment">The NPV for option 1 is <strong>$5,471.07</strong> (if calculate exactly up to 2 decimal places)</li>
</ul>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<p><strong>Option 2:</strong> Sign a 3-year lease for 100,000 sq.ft. for $1/sq.ft. and obtain extra on spot market if needed.</p>
<div style="font-size: 85%">
<ol type="1">
<li class="fragment">Calculate payoff at Period 2</li>
</ol>
<div class="fragment">
<p>The total cost for this option is 100k lease + extra warehouse cost.</p>
<p><span class="math display">\[
\text{Cost} = 100 + \text{max}(0, D - 100) \times P \quad \text{(in 1000s)}
\]</span></p>
</div>
<div class="fragment">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">163.80</td>
<td style="text-align: right;">11.88</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">152.36</td>
<td style="text-align: right;">23.32</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">142.68</td>
<td style="text-align: right;">33.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">17.12</td>
</tr>
<tr class="odd">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">17.12</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">17.12</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">-21.92</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">-21.92</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">-21.92</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<div style="font-size:83%">
<div class="columns">
<div class="column" style="width:29%;">
<ol start="2" type="1">
<li class="fragment">Calculate <span class="math inline">\(EMV_2\)</span> for each node at Period 1</li>
</ol>
<div class="fragment">
<p><img data-src="figs/dts2.png" style="width:90.0%"></p>
</div>
</div><div class="column" style="width:71%;">
<ul>
<li class="fragment">For each terminal node, calculate EV.</li>
<li class="fragment">Sum the corresponding EVs to get EMV for each node at Period 1.</li>
</ul>
<div class="fragment">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;">Profit (Payoff)</th>
<th style="text-align: right;">EV = Payoff x 0.25</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">11.88</td>
<td style="text-align: right;">2.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">23.32</td>
<td style="text-align: right;">5.83</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">33.00</td>
<td style="text-align: right;">8.25</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">17.12</td>
<td style="text-align: right;">4.28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">17.12</td>
<td style="text-align: right;">4.28</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">17.12</td>
<td style="text-align: right;">4.28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">-21.92</td>
<td style="text-align: right;">-5.48</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">-21.92</td>
<td style="text-align: right;">-5.48</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">-21.92</td>
<td style="text-align: right;">-5.48</td>
</tr>
</tbody>
</table>
</div>
</div></div>
<div class="center">
<ul>
<li class="fragment"><strong>Red Node</strong> <span class="math inline">\(EMV_2\)</span> = 2.97 + 5.83 + 4.28 + 4.28 = 17.36</li>
<li class="fragment"><strong>Blue Node</strong> <span class="math inline">\(EMV_2\)</span> = 5.83 + 8.25 + 4.28 + 4.28 = 22.64</li>
<li class="fragment"><strong>Yellow Node</strong> <span class="math inline">\(EMV_2\)</span> = 4.28 + 4.28 + -5.48 - 5.48 = -2.40</li>
<li class="fragment"><strong>Green Node</strong> <span class="math inline">\(EMV_2\)</span> = 4.28 + 4.28 - 5.48 - 5.48 = -2.40</li>
</ul>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<ol start="3" type="1">
<li class="fragment">Calculate <span class="math inline">\(EMV_1\)</span> at Period 1</li>
</ol>
<div class="fragment" style="font-size: 85%">
<div class="center" style="color:blue;">
<p>P1 Nodes <span class="math inline">\(\;\)</span> Step 2 <span class="math inline">\(\;\;\)</span> /1.1 <span class="math inline">\(\;\)</span> 1.22 x D <span class="math inline">\(\;\)</span> 100+extra <span class="math inline">\(\;\)</span> Payoff <span class="math inline">\(\;\)</span> x0.25</p>
</div>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;"><span class="math inline">\(EMV_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_1\)</span></th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">120</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">17.36</td>
<td style="text-align: right;">15.78</td>
<td style="text-align: right;">146.40</td>
<td style="text-align: right;">126.40</td>
<td style="text-align: right;">35.78</td>
<td style="text-align: right;">8.94</td>
</tr>
<tr class="even">
<td style="text-align: right;">120</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">22.64</td>
<td style="text-align: right;">20.58</td>
<td style="text-align: right;">146.40</td>
<td style="text-align: right;">121.60</td>
<td style="text-align: right;">45.38</td>
<td style="text-align: right;">11.34</td>
</tr>
<tr class="odd">
<td style="text-align: right;">80</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">-2.40</td>
<td style="text-align: right;">-2.18</td>
<td style="text-align: right;">97.60</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">-4.58</td>
<td style="text-align: right;">-1.14</td>
</tr>
<tr class="even">
<td style="text-align: right;">80</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">-2.40</td>
<td style="text-align: right;">-2.18</td>
<td style="text-align: right;">97.60</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">-4.58</td>
<td style="text-align: right;">-1.14</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
EMV_\text{Period 1} = 8.94 + 11.34 - 1.14 - 1.14 = \textbf{18.00}
\]</span></p>
</div>
<ol start="4" type="1">
<li class="fragment">Calculate NPV</li>
</ol>
<div class="fragment" style="font-size: 80%">
<div class="center" style="color:blue;">
<p>P0 Node <span class="math inline">\(\;\)</span> Step 3 <span class="math inline">\(\;\;\)</span> /1.1 <span class="math inline">\(\;\)</span> 1.22 x D <span class="math inline">\(\;\)</span> 100+extra <span class="math inline">\(\;\)</span> NPV</p>
</div>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;"><span class="math inline">\(EMV_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_0\)</span></th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: right;">16.36</td>
<td style="text-align: right;">122.00</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">38.36</td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<div class="center">
<ul>
<li class="fragment">The NPV for option 2 is <strong>$38,363.64</strong> (if calculate exactly up to 2 decimal places)</li>
</ul>
</div>
</div>
</section>
<section class="slide level2">

<div style="font-size: 85%;">
<p><strong>Option 3:</strong> Sign a flexible lease with a minimum charge of $10,000, the company has</p>
<ul>
<li class="fragment"><p>Flexibility of using between 60,000 and 100,000 sq.ft of warehouse space at $1/sq.ft./year.</p></li>
<li class="fragment"><p>Pay $60,000/year for the first 60,000 sq.ft. and can then use up to another 40,000 sq.ft. on demand of $1/sq.ft.</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\text{Cost} = \min(100000, D) \times \$1 + \max(0, D-100000) \times P.
\]</span></p>
</div>
<div class="fragment">
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">100 + 44 x 1.45 = 163.80</td>
<td style="text-align: right;">11.88</td>
<td style="text-align: right;">2.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">100 + 44 x 1.19 = 152.36</td>
<td style="text-align: right;">23.32</td>
<td style="text-align: right;">5.83</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">175.68</td>
<td style="text-align: right;">100 + 44 x 0.97 = 142.68</td>
<td style="text-align: right;">33.00</td>
<td style="text-align: right;">8.25</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">21.12</td>
<td style="text-align: right;">5.28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">21.12</td>
<td style="text-align: right;">5.28</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">117.12</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">21.12</td>
<td style="text-align: right;">5.28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">14.08</td>
<td style="text-align: right;">3.52</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">14.08</td>
<td style="text-align: right;">3.52</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">14.08</td>
<td style="text-align: right;">3.52</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section class="slide level2">

<div class="fragment" style="font-size: 90%">
<div class="center" style="color:blue;">
<p>P1 Nodes <span class="math inline">\(\;\;\)</span> Step 2 <span class="math inline">\(\;\;\)</span> /1.1 <span class="math inline">\(\;\;\)</span> 1.22 x D <span class="math inline">\(\;\;\)</span> flexible <span class="math inline">\(\;\;\)</span> Payoff <span class="math inline">\(\;\)</span> x0.25</p>
</div>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;"><span class="math inline">\(EMV_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_1\)</span></th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">120</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">19.36</td>
<td style="text-align: right;">17.60</td>
<td style="text-align: right;">146.40</td>
<td style="text-align: right;">126.40</td>
<td style="text-align: right;">37.60</td>
<td style="text-align: right;">9.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">120</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">24.64</td>
<td style="text-align: right;">22.40</td>
<td style="text-align: right;">146.40</td>
<td style="text-align: right;">121.60</td>
<td style="text-align: right;">47.20</td>
<td style="text-align: right;">11.80</td>
</tr>
<tr class="odd">
<td style="text-align: right;">80</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">17.60</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">97.60</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;">33.60</td>
<td style="text-align: right;">8.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">80</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">17.60</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">97.60</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;">33.60</td>
<td style="text-align: right;">8.40</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
EMV_\text{Period 1} = 9.40 + 11.80 + 8.40 + 8.40 = \textbf{38.00}
\]</span></p>
</div>
<p><br></p>
<div class="fragment" style="font-size:90%">
<div class="center" style="color:blue;">
<p><span class="math inline">\(\;\;\)</span> P0 Node <span class="math inline">\(\;\)</span> Step 3 <span class="math inline">\(\;\;\)</span> /1.1 <span class="math inline">\(\;\)</span> 1.22 x D <span class="math inline">\(\;\)</span> 100+upfront <span class="math inline">\(\,\)</span> NPV</p>
</div>
<table class="table-striped caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">D</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;"><span class="math inline">\(EMV_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(PV_0\)</span></th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">38.00</td>
<td style="text-align: right;">34.55</td>
<td style="text-align: right;">122.00</td>
<td style="text-align: right;">110.00</td>
<td style="text-align: right;">46.55</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="center">
<p>The NPV for option 3 is <strong>$46,545.45</strong> (if calculate exactly up to 2 decimal places)</p>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h5 id="target.com-comparison-of-lease-options">Target.com Comparison of Lease Options</h5>
<p><br></p>
<div style="font-size:85%">
<table class="table-striped caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 24%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Option 0<br>ignore uncertainty</th>
<th style="text-align: center;">Option 1<br>spot market only</th>
<th style="text-align: center;">Option 2<br>lease 100k + spot</th>
<th style="text-align: center;">Option 3<br>flexible lease + spot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>NPV</strong></td>
<td style="text-align: center;">60,181.82</td>
<td style="text-align: center;">5,471.07</td>
<td style="text-align: center;">38,363.64</td>
<td style="text-align: center;">46,545.45</td>
</tr>
</tbody>
</table>
<p><span class="space-out"></span></p>
<ul>
<li class="fragment">Option 0 (from section 3.5.3) has highest NPV but it underestimates all the fluctuations in demands and costs.</li>
<li class="fragment">Option 3 yields highest NPV and would be the best option for Target.com.</li>
</ul>
</div>
<div class="fragment" style="font-size:1.2em;">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Steps to Solve a Decision Tree Problem</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li class="fragment">Identify all options and information</li>
<li class="fragment">Construct the decision tree representing all possible outcomes and decisions</li>
<li class="fragment">Calculate EMV starting from the terminal nodes to the root node</li>
<li class="fragment">Calculate NPV for each option and compare</li>
</ol>
</div>
</div>
</div>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="figs/curtin-logo2.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="04lecture_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="04lecture_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="04lecture_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="04lecture_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"titleSelector":"h1, h2, h3","hideMissingTitles":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>