{
  "hash": "a48e5aa4fe9ecccb0fb1451ffacefe1a",
  "result": {
    "engine": "jupyter",
    "markdown": "# Tutorial 2 Solutions {#02sols .unnumbered}\n\n### Question 1\n\nWith precisely 2700 sq. cm. of cardboard, you wish to construct a box (width: $x$, depth: $y$, height: $z$) containing a volume $V$. You require the width to double its depth. You would like to maximise the volume of the box. Which values of $x, y, z$ will maximise the volume?\n\n::: {.example}\n1. **Construct the objective function and constraints**: \n\n$$\n\\begin{aligned}\n\\max\\; &f(x,y,z) = xyz \\\\\n\\text{st:} \\quad\n&x = 2y \\\\\n&2(xy + xz + yz) = 2700 \\\\\n&x, y, z \\ge 0\n\\end{aligned}\n$$\n\n&emsp;&emsp;Convert the maximisation problem to a minimisation problem in the standard form:\n\n$$\n\\begin{aligned}\n\\min\\; &f(x,y,z) = -xyz \\\\\n\\text{st:} \\quad\n&x - 2y = 0 \\\\\n&2(xy + xz + yz) - 2700 = 0 \\\\\n&-x, -y, -z \\le 0\n\\end{aligned}\n$$\n\n\n2. **Set up a Lagrangian function**\n\n$$\n\\begin{aligned}\nL(x,y,z,\\lambda_1,\\lambda_2,\\mu_1, \\mu_2, \\mu_3)\n = xyz &+ \\lambda_1(2(xy + xz + yz) - 2700) \\\\\n       &+ \\lambda_2(x-2y) \\\\\n       &+ \\mu_1 x + \\mu_2 y +\\mu_3 z\n\\end{aligned}\n$$\n\nSince the optimum has $x,y,z>0,$ the non-negativity constraints are not binding, so $\\mu_1=\\mu_2=\\mu_3=0$. Therefore,\n\n$$\n\\begin{aligned}\nL(x,y,z,\\lambda_1,\\lambda_2,\\mu_1, \\mu_2, \\mu_3)\n = xyz &+ \\lambda_1(2(xy + xz + yz) - 2700) \\\\\n       &+ \\lambda_2(x-2y)\n\\end{aligned}\n$$\n\nFrom this, KKT's dual feasibility and complementary slackness conditions are satisfied, so we can proceed to the stationarity and primal feasibility conditions.\n\n2. **KKT's stationarity**\n\nSolve for partial derivatives and set them equal to 0:\n\n$$\n\\begin{aligned}\nL_x &= yz - 2\\lambda_1(y+z) - \\lambda_2 + \\mu_1 = 0 \\\\\nL_y &= xz - 2\\lambda_1(x+z) + 2\\lambda_2 + \\mu_2 = 0 \\\\\nL_z &= xy - 2\\lambda_1(x+y) + \\mu_3 = 0 \\\\\nL_{\\lambda_1} &= 2(xy + xz + yz) - 2700 = 0 \\\\\nL_{\\lambda_2} &= x - 2y = 0 \\\\\n\\end{aligned}\n$$\n\nFrom $L_{\\lambda_2}$,\n\n$$\nx = 2y\n$$\n\nFrom $L_{\\lambda_1}$, substitute $x=2y$:\n\n$$\n2(2y^2+2yz+yz)=2700\n$$\n\n$$\n4y^2+6yz=2700\n$$\n\nSolve for $z$:\n\n$$\nz=\\frac{2700-4y^2}{6y}= \\frac{450}{y}-\\frac{2y}{3}\n$$\n\nVolume:\n\n$$\nV=xyz=(2y)(y)(z)=2y^2z\n$$\n\nSubstitute $z$:\n\n$$\nV(y)=2y^2\\left(\\frac{450}{y}-\\frac{2y}{3}\\right)\n=900y-\\frac{4}{3}y^3\n$$\n\nDifferentiate and set it equal to 0:\n\n$$\n\\begin{aligned}\nV'(y)=900-4y^2&=0 \\\\\ny^2&=225 \\\\\ny&=15\n\\end{aligned}\n$$\n\nThen:\n\n$$\nx=2y=30\n$$\n\n$$\nz=\\frac{450}{15}-\\frac{2(15)}{3}=30-10=20\n$$\n\nSo the optimal dimensions are:\n\n$$\n\\boxed{x=30,\\quad y=15,\\quad z=20}\n$$\n\n3. **Verify KKT's primal feasibility**\n\nSubstitute the optimal dimensions into the constraints $L_{\\lambda_1}$ and $L_{\\lambda_2}$:\n\n$$\nL_{\\lambda_1} = 2(2(15)^2+2(15)(20)+(15)(20)) - 2700 = 0 \\quad \\text{(Satisfied)}\n$$\n\n$$\nL_{\\lambda_2} = 30 - 2(15) = 0 \\quad \\text{(Satisfied)}\n$$\n\n4. **Calculate the maximum volume**\n\n$$\nV=30(15)(20)=\\boxed{9000\\text{ cm}^3}\n$$\n\n:::\n\n::: {#418f925a .cell execution_count=1}\n``` {.python .cell-code}\nimport sympy as sp\n\n# Variables\nx, y, z = sp.symbols(\"x y z\", positive=True)\nlambda1, lambda2 = sp.symbols(\"lambda1 lambda2\")\n\n# Objective and constraints\nV = x * y * z\ng1 = 2 * (x*y + x*z + y*z) - 2700\ng2 = x - 2*y\n\n# Lagrangian\nL = V - lambda1 * g1 - lambda2 * g2\n\n# First-order conditions\nequations = [\n    sp.diff(L, x),\n    sp.diff(L, y),\n    sp.diff(L, z),\n    g1,\n    g2,\n]\n\nsolution = sp.solve(\n    equations,\n    [x, y, z, lambda1, lambda2],\n    dict=True\n)\n\nprint(\"Solutions:\")\nfor sol in solution:\n    print(sol)\n\n# Keep positive real solution\npositive_solutions = [\n    sol for sol in solution\n    if sol[x].is_real and sol[y].is_real and sol[z].is_real\n    and sol[x] > 0 and sol[y] > 0 and sol[z] > 0\n]\n\nbest = max(positive_solutions, key=lambda sol: V.subs(sol))\n\nprint(\"\\nOptimal dimensions:\")\nprint(f\"x = {sp.simplify(best[x])} = {float(best[x]):.4f} cm\")\nprint(f\"y = {sp.simplify(best[y])} = {float(best[y]):.4f} cm\")\nprint(f\"z = {sp.simplify(best[z])} = {float(best[z]):.4f} cm\")\n\nprint(\"\\nMaximum volume:\")\nprint(f\"V = {sp.simplify(V.subs(best))} = {float(V.subs(best)):.4f} cubic cm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSolutions:\n{lambda1: 5, lambda2: -50, x: 30, y: 15, z: 20}\n\nOptimal dimensions:\nx = 30 = 30.0000 cm\ny = 15 = 15.0000 cm\nz = 20 = 20.0000 cm\n\nMaximum volume:\nV = 9000 = 9000.0000 cubic cm\n```\n:::\n:::\n\n\n---\n\n### Question 2\n\nA manufacturing facility produces four types of wood panelling: Tahoe, Pacific, Savannah, and Aspen. Each product is manufactured using pine chips and oak chips and requires both gluing and pressing processes.\n\nThe profit earned per pallet is as follows:\n\n- \\$450 for Tahoe,\n- \\$1140 for Pacific,\n- \\$800 for Savannah, and\n- \\$400 for Aspen.\n\nThe factory operates under limited resource availability. During the planning period, there are 5,800 quarts of glue available, 730 pressing machine hours, and 29,200 pounds of pine chips. In addition, the supply of oak chips is limited to a fixed total amount.\n\n|| Tahoe | Pacific | Savannah | Aspen | Capacity |\n|---|---|---|---|---|---|\n| Glueing (quarts) | 50 | 50 | 100 | 50 | 5800 quarts |\n| Pressing (hours) | 5 | 15 | 10 | 5 | 730 hours |\n| Pine chips (pounds) | 500 | 400 | 300 | 200 | 29200 pounds |\n| Oak chips (pounds) | 500 | 750 | 250 | 500 | 60500 pounds |\n| Profit per pallet (\\$) | 450 | 1150 | 800 | 400 | - |\n\nLet decision variables be $X_1,X_2,X_3,X_4$ (pallets of Tahoe, Pacific, Savannah, Aspen). Write down the optimisation model to maximise profit, and solve for the optimal production plan. What is the maximum profit?\n\n::: {.example}\n\n**Objective function:**\n\n$$\n\\max\\; 450x_1 + 1150x_2 + 800x_3 + 400x_4\n$$\n\n**Constraints:**\n\n$$\n\\begin{aligned}\n50x_1 + 50x_2 + 100x_3 + 50x_4 &\\le 5800 \\quad \\text{(Glueing)} \\\\\n5x_1 + 15x_2 + 10x_3 + 5x_4 &\\le 730 \\quad \\text{(Pressing)} \\\\\n500x_1 + 400x_2 + 300x_3 + 200x_4 &\\le 29200 \\quad \\text{(Pine chips)} \\\\\n500x_1 + 750x_2 + 250x_3 + 500x_4 &\\le 60500 \\quad \\text{(Oak chips)} \\\\\nx_1, x_2, x_3, x_4 &\\ge 0\n\\end{aligned}\n$$\n\nThis can be solved using KKT. However, it is usually not the preferred manual method for solving linear programming problems, especially with 4 variables. Instead, we can use the **Simplex method** or an **LP solver**.\n\n:::\n\n::: {#a6b9b993 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nfrom scipy.optimize import linprog\n\n# Maximise: 450x1 + 1150x2 + 800x3 + 400x4\n# linprog minimises, so use negative coefficients\nc = np.array([-450, -1150, -800, -400])\n\nA = np.array([\n    [50, 50, 100, 50],      # Glueing\n    [5, 15, 10, 5],         # Pressing\n    [500, 400, 300, 200],   # Pine chips\n    [500, 750, 250, 500]    # Oak chips\n])\n\nb = np.array([5800, 730, 29200, 60500])\n\nresult = linprog(\n    c,\n    A_ub=A,\n    b_ub=b,\n    bounds=[(0, None)] * 4,\n    method=\"highs\"\n)\n\nprint(result.x)\nprint(-result.fun)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[23. 15. 39.  0.]\n58800.0\n```\n:::\n:::\n\n\n**Optimal solution**\n\n$$\n\\boxed{x_10=23,\\quad x_2=15,\\quad x_3=39,\\quad x_4=0}\n$$\n\nSo the optimal production plan is:\n\n$$\n\\boxed{\\text{Tahoe: 23, Pacific: 15, Savannah: 39, Aspen: 0}}\n$$\n\nMaximum profit:\n\n$$\nZ=450(23)+1150(15)+800(39)+400(0)=\\boxed{58,800}\n$$\n\nResources used:\n\n$$\n\\begin{aligned}\n\\text{Glueing} &= 50(23)+50(15)+100(39)+50(0) = 5800\\\\\n\\text{Pressing} &= 5(23)+15(15)+10(39)+5(0) = 730\\\\\n\\text{Pine chips} &= 500(23)+400(15)+300(39)+200(0) = 29200\\\\\n\\text{Oak chips} &= 500(23)+750(15)+250(39)+500(0) = 32500\n\\end{aligned}\n$$\n\nSo all requirements are satisfied.\n\n\n---\n\n## Question 3\n\nConsider the problem of diet optimisation. There are four different types of food: Brownies, Ice Cream, Cola, and Cheese Cake. The nutrition values and cost per unit are as follows: \n\n\n| | Brownies | Ice Cream | Cola | Cheese Cake |\n|---|---|---|---|---|\n| Calories | 400 | 200 | 150 | 500 |\n| Chocolate | 3 | 2 | 0 | 0 |\n| Sugar | 2 | 2 | 4 | 4 |\n| Fat | 2 | 4 | 1 | 5 |\n| Cost (\\$) | \\$0.50 | \\$0.20 | \\$0.30 | \\$0.80 |\n\nThe objective is to minimise the cost of the diet while satisfying the following nutritional requirements:\n\n- At least 500 calories,\n- At least 6 units of chocolate,\n- At least 10 units of sugar, and\n- At least 8 units of fat.\n\nFormulate the optimisation model and solve for the optimal diet plan.\n\n\n::: {.example}\n**Objective function:**\n$$\n\\min\\; 0.50x_0+0.20x_1+0.30x_2+0.80x_3\n$$\n\n**Constraints:**\n$$\n\\begin{aligned}\n400x_0 + 200x_1 + 150x_2 + 500x_3 &\\ge 500,\\\\\n3x_0 + 2x_1 + 0x_2 + 0x_3 &\\ge 6,\\\\\n2x_0 + 2x_1 + 4x_2 + 4x_3 &\\ge 10,\\\\\n2x_0 + 4x_1 + 1x_2 + 5x_3 &\\ge 8,\\\\\nx_0,x_1,x_2,x_3 &\\ge 0.\n\\end{aligned}\n$$\n\n:::\n\n::: {#dc1bb7df .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nfrom scipy.optimize import linprog\n\n# Cost coefficients\nc = np.array([0.50, 0.20, 0.30, 0.80])\n\n# Nutrient matrix\nA = np.array([\n    [400, 200, 150, 500],  # Calories\n    [3,   2,   0,   0],    # Chocolate\n    [2,   2,   4,   4],    # Sugar\n    [2,   4,   1,   5]     # Fat\n])\n\n# Minimum requirements\nb = np.array([500, 6, 10, 8])\n\n# linprog uses <= constraints, so multiply by -1\nresult = linprog(\n    c,\n    A_ub=-A,\n    b_ub=-b,\n    bounds=[(0, None)] * 4,\n    method=\"highs\"\n)\n\nprint(result.x)\nprint(result.fun)\nprint(A @ result.x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[0. 3. 1. 0.]\n0.9000000000000001\n[750.   6.  10.  13.]\n```\n:::\n:::\n\n\n**Optimal solution**\n\n$$\n\\boxed{x_0=0,\\quad x_1=3,\\quad x_2=1,\\quad x_3=0}\n$$\n\nSo the optimal diet is:\n\n$$\n\\boxed{\\text{0 Brownies, 3 Ice Cream, 1 Cola, 0 Cheese Cake}}\n$$\n\nMinimum cost:\n\n$$\nZ=0.20(3)+0.30(1)=\\boxed{0.90}\n$$\n\nNutrients obtained:\n\n$$\n\\begin{aligned}\n\\text{Calories} &= 750\\\\\n\\text{Chocolate} &= 6\\\\\n\\text{Sugar} &= 10\\\\\n\\text{Fat} &= 13\n\\end{aligned}\n$$\n\nSo all requirements are satisfied.\n\n\n---\n\n## Question 4\n\nTowAlong makes trailers at Kansas City, Denver, and Raleigh plants and ships these units to Birmingham, Milwaukee, Los Angeles, and Seattle distribution centres. In planning production for the next year, TowAlong estimates Kansas City, Denver, and Raleigh plant’s unit shipping cost between any plant and distribution centre, plant capacities, and distribution centre demands. These numbers are given in the table.\n\n| Plant/DC | Birmingham | Milwaukee | LA | Seattle | Capacity |\n|---|---|---|---|---|---|\n| Kansas City | \\$35 | \\$40 | \\$60 | \\$120 | 12,000 |\n| Denver | \\$30 | \\$30 | \\$45 | \\$130 | 8,000 |\n| Raleigh | \\$60 | \\$65 | \\$50 | \\$100 | 5,000 |\n| Demand | 9,000 | 3,000 | 9,500 | 1,500 | - |\n\nFormulate the optimisation model to minimise the total shipping cost, and solve for the optimal shipping plan. What is the minimum total cost?\n\n::: {.example}\n**Objective function:**\n\n$$\n\\begin{aligned}\n\\min \\; &35x_{11} + 40x_{12} + 60x_{13} + 120x_{14} \\\\\n        &+ 30x_{21} + 30x_{22} + 45x_{23} + 130x_{24} \\\\\n        &+ 60x_{31} + 65x_{32} + 50x_{33} + 100x_{34}\n\\end{aligned}\n$$\n\n**Capacity constraints:**\n$$\n\\begin{aligned}\nx_{11}+x_{12}+x_{13}+x_{14} &\\le 12000 \\quad \\text{(Kansas City)}\\\\\nx_{21}+x_{22}+x_{23}+x_{24} &\\le 8000 \\quad \\text{(Denver)}\\\\\nx_{31}+x_{32}+x_{33}+x_{34} &\\le 5000 \\quad \\text{(Raleigh)}\n\\end{aligned}\n$$\n\n\n**Demand constraints:**\n$$\n\\begin{aligned}\nx_{11}+x_{21}+x_{31} &= 9000 \\quad \\text{(Birmingham)}\\\\\nx_{12}+x_{22}+x_{32} &= 3000 \\quad \\text{(Milwaukee)}\\\\\nx_{13}+x_{23}+x_{33} &= 9500 \\quad \\text{(Los Angeles)}\\\\\nx_{14}+x_{24}+x_{34} &= 1500 \\quad \\text{(Seattle)}\\\\\nx_{ij} &\\ge 0.\n\\end{aligned}\n$$\n\n:::\n\n::: {#4cf85f88 .cell execution_count=4}\n``` {.python .cell-code}\nimport numpy as np\nfrom scipy.optimize import linprog\n\n# Cost coefficients\n# Order:\n# x11, x12, x13, x14,\n# x21, x22, x23, x24,\n# x31, x32, x33, x34\n\nc = np.array([\n    35, 40, 60, 120,\n    30, 30, 45, 130,\n    60, 65, 50, 100\n])\n\n# Capacity constraints: <=\nA_ub = np.array([\n    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],  # Kansas City\n    [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0],  # Denver\n    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]   # Raleigh\n])\n\nb_ub = np.array([12000, 8000, 5000])\n\n# Demand constraints: =\nA_eq = np.array([\n    [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],  # Birmingham\n    [0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],  # Milwaukee\n    [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],  # Los Angeles\n    [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1]   # Seattle\n])\n\nb_eq = np.array([9000, 3000, 9500, 1500])\n\nbounds = [(0, None)] * 12\n\nresult = linprog(\n    c,\n    A_ub=A_ub,\n    b_ub=b_ub,\n    A_eq=A_eq,\n    b_eq=b_eq,\n    bounds=bounds,\n    method=\"highs\"\n)\n\nprint(result.success)\nprint(result.fun)\nprint(result.x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue\n1010000.0\n[9000. 1000.    0.    0.    0. 2000. 6000.    0.    0.    0. 3500. 1500.]\n```\n:::\n:::\n\n\n**Optimal solution:**\n\nPython returns variable order as:\n\n$$[x_{11},x_{12},x_{13},x_{14},x_{21},x_{22},x_{23},x_{24},x_{31},x_{32},x_{33},x_{34}]\n$$\n\n\nSo the optimal shipping plan is:\n\n| From / To   | Birmingham | Milwaukee | Los Angeles | Seattle | Supply Used |\n| ----------- | ---------: | --------: | ----------: | ------: | ----------: |\n| Kansas City |       9000 |      1000 |           0 |       0 |       10000 |\n| Denver      |          0 |      2000 |        6000 |       0 |        8000 |\n| Raleigh     |          0 |         0 |        3500 |    1500 |        5000 |\n\n**Demands:**\n\n\n$$\n\\begin{aligned}\n\\text{Birmingham} &= 9000\\\\\n\\text{Milwaukee} &= 1000+2000=3000\\\\\n\\text{Los Angeles} &= 6000+3500=9500\\\\\n\\text{Seattle} &= 1500\n\\end{aligned}\n$$\n\n**Minimum cost:**\n\n\n$$\n35(9000)+40(1000)+30(2000)+45(6000)+50(3500)+100(1500)\n$$\n\nSo:\n\n\n$$\n\\boxed{\\text{Minimum cost} = 1{,}010{,}000}\n$$\n\n\n---\n\n## Question 5\n\nSunchem, a manufacturer of printing inks, has five manufacturing plants worldwide. Their locations and capacities are shown in Table 4 along with the cost of producing 1 ton of ink at each facility. The production costs are in the local currency of the country where the plant is located. The major markets for the inks are North America, South America, Europe, Japan, and the rest of Asia. Demand at each market is shown in Table 4. Transportation costs from each plant to each market in U.S. dollars are shown in Table 4. Management must come up with a production plan for the next year.\n\n(a) If exchange rates are expected as in Table 2, and no plant can run below 50 percent of capacity, how much should each plant produce and which markets should each plant supply?\n(b) If there are no limits on the amount produced in a plant, how much should each plant produce?\n(c) Can adding 10 percent of capacity in any plant reduce costs?\n(d) How should Sunchem account for the fact that exchange rates fluctuate over time?\n\n| Supply Region | N. America | S. America | Europe | Japan | Asia | Capacity (tons/year) | Production cost/ton |\n|---|---|---|---|---|---|---|---|\n| USA | 600 | 1,200 | 1,300 | 2,000 | 1,700 | 185 | \\$10,000 |\n| GER | 1,300 | 1,400 | 600 | 1,400 | 1,300 | 475 | €15,000 |\n| JAP | 2,000 | 2,100 | 1,400 | 300 | 900 | 50 | ¥1,800,000 |\n| BRA | 1,200 | 800 | 1,400 | 2,100 | 2,100 | 210 | BRL13,000 |\n| IND | 2,200 | 2,300 | 1,300 | 1,000 | 800 | 80 | INR400,000 |\n\n: Table 1. Transportation costs, production capacity, and cost by region\n\n| | USD | EUR | JPY | BRL | INR |\n|---|---|---|---|---|---|\n| USD | 1.0000 | 0.8794 | 141.94 | 5.6336 | 85.282 |\n| EUR | 1.1374 | 1.0000 | 161.45 | 6.408 | 97.0 |\n| JPY | 0.0070 | 0.0062 | 1.0000 | 0.045 | 0.60 |\n| BRL | 0.1775 | 0.1560 | 22.22 | 1.0000 | 15.14 |\n| INR | 0.0117 | 0.0103 | 1.67 | 0.066 | 1.0000 |\n\n: Table 2. Exchange Rates as of April 2025\n\n::: {.example}\n**Sets**\n\n$$\n\\begin{aligned}\nI &= \\{\\text{US},\\text{DE},\\text{JP},\\text{BR},\\text{IN}\\} \\quad \\text{(plants)} \\\\\nJ &= \\{\\text{NA},\\text{SA},\\text{EU},\\text{JP},\\text{AS}\\} \\quad \\text{(markets)}\n\\end{aligned}\n$$\n\n**Parameters**\n\n- $D_j$ : demand in market $j$ (tons/year)\n- $K_i$ : capacity of plant $i$ (tons/year)\n- $c_{ij}$ : transportation cost from plant $i$ to market $j$ (USD/ton)\n- $p_i$ : production cost at plant $i$ (local currency/ton)\n- $r_i$ : USD per unit of local currency at plant $i$\n\n\nExchange rates (USD per local currency unit):\n\n$$\nr_{\\text{US}}=1,\\;\nr_{\\text{DE}}=1.1374,\\;\nr_{\\text{JP}}=0.0070,\\;\nr_{\\text{BR}}=0.1775,\\;\nr_{\\text{IN}}=0.0117\n$$\n\nDefine total unit delivered cost in USD:\n\n$$\nu_{ij} = r_i p_i + c_{ij}\n$$\n\n**Decision Variables**\n\n- $x_{ij}$ : tons shipped from plant $i$ to market $j$\n- $y_i = \\sum_{j\\in J} x_{ij}$ : total production at plant $i$\n\n**(a) Fixed Exchange Rates, Minimum 50\\% Utilisation**\n\n$$\n\\begin{aligned}\n\\min \\; &\\sum_{i\\in I}\\sum_{j\\in J} u_{ij} x_{ij} \\\\\n\\text{s.t. } &\\sum_{i\\in I} x_{ij} = D_j \\quad \\forall j\\in J \\quad \\text{Demand satisfaction} \\\\\n&\\sum_{j\\in J} x_{ij} \\le K_i\\quad \\forall i\\in I \\quad \\text{Capacity constraints} \\\\\n&\\sum_{j\\in J} x_{ij} \\ge 0.5 K_i \\quad \\forall i\\in I \\quad \\text{Minimum 50\\% utilisation} \\\\\n&x_{ij} \\ge 0 \\quad \\forall i\\in I, j\\in J \\quad \\text{Non-negativity}\n\\end{aligned}\n$$\n\n**(b) No Production Limits**\n\nIn this case, capacity constraints and minimum utilisation constraints are removed.\n\n$$\n\\begin{aligned}\n\\min \\; &\\sum_{i\\in I}\\sum_{j\\in J} u_{ij} x_{ij} \\\\\n\\text{s.t. } &\\sum_{i\\in I} x_{ij} = D_j \\quad \\forall j\\in J \\quad \\text{Demand satisfaction} \\\\\n&x_{ij} \\ge 0 \\quad \\forall i\\in I, j\\in J \\quad \\text{Non-negativity}\n\\end{aligned}\n$$\n\nThis is the classical uncapacitated transportation problem.\n\n**(c) Allow 10\\% Capacity Expansion**\n\nIntroduce binary decision variables:\n\n$$\nz_i =\n\\begin{cases}\n1 & \\text{if plant } i \\text{ expands by 10\\%} \\\\\n0 & \\text{otherwise}\n\\end{cases}\n$$\n\nExpanded capacity:\n\n$$\n(1+0.1 z_i)K_i\n$$\n\n$$\n\\begin{aligned}\n\\min \\; &\\sum_{i\\in I}\\sum_{j\\in J} u_{ij} x_{ij} \\\\\n\\text{s.t. } &\\sum_{i\\in I} x_{ij} = D_j \\quad \\forall j\\in J \\quad \\text{Demand satisfaction} \\\\\n&\\sum_{j\\in J} x_{ij} \\le (1+0.1 z_i)K_i\\quad \\forall i\\in I \\quad \\text{Expanded capacity constraints} \\\\\n&\\sum_{j\\in J} x_{ij} \\ge 0.5 K_i \\quad \\forall i\\in I \\quad \\text{Minimum 50\\% utilisation} \\\\\n&z_i \\in \\{0,1\\} \\quad \\forall i\\in I \\quad \\text{Binary expansion decision} \\\\\n&x_{ij} \\ge 0 \\quad \\forall i\\in I, j\\in J \\quad \\text{Non-negativity}\n\\end{aligned}\n$$\n\nTo determine whether expansion reduces cost, compare the optimal objective value of this model with that of part (a)\n\n**(d) Accounting for Exchange Rate Uncertainty**\n\nExchange rates should be treated as uncertain parameters.\n\n- **Stochastic Programming**\n\nLet $s\\in S$ be scenarios with probability $\\pi_s$ and exchange rates $r_i^{(s)}$.\n\n$$\n\\min \\sum_{s\\in S} \\pi_s \n\\sum_{i\\in I}\\sum_{j\\in J}\n\\left( r_i^{(s)} p_i + c_{ij} \\right)\nx_{ij}^{(s)}\n$$\n\nsubject to demand and capacity constraints (with optional non-anticipativity constraints if decisions must be made before rates are known).\n\n- **Robust Optimisation**\n\nIf exchange rates lie in uncertainty set $\\mathcal{R}$:\n\n$$\n\\min_{x} \\;\n\\max_{r\\in \\mathcal{R}}\n\\sum_{i\\in I}\\sum_{j\\in J}\n\\left( r_i p_i + c_{ij} \\right) x_{ij}\n$$\n\nThis protects against worst-case exchange rate realizations.\n\n- **Financial Hedging**\n\nOperational optimisation can be combined with financial instruments (forwards/options) to hedge currency exposure.\n\n- **Rolling Horizon Re-optimisation**\n\nRe-solve the optimisation model periodically using updated exchange rates and demand forecasts.\n\n:::\n\n",
    "supporting": [
      "02solutions_files"
    ],
    "filters": [],
    "includes": {}
  }
}